Pretty Disposals
DeltaV-Station/Delta-v pull request #1009
Opened 2024-03-26 15:37 UTC by rosieposieeee

## About the PR

Brings back the old disposal sprites, and adds a 'space' variant that warns you that it goes to space. (Otherwise, the space one is no different than a normal one.)

If anyone has a better idea than a generic yellow warning triangle I'll sprite it.

![QR7aqBY9Ru](https://github.com/DeltaV-Station/Delta-v/assets/52761126/b243dcd9-93a9-49d1-894a-99399fe19f6f)

<img width="355" alt="Content Client_zmlLtlqNMP" src="https://github.com/DeltaV-Station/Delta-v/assets/52761126/684300a3-1ea0-462e-a747-7891df61d78f">

![image](https://github.com/DeltaV-Station/Delta-v/assets/52761126/1c89165c-c14c-47f4-8c0b-6f3b5679a549)

## Why / Balance

The new sprites were ugly, and I had to make a new RSI for the space one anyway (or touch the upstream RSI, but I didn't want to.)

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- tweak: Added Space Disposals with a warning sign on them, and made disposals pretty again.

2024-03-26 15:50 UTC, DangerRevolution commented
bringing back old sprite should be it's own PR for easy reversal should it be wanted/needed down the line

2024-03-26 15:51 UTC, DangerRevolution commented
are all the pipes & unused intake sprites necessary in the new folder?

2024-03-26 15:51 UTC, rosieposieeee commented
> bringing back old sprite should be it's own PR for easy reversal should it be wanted/needed down the line

space disposals relies on it, otherwise i would have to touch upstream files

2024-03-26 15:53 UTC, DangerRevolution commented
> > bringing back old sprite should be it's own PR for easy reversal should it be wanted/needed down the line
> 
> space disposals relies on it, otherwise i would have to touch upstream files

you can PR the old sprites & PR the space sprites; and ask for the old sprites to be merged first so it works

2024-03-26 15:53 UTC, rosieposieeee commented
> > > bringing back old sprite should be it's own PR for easy reversal should it be wanted/needed down the line
> > 
> > 
> > space disposals relies on it, otherwise i would have to touch upstream files
> 
> you can PR the old sprites & PR the space sprites; and ask for the old sprites to be merged first so it works

yeah but if it was undone, you'd have to undo both anyway

2024-03-27 16:31 UTC, IamVelcroboy commented
The question is, *should* I warn the prisoners in Hive....

2024-03-28 09:51 UTC, UnicornOnLSD commented
amazing, god bless my beloved old chutes

2024-03-28 19:19 UTC, DEATHB4DEFEAT requested changes

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
```

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
```

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
```

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
```

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
```

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
```

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
```

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
```

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
            "delays": [ [ 0.1, 0.1, 0.1, 0.1, 0.1, 0.5, 0.1, 0.1, 0.1 ] ]
```

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
            "delays": [ [ 0.1, 0.1, 0.1, 0.1, 0.1, 0.5, 0.1, 0.1, 0.1 ] ]
```

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
            "delays": [ [ 0.4, 0.4 ] ]
```

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
            "delays": [ [ 0.2, 0.2 ] ]
```

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
```

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
```

2024-03-28 19:19 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            ]
```suggestion
```

2024-03-28 19:46 UTC, FluffiestFloof reviewed
should fix the tests
thanks death

2024-03-28 19:46 UTC, FluffiestFloof commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "directions": 1,
```suggestion
            "directions": 1
```

2024-03-28 19:46 UTC, FluffiestFloof commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "directions": 1,
```suggestion
            "directions": 1
```

2024-03-28 19:46 UTC, FluffiestFloof commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "directions": 1,
```suggestion
            "directions": 1
```

2024-03-28 19:46 UTC, FluffiestFloof commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "directions": 1,
```suggestion
            "directions": 1
```

2024-03-28 19:46 UTC, FluffiestFloof commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "directions": 1,
```suggestion
            "directions": 1
```

2024-03-28 19:46 UTC, FluffiestFloof commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "directions": 1,
```suggestion
            "directions": 1
```

2024-03-28 19:46 UTC, FluffiestFloof commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "directions": 1,
```suggestion
            "directions": 1
```

2024-03-28 19:46 UTC, FluffiestFloof commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "directions": 1,
```suggestion
            "directions": 1
```

2024-03-28 19:46 UTC, FluffiestFloof commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "directions": 1,
```suggestion
            "directions": 1
```

2024-03-28 19:46 UTC, FluffiestFloof commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "directions": 1,
```suggestion
            "directions": 1
```

2024-03-28 19:46 UTC, FluffiestFloof commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "directions": 1,
```suggestion
            "directions": 1
```

2024-03-28 19:50 UTC, rosieposieeee commented
lol

2024-04-04 17:28 UTC, IamVelcroboy commented
Looks fine to me. Just waiting to see if any other maintainers have thoughts...?

2024-04-08 08:23 UTC, deltanedas submitted a review, later dismissed
long live the king

2024-04-09 03:47 UTC, DEATHB4DEFEAT requested changes

2024-04-09 03:47 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +        }
```suggestion
        {
            "name": "condisposal",
        },
        {
            "name": "conmailing",
        },
        {
            "name": "conspace",
        },
        {
            "name": "disposal",
        },
        {
            "name": "mailing",
        },
        {
            "name": "space",
        },
        {
            "name": "disposal-charging",
        },
        {
            "name": "mailing-charging",
        },
        {
            "name": "disposal-flush",
            "delays": [ [ 0.1, 0.1, 0.1, 0.1, 0.1, 0.5, 0.1, 0.1, 0.1 ] ]
        },
        {
            "name": "mailing-flush",
            "delays": [ [ 0.1, 0.1, 0.1, 0.1, 0.1, 0.5, 0.1, 0.1, 0.1 ] ]
        },
        {
            "name": "dispover-charge",
            "delays": [ [ 0.4, 0.4 ] ]
        },
        {
            "name": "dispover-full",
            "delays": [ [ 0.2, 0.2 ] ]
        },
        {
            "name": "dispover-handle",
        },
        {
            "name": "mailover-handle",
        },
        {
            "name": "dispover-ready",
        }
```

2024-04-11 05:14 UTC, DEATHB4DEFEAT approved these changes, later dismissed

2024-04-11 05:15 UTC, DEATHB4DEFEAT commented
Fix tests then this looks good.

2024-05-26 15:03 UTC, Colin-Tel commented
Any update? Tests are still failing.

2024-05-26 15:16 UTC, DangerRevolution reviewed
this should fix le PR

2024-05-26 15:16 UTC, DangerRevolution commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "name": "condisposal",
```suggestion
            "name": "condisposal"
```

2024-05-26 15:16 UTC, DangerRevolution commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "name": "conmailing",
```suggestion
            "name": "conmailing"
```

2024-05-26 15:16 UTC, DangerRevolution commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "name": "conspace",
```suggestion
            "name": "conspace"
```

2024-05-26 15:16 UTC, DangerRevolution commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "name": "disposal",
```suggestion
            "name": "disposal"
```

2024-05-26 15:16 UTC, DangerRevolution commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "name": "mailing",
```suggestion
            "name": "mailing"
```

2024-05-26 15:16 UTC, DangerRevolution commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "name": "space",
```suggestion
            "name": "space"
```

2024-05-26 15:16 UTC, DangerRevolution commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "name": "disposal-charging",
```suggestion
            "name": "disposal-charging"
```

2024-05-26 15:16 UTC, DangerRevolution commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "name": "mailing-charging",
```suggestion
            "name": "mailing-charging"
```

2024-05-26 15:16 UTC, DangerRevolution commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "name": "dispover-handle",
```suggestion
            "name": "dispover-handle"
```

2024-05-26 15:16 UTC, DangerRevolution commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "name": "mailover-handle",
```suggestion
            "name": "mailover-handle"
```

2024-05-26 15:16 UTC, DangerRevolution commented on Resources/Textures/DeltaV/Structures/Piping/disposal.rsi/meta.json
> +            "name": "dispover-ready",
```suggestion
            "name": "dispover-ready"
```

2024-05-27 03:36 UTC, rosieposieeee commented
laziness ops wins again

2024-07-20 18:04 UTC, IamVelcroboy commented
👻

2024-07-20 18:12 UTC, Timemaster99 commented
Should revive this

2024-07-20 18:18 UTC, Timemaster99 commented on Resources/Prototypes/DeltaV/Entities/Structures/Piping/Disposal/space_disposal.yml
> +      map: [ "enum.DisposalUnitVisualLayers.BaseFlush" ]
```suggestion
      map: [ "enum.DisposalUnitVisualLayers.OverlayFlush" ]
```
this should fix test errors

2024-09-02 11:31 UTC, adeinitas commented
As the oldest open PR in the repo, what's the consensus on if we want old disposals? I'm so used to the new sprite that I kinda forgot how nice this one looked.

2024-09-05 05:27 UTC, TadJohnson00 commented
I would like old disposals back, I think this is neat.

2024-09-05 05:45 UTC, ghost approved these changes
Yeah this looks fine. Let's try it.

2024-09-05 05:46 UTC, merged