Fixed Cargo Bounties
DeltaV-Station/Delta-v pull request #1010
Opened 2024-03-26 17:51 UTC by blueDev2

## About the PR

Fixed Cargo Bounties

## Why / Balance

Players tend to want the bounties to work so that they don't have to depend on mail for funds.

## Technical details

Made bounty label components also hold the station where it was printed, so that the main station's bounty DB is used instead of the automated trade station's bounty DB

## Media

TODO

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-03-26 18:39 UTC, Adrian16199 commented on Content.Server/Cargo/Systems/CargoSystem.Bounty.cs
> +                    entities.Add(child);
Im now going to nitpick.
```suggestion
                 entities.Add(child);
```

2024-03-26 18:48 UTC, FluffiestFloof commented
Should probably add markers to note what is being changed, and that those are deltav changes.
Also shouldn't this be directly fixed upstream if it's an overall issue?

2024-03-26 19:17 UTC, Adrian16199 commented
> Should probably add markers to note what is being changed, and that those are deltav changes. Also shouldn't this be directly fixed upstream if it's an overall issue?

To the first thing, yeah, I didnt said much as this is a draft and alot can change so I would wait till its functional.
Regarding the second thing, this is not an upstream issue as debug made automated trading station be different aka it spawning on a different universe compared to the station that you work on in here.

2024-03-26 19:33 UTC, deltanedas commented
this still would be nice for upstream so it would support multi station sharing a trade station but using each stations bounties

2024-03-26 19:37 UTC, Adrian16199 commented
> this still would be nice for upstream so it would support multi station sharing a trade station but using each stations bounties

You are not wrong.

2024-03-26 21:23 UTC, blueDev2 commented
Still working on this, but if anyone knows how to make the logs actually go to the terminal, it would be much appreciated


> Should probably add markers to note what is being changed, and that those are deltav changes. Also shouldn't this be directly fixed upstream if it's an overall issue?

I'm not sure what markers you are talking about.

2024-03-26 21:25 UTC, blueDev2 commented
Do you think I really should make this an upstream PR?

2024-03-26 21:29 UTC, Adrian16199 commented
> > Should probably add markers to note what is being changed, and that those are deltav changes. Also shouldn't this be directly fixed upstream if it's an overall issue?
> 
> I'm not sure what markers you are talking about.

The markers are pretty much just notes that indicate that an upstream file was touched that usually goes like: # DELTA V-Fixes Cargo Bountys

2024-03-26 21:31 UTC, Adrian16199 commented
> Do you think I really should make this an upstream PR?

It would be a good attempt as deltanedas suggested, it would fix it and less upstream file touched that are different from wizden.
I would keep this in draft and just open it if they wont accept it upstream.
I dont think they would deny it as it basicly makes bountys not just go kapoot just because its not on the same galaxy and the code could be used aswell on any other thing for any future ideas.

2024-03-27 03:54 UTC, blueDev2 commented
> > > Should probably add markers to note what is being changed, and that those are deltav changes. Also shouldn't this be directly fixed upstream if it's an overall issue?
> > 
> > 
> > I'm not sure what markers you are talking about.
> 
> The markers are pretty much just notes that indicate that an upstream file was touched that usually goes like: # DELTA V-Fixes Cargo Bountys

Where am I supposed to mark that down?

2024-03-27 08:23 UTC, Adrian16199 commented
> Where am I supposed to mark that down?

So basicly

{
  (Wizden code but changed on delta V) # Delta V- Fixes cargo bountys [aka the point of PR, helps with github blame]
  (Wizden code)
  (Wizden code but changed on delta V) # Delta V- Fixes cargo bountys
}
Second example
{
   (Wizden code but changed on delta V) # Delta V- Start of Fixes cargo bountys
   (Wizden code but changed on delta V)
   (Wizden code but changed on delta V) # Delta V- End of Fixes cargo bountys
}

2024-03-27 08:59 UTC, Axionyxx requested changes
Here's just a few I had time for right now

2024-03-27 08:59 UTC, Axionyxx commented on Content.Server/Cargo/Components/CargoBountyLabelComponent.cs
> +
Why do you need this imported here?

2024-03-27 08:59 UTC, Axionyxx commented on Content.Server/Cargo/Components/CargoBountyLabelComponent.cs
> +    /// The Station System to check and remove bounties from
```suggestion
    /// DeltaV - The Station System to check and remove bounties from
```

2024-03-27 08:59 UTC, Axionyxx commented on Content.Server/Cargo/Systems/CargoSystem.Bounty.cs
> +using Serilog;
Don't use Serilog

2024-03-27 08:59 UTC, Axionyxx commented on Content.Server/Cargo/Systems/CargoSystem.Bounty.cs
> +        SetupBountyLabel(label, station, bounty.Value);
```suggestion
        SetupBountyLabel(label, station, bounty.Value); // DeltaV - Track owning station
```

2024-03-27 08:59 UTC, Axionyxx commented on Content.Server/Cargo/Systems/CargoSystem.Shuttle.cs
> +using Content.Shared.Database;
You don't need this here

2024-03-27 15:49 UTC, blueDev2 commented
I'm gonna wait until a final decision is made on the upstream PR before adding code markers.
I do appreciate you giving me some examples though.

2024-03-27 15:53 UTC, stellar-novas commented
> Do you think I really should make this an upstream PR?

Yes, this is a flaw with the bounty system that would also affect wizden, and their downstreams, if they put the station on a different map.

If they don't accept it for whatever reason, which I doubt, can just reopen this pr.

2024-03-28 14:45 UTC, blueDev2 commented
Upstream PR merged: https://github.com/space-wizards/space-station-14/pull/26469
I will close this PR and make a new PR by pulling the 3 applicable upstream files.

2024-03-28 14:45 UTC, closed without merging