New horns for oni.
DeltaV-Station/Delta-v pull request #1030
Opened 2024-03-28 18:32 UTC by Adrian16199

## About the PR

I added new horns and fixed marking ftl
Sprites were made by PS3MOIRA
## Why / Balance

These sprites were made and simply it took a moment from various of reasons for them to be pull resquested here.
So I have simply ported them here myself.
## Technical details

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/ac93e16c-e834-432e-af82-1da29ab4aece)
![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/8527f0fc-67a6-441d-b6c0-eb42daa76a9e)

## Breaking changes

**Changelog**

:cl:
- add: Added new horn designs for onis.

2024-03-28 19:12 UTC, DEATHB4DEFEAT requested changes
Move this to the DeltaV namespace

2024-03-28 19:36 UTC, Adrian16199 commented
> Move this to the DeltaV namespace

Done

2024-03-28 20:51 UTC, Axionyxx approved these changes

2024-04-04 17:05 UTC, IamVelcroboy commented
> Move this to the DeltaV namespace

This review is blocking merge and I can't find a way to dismiss it. Looks like it was addressed.

2024-04-04 21:43 UTC, DEATHB4DEFEAT approved these changes

2024-04-04 21:43 UTC, merged