shipyard rewrite/port
DeltaV-Station/Delta-v pull request #1171
Opened 2024-05-07 05:47 UTC by deltanedas

## About the PR
port shipyard from pre rebase, but:
- a ship can have multiple categories, unused group is now a category
- console whitelist support added so you can have centcom shipyard, nukie shipyard, emagged normal shipyard console, etc.
- a good bit of the console code is in shared so access is predicted
- instead of managing a single shipyard map and doing fucky stuff to make sure spawned ships dont hit eachother, ships get their own temporary map similar to the loneop shuttle.
  once it enters ftl space the temporary map gets deleted
- RENAMED PROSPECTER TO PROSPECTOR, GRAMMAR!!!!

currently unobtainable i forgor how its meant to be gotten

2024-05-07 14:14 UTC, Axionyxx commented
UI code got changed with the incoming merge, this will have to wait until after that is merged

2024-05-07 15:13 UTC, deltanedas commented
yep has a comment to update when merged

2024-05-07 21:43 UTC, Axionyxx requested changes
I'm gonna request 2 things here.

An arbitrage test, and a test that makes sure shuttles are valid (if there isn't already a test that does this.)

2024-05-07 21:46 UTC, deltanedas commented
> a test that makes sure shuttles are valid

as in having != 1 grids? shuttles being loadable is tested already

2024-05-07 21:47 UTC, Axionyxx commented
> > a test that makes sure shuttles are valid
> 
> as in having != 1 grids? shuttles being loadable is tested already

Stuff like that, yes. Along with making sure there's a shuttle console, and at least 1 dock

2024-05-09 14:30 UTC, Shadowwailker commented
Shipyard isn't meant to be obtainable,  im pretty sure it's one of the consoles meant to be mapped into bridge, might add it to shuttle creation though

2024-05-09 15:11 UTC, deltanedas commented
yeah mapping being in locker or research whatevers best

2024-05-09 16:14 UTC, Axionyxx reviewed
Fix all arbitrages and I'll approve

2024-05-09 17:34 UTC, IamVelcroboy commented
> yeah mapping being in locker or research whatevers best

Was previously mapped on the bridge

2024-05-09 17:35 UTC, IamVelcroboy commented
We should add warp points to all the shuttles too. Can be in a follow up PR but should be done eventually.

2024-05-09 18:30 UTC, Axionyxx commented
> We should add warp points to all the shuttles too. Can be in a follow up PR but should be done eventually.

When thats done, it should be added to the tests too. Ensure the shuttles always have a warp point

2024-05-09 18:30 UTC, Axionyxx commented
But should probably be a seperate pr lol

2024-05-10 04:50 UTC, deltanedas commented
test itself has dirty disposing but theres no arbitrage, can fix test now or later

2024-05-14 00:15 UTC, Axionyxx requested changes
One small nitpick, lgtm otherwise

2024-05-14 00:15 UTC, Axionyxx commented on Content.Shared/CCVar/CCVars.cs
We have our own cvars file iirc

2024-05-15 12:09 UTC, Axionyxx approved these changes

2024-05-15 12:18 UTC, merged