DeltaV species guidebook entries
DeltaV-Station/Delta-v pull request #1174
Opened 2024-05-07 23:34 UTC by Axionyxx

## About the PR
I copied these straight from the wiki.

I noticed that we didn't have any while testing loadouts

**Changelog**
:cl:
- add: Vulpkanin, felinids, oni and harpies now have guidebook entries

2024-05-08 00:38 UTC, deltanedas requested changes

2024-05-08 00:38 UTC, deltanedas commented on Resources/ServerInfo/Guidebook/Mobs/DeltaV/Oni.xml
> +  - They have an easier type prying open doors, taking around 50% less time than other species.
time

2024-05-08 00:48 UTC, Axionyxx commented on Resources/ServerInfo/Guidebook/Mobs/DeltaV/Oni.xml
> +  - They have an easier type prying open doors, taking around 50% less time than other species.
Huh? I just copied it from the wiki

2024-05-08 01:29 UTC, deltanedas commented on Resources/ServerInfo/Guidebook/Mobs/DeltaV/Oni.xml
> +  - They have an easier type prying open doors, taking around 50% less time than other species.
easier time not easier type

2024-05-08 01:49 UTC, Axionyxx commented on Resources/ServerInfo/Guidebook/Mobs/DeltaV/Oni.xml
> +  - They have an easier type prying open doors, taking around 50% less time than other species.
Ohhh, I see it now

2024-05-09 16:32 UTC, Axionyxx commented on Resources/ServerInfo/Guidebook/Mobs/DeltaV/Oni.xml
> +  - They have an easier type prying open doors, taking around 50% less time than other species.
Fixed

2024-05-09 20:06 UTC, deltanedas approved these changes

2024-05-18 19:37 UTC, merged