Add Premade Merc Roles for admenes
DeltaV-Station/Delta-v pull request #1256
Opened 2024-05-26 03:00 UTC by Tryded

## About the PR

adds cool loadouts for admenes to use
## Why / Balance

there are 4 main roles:
Squad Leader: Armed with L6 Saw, pinpointer, and flares. Their job is to lead their squad while occasionally giving suppressive fire.

Sergeant: Assists Squad Leader with leadership and is armed with an AKM and plastic explosives for breaking into rooms.

Mercenary Corpsman: Does medic stuff

Mercenary Rifleman: Armed with an AKM and has the main task of following the Leader's orders. They shoot stuff.

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:

ADMIN

- add: Added mercenary squad loadouts for admenes.

2024-05-26 03:35 UTC, Tryded commented
Will finish FTL files and EVA stuff tommorrow

2024-05-27 03:07 UTC, Tryded commented
what does these errors mean :elp:

2024-05-30 03:06 UTC, Tryded commented
ready for review

2024-06-04 16:00 UTC, Colin-Tel requested changes
Some minor .yml housekeeping

2024-06-04 16:00 UTC, Colin-Tel commented on Resources/Locale/en-US/deltav/job/job-description.ftl
This file shouldn't be touched.

2024-06-04 16:00 UTC, Colin-Tel commented on Resources/Locale/en-US/deltav/job/job-names.ftl
> +job-name-mercsquadleader = Mercenary Squad Leader
```suggestion
job-name-mercsquadleader = Mercenary Squad Leader

```

2024-06-04 16:00 UTC, Colin-Tel commented on Resources/Locale/en-US/deltav/job/job-supervisors.ftl
> +job-supervisors-mercsergeant = the sergeant
```suggestion
job-supervisors-mercsergeant = the sergeant

```

2024-06-04 16:00 UTC, Colin-Tel commented on Resources/Prototypes/DeltaV/Catalog/Fills/Backpacks/StarterGear/backpack.yml
> +    - id: Zipties
```suggestion
    - id: Zipties
    
```

2024-06-04 16:00 UTC, Colin-Tel commented on Resources/Prototypes/DeltaV/Entities/Objects/Misc/identification_cards.yml
> +    - External
```suggestion
    - External
    
```

2024-06-04 16:00 UTC, Colin-Tel commented on Resources/Prototypes/DeltaV/Roles/Jobs/Fun/merc_startinggear.yml
> +    pocket1: FlashlightSeclite
```suggestion
    pocket1: FlashlightSeclite
    
```

2024-06-04 16:00 UTC, Colin-Tel commented on Resources/Prototypes/_NF/Entities/Clothing/Head/hardsuit-helmets.yml
> +        Heat: 0.9
```suggestion
        Heat: 0.9
        
```

2024-06-04 16:00 UTC, Colin-Tel commented on Resources/Prototypes/_NF/Entities/Clothing/OuterClothing/hardsuits.yml
> +    clothingPrototype: ClothingHeadHelmetHardsuitMerc
```suggestion
    clothingPrototype: ClothingHeadHelmetHardsuitMerc
    
```

2024-06-04 16:24 UTC, Lyndomen commented
Love the idea here, headmin approved.

2024-06-04 21:39 UTC, Tryded commented on Resources/Locale/en-US/deltav/job/job-description.ftl
I thought I reverted all of these.. hold on

2024-06-04 23:24 UTC, Tryded commented
No idea why tests are failing, something to do with nuke ops

2024-06-13 17:13 UTC, TadJohnson00 commented
Is this intended to replace nukeops?

2024-06-13 17:17 UTC, Lyndomen commented
> Is this intended to replace nukeops?

Nope, just prefabbed spawns for admin events.

2024-06-13 19:32 UTC, TadJohnson00 commented
In that case, I strongly suggest avoiding the AKMS, it's unbalanced for most intents and purposes. Use the Tenebra and Pollock instead, they were both custom made for mercenaries to use as rough approximates to station weapons. Same goes for the SAW, but at least its power and capacity are limited by its accuracy. and unwieldiness.

2024-06-21 16:22 UTC, closed without merging

2024-06-21 16:41 UTC, Tryded commented
Wait why did it close

2024-06-21 16:42 UTC, Tryded commented
All my code disappeared after I accidentally discarded all changes on the branch.. bruh