Increased security PDAs' cartridge slots by 2
DeltaV-Station/Delta-v pull request #1266
Opened 2024-05-28 04:41 UTC by Remuchi

## About the PR
Increased cartridge slots for all security PDAs to compensate for SecWatch and CrimeAssist. Now security can once again install other programs.

## Why / Balance
Couldn't install LogProbe or any other program on any security PDA after the addition of SecWatch and CrimeAssist. Huge disadvantage for detective.

:cl:
- tweak: Cartridge slots in all security PDAs were increased by 2 to compensate for the addition of SecWatch and CrimeAssist.

2024-05-28 04:54 UTC, Colin-Tel commented
I wonder if it'd instead be better to attach the 
```
  - type: CartridgeLoader # DeltaV - Crime Assist + SecWatch, increased diskSpace by 2 to fit them
    diskSpace: 7
```
to `BasePDA` since it'd cover everything.

2024-05-28 05:04 UTC, Remuchi commented
I had a thought about it but didn't really wanna go into changing BasePDA as this problem only appears in security PDAs. Changing it to all PDAs is a balance thing I suppose (tho we don't really have enough cartridges so it would matter anyway)

2024-05-28 05:14 UTC, WarMechanic commented
Why should security PDA's specifically have more cartridges? If anything, epistemics PDA's would see future development in PDA apps so it doesn't really make sense, as opposed to BasePDA.

2024-05-28 07:37 UTC, Axionyxx requested changes
The PR body is too lacking. This absolutely needs screenshots in game to show this doesn't cause issues. If anything, the increase could probably be upstreamed too

2024-05-28 07:54 UTC, Remuchi commented
I'll add screenshots a bit later.
About the increased limit, the problem described in the issue only happens with DeltaV security PDAs since DeltaV modifies starting programs in them. It doesn't affect the overall limit as security can install only 2 more programs on their PDAs as any other PDA on the station.
Although maybe the epi PDAs should have increased limit as well

2024-05-28 12:19 UTC, Remuchi commented
![image](https://github.com/DeltaV-Station/Delta-v/assets/72476615/09c58c11-e66a-490a-812c-7ef57669146d)

New limit is right enough so it fits without scrolling

2024-06-01 21:17 UTC, Axionyxx approved these changes

2024-06-01 21:17 UTC, merged