Security Service Access 1984
DeltaV-Station/Delta-v pull request #1287
Opened 2024-06-02 16:26 UTC by Colin-Tel

## About the PR

sec can no longer whack service workers in their job areas without breaking down the wall

## Why / Balance

There isn't much of a reason for sec to be able to barge into service-locked rooms willy nilly. If there's a reason, they can fetch someone with the access (i.e. command) or get assigned the access with an ID computer.

**Changelog**

:cl:
- remove: Security personnel no longer have service access by default.

2024-06-02 17:25 UTC, Axionyxx requested changes

2024-06-02 17:25 UTC, Axionyxx commented on Resources/Prototypes/Roles/Jobs/Security/detective.yml
> +  #- Service # Delta V: Access adjustments 02June2024
These don't need to be dated, it looks weird and doesn't match anything else in the codebase

2024-06-02 17:26 UTC, Colin-Tel commented on Resources/Prototypes/Roles/Jobs/Security/detective.yml
> +  #- Service # Delta V: Access adjustments 02June2024
wilco

2024-06-03 18:49 UTC, therealDLondon commented
Headmin approved btw

2024-06-04 07:02 UTC, Axionyxx approved these changes

2024-06-04 07:02 UTC, merged