Make flatpacks mappable
DeltaV-Station/Delta-v pull request #1288
Opened 2024-06-02 16:50 UTC by IamVelcroboy

## About the PR
Removes hideSpawnMenu from flatpacks so they can be mapped

## Why / Balance
Mainly for engine setups when we don't want to map an entire crate but simply add a piece or two. Could also be used in salvage wrecks down the line.

2024-06-04 07:01 UTC, Axionyxx requested changes
A base item should never be mappable. You should override categories on the entities you want to map, or create crates for them.

2024-06-04 07:02 UTC, Axionyxx commented
You can also just use `spawn PrototypeId` in the console to spawn any item regardless of nospawn or hideSpawnMenu

2024-06-04 15:39 UTC, IamVelcroboy commented
> A base item should never be mappable. You should override categories on the entities you want to map, or create crates for them.

Should this just be abstracted then? Is there any case/use for a generic flatpack?

2024-06-04 20:40 UTC, deltanedas commented
> Is there any case/use for a generic flatpack?

this machine called flatpacker 9001 :trollface:

2024-07-22 15:17 UTC, Colin-Tel commented
Gonna close this for the time being.

2024-07-22 15:17 UTC, closed without merging