Tiny loadout patch
DeltaV-Station/Delta-v pull request #1316
Opened 2024-06-07 01:41 UTC by Timemaster99

## About the PR
Fixed a couple of loadout issues introduced by #1269 

## Why / Balance

## Technical details
Changed HoPMess loadout item to HoPMessSkirt, and added the jumpsuit variation
Added minLimit for salvage and chem neck slots, so they aren't forced to wear a neck item

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
Tiniest changes, so it probably doesn't need a CL.

2024-06-07 07:05 UTC, Axionyxx requested changes

2024-06-07 07:05 UTC, Axionyxx commented on Resources/Prototypes/Loadouts/Jobs/Command/head_of_personnel.yml
> +    jumpsuit: ClothingUniformJumpsuitHoPMess
These should be added to our own loadouts file

2024-06-14 07:30 UTC, Timemaster99 commented on Resources/Prototypes/Loadouts/Jobs/Command/head_of_personnel.yml
> +    jumpsuit: ClothingUniformJumpsuitHoPMess
Moved all the items from the loadout PR to our own file now

2024-06-19 22:46 UTC, Timemaster99 commented
Added MG cloak and beret to this as well

2024-07-15 07:09 UTC, adeinitas approved these changes
Was about to say "The HoP's winter boots have a spelling error" but they seem to just be like that for the item itself. Regardless of that, this is a quality of life thing that I've been wondering if there was a fix to FOR SOME TIME, so I'm glad to see it.
Null, by the way, dismiss your review on this, the changes were made.

2024-07-22 16:52 UTC, Axionyxx approved these changes

2024-07-22 18:18 UTC, merged