add syndicate recruiter midround event
DeltaV-Station/Delta-v pull request #1345
Opened 2024-06-10 19:04 UTC by deltanedas

## About the PR
adds a recruiter event, their job is to interview people on the station and hire the best candidates for the syndicate. ask some questions and write the answers, do up a contract whatever you want works
all that matters is that once you have the paperwork done, the candidate uses your special recruiter pen to prick their finger and sign it with their blood. this gives you the sweet greentext but since its an mrp server you are expected to actually do some recruiting and not nrp postal 2 "will you please sign my petition".

you also arent allowed to recruit mindshielded people or yourself for obvious reasons. if you want to recruit an ex-seccie get an implanter to remove the mindshield :trollface:

the objectives are simple:
- escape
- recruit a random number of people using the mechanism above
- keep your pen safe, it has the dna of everyone you recruited

## Why / Balance
had a lot of good rp with it as selfantag, now its realantag :trollface:

the RecruiterPen component can also be reused for non syndicate (e.g. tgmc recruiter) admeme events with uploaded prototypes

## Technical details
- added `SignAttemptEvent` for signatures to get cancelled, used by recruiter pen
- `RecruiterPen` component makes a pen need blood to sign paper and lets you prick your finger to refill it with blood

## Media
rules should make it reasonably clear what you have to and cant do
![19:40:32](https://github.com/DeltaV-Station/Delta-v/assets/39013340/2dfb8eba-defd-4d9f-972e-2d0767cb185e)

valid...
![19:48:43](https://github.com/DeltaV-Station/Delta-v/assets/39013340/51f62c53-2456-4332-87d9-db4546478c60)

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: Syndicate Recruiters have started trying to hire people from the station!

2024-06-11 09:25 UTC, dvir001 commented
Time to hire punpun

2024-06-11 12:03 UTC, noctyrnal commented
I feel like adding the recruitment objective to regular agents and letting them buy 1 pen for free could be a cool RP-friendly objective for them too

2024-06-11 15:46 UTC, WarMechanic commented
![image](https://github.com/DeltaV-Station/Delta-v/assets/69510347/994ea796-a3d8-4756-9987-d1791e39c48f)

will the syndicate recruiter have a way to give new employees syndicate clothes?

2024-06-11 16:18 UTC, deltanedas commented
> will the syndicate recruiter have a way to give new employees syndicate clothes?

no its just "you will get mission and gear after centcom" meme right now, but the ship could be expanded with some valid gear
though it would make it harder to set up shop somewhere on station because then either you have to go back to the ship for the drip or bring it with you and be giga sus

2024-06-12 16:16 UTC, Axionyxx requested changes
Upstream is merged

2024-06-12 16:16 UTC, Axionyxx commented on Content.Shared/DeltaV/Recruiter/SharedRecruiterPenSystem.cs
> +        // TODO: when upstream merged make this use whitelist system blacklist helper functions
TODO pro

2024-06-30 17:34 UTC, Axionyxx submitted a review, later dismissed
Fix the conflict and I'll merge it

2024-07-09 10:47 UTC, Axionyxx approved these changes

2024-07-09 10:48 UTC, merged