Prosecutor antag fix
DeltaV-Station/Delta-v pull request #1360
Opened 2024-06-12 04:18 UTC by Timemaster99

## About the PR

This was supposed to be the case from the start. Also added mindshield in line with the rest of sec

## Why / Balance

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: Timemaster99
- tweak: Prosecutor can no longer be an antagonist.

2024-06-12 16:12 UTC, Axionyxx requested changes

2024-06-12 16:12 UTC, Axionyxx commented on Resources/Prototypes/DeltaV/Roles/Jobs/Justice/prosecutor.yml
> +    implants: [ MindShieldImplant ]
They don't need a mindshield implant, just canBeAntag is enough

2024-06-12 18:37 UTC, Timemaster99 commented on Resources/Prototypes/DeltaV/Roles/Jobs/Justice/prosecutor.yml
> +    implants: [ MindShieldImplant ]
Fixed

2024-06-13 16:42 UTC, Axionyxx approved these changes

2024-06-13 16:42 UTC, merged