rename glimmershow
DeltaV-Station/Delta-v pull request #1365
Opened 2024-06-12 17:11 UTC by MilonPL

## About the PR

Changed "glimmershow" to "showglimmer"

## Why / Balance

All of the commands start with "show". OCD.

## Media
- [X] This PR does not require an ingame showcase

**Changelog**

:cl:
DELTAVADMIN:
- tweak: Renamed "glimmershow" to "showglimmer".

2024-06-12 17:13 UTC, Axionyxx requested changes

2024-06-12 17:13 UTC, Axionyxx commented on Content.Server/Nyanotrasen/Psionics/Glimmer/GlimmerCommands.cs
> +[AdminCommand(AdminFlags.Debug)] // Delta-V - Set to Debug flag
I know this'd make it match the set command, but given all it does is show the glimmer, just admin would be fine

2024-06-12 17:14 UTC, deltanedas commented
glimmerset: :trollface:

also i dont think the comments matter for nyano files since le dead

2024-06-12 17:16 UTC, MilonPL commented
> also i dont think the comments matter for nyano files since le dead

i can't risk a lawsuit in this economy

2024-06-12 17:22 UTC, deltanedas commented
well to not risk lawsuit youd have to keep the mit license notice in every nyano file, not just add `# stolen from nyano` everywhere :trollface:

2024-06-13 16:41 UTC, Axionyxx approved these changes

2024-06-13 16:41 UTC, merged