Wake up Sleepy Agents
DeltaV-Station/Delta-v pull request #1389
Opened 2024-06-15 19:19 UTC by Lyndomen

## About the PR
Enable Sleeper Agents. 

## Why / Balance
Traitors are a good mechanic. No longer a busted event. 
Decrease weight from 8 to 5. Increases max number of sleepy fellows to 4 instead of 2. 
Fox & I like it. 

## Technical details
YAML edit

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- add: Sleeper Agents are waking up!

2024-06-15 20:07 UTC, deltanedas requested changes

2024-06-15 20:07 UTC, deltanedas commented on Resources/Prototypes/GameRules/events.yml
> +    id: NinjaSpawn
troller

2024-06-16 10:33 UTC, ShatteredSwords commented
> Lyndomen : wakeupjoebiden
Advanced branch naming.
Anywho, now no survival or nukeops is safe from SleepOps

2024-06-16 12:01 UTC, deltanedas approved these changes

2024-06-20 20:36 UTC, merged