Senior ID cards get a custom job name: Attempt 3
DeltaV-Station/Delta-v pull request #1425
Opened 2024-06-22 04:14 UTC by WarMechanic

## About the PR

Lorem ipsum while I add some comments, to the code. Just like last time, except Job Prototypes are no longer used.

## Why / Balance

Fixes https://github.com/DeltaV-Station/Delta-v/issues/1263

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Fixed senior roles not displaying properly

2024-07-22 16:48 UTC, Axionyxx requested changes
I know I didn't either, but these should really be using localized job names. Looks good besides that

2024-07-25 12:50 UTC, WarMechanic commented
i think i bunged something up, i had to pull my git files while working here in america.

2024-08-04 21:48 UTC, WarMechanic commented
all the errors have been fixed, and i have playtested the solution and found everything to be working. i think its good to go

2024-08-06 21:20 UTC, Axionyxx approved these changes

2024-08-06 21:20 UTC, merged