Unique glove fibers
DeltaV-Station/Delta-v pull request #1455
Opened 2024-07-03 05:43 UTC by WarMechanic

## About the PR

Every pair of gloves now has its own fingerprint, so items can be traced back to gloves which can then be traced back to people.

## Why / Balance

Evidence is very important to court cases running smoothly, so detectives now have more evidence that can certify whether or not John Syndicate's behaviour is valid. Traitors are now encouraged to either clean evidence off syndicate gear regardless of glove status, or use a disposable pair of gloves specifically for handling syndicate gear to be disposed of later.

Aside from being required to obfuscate evidence you leave behind, there is now a value proposition to searching glove prints of departments. Wearing gloves that does not correspond your department can punish an unknowing detective into searching the wrong people.

## Technical details

`FiberComponent.cs` now stores a Fiberprint variable like `FingerprintComponent.cs`. The code for assigning a fiberprint is the same as the fingerprint. When evidence is placed on an object, the fiberprint is concatenated to its localised fiber type.

## Media

hm ok we have these specific gloves on an akms
![image](https://github.com/DeltaV-Station/Delta-v/assets/69510347/55819ed3-1e89-401f-b7fb-0d8569bd7aa2)
hm well we found the gloves and they have fingerprints
![image](https://github.com/DeltaV-Station/Delta-v/assets/69510347/a9b21171-bee5-4c5f-8ec6-cf5576572d45)
gotem
![image](https://github.com/DeltaV-Station/Delta-v/assets/69510347/d6254f48-2d81-4702-ac03-c1c796712ef4)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-07-03 06:54 UTC, DangerRevolution commented
Test fail doesn't seem skbidi

2024-07-03 13:38 UTC, noctyrnal commented
no more will yellow insulative fibres be the end of a case

2024-07-08 12:56 UTC, deltanedas requested changes

2024-07-08 12:56 UTC, deltanedas commented on Content.Server/Forensics/Components/FiberComponent.cs
> +        public string? Fiberprint;
deltav comment

2024-07-08 12:56 UTC, deltanedas commented on Content.Server/Forensics/Systems/ForensicsSystem.cs
> +        private void OnFiberInit(EntityUid uid, FiberComponent component, MapInitEvent args)
deltav comment

2024-07-08 12:56 UTC, deltanedas commented on Content.Server/Forensics/Systems/ForensicsSystem.cs
> +        public string GenerateFingerprint(int length = 16)
.

2024-07-08 12:56 UTC, deltanedas commented on Content.Server/Forensics/Systems/ForensicsSystem.cs
> +                    var fiberLocale = string.IsNullOrEmpty(fiber.FiberColor)
.

2024-07-08 13:55 UTC, WarMechanic commented
i forgor the comments

2024-07-08 13:55 UTC, deltanedas submitted a review, later dismissed

2024-07-08 13:55 UTC, deltanedas commented
moths keep winning

2024-07-08 13:57 UTC, WarMechanic commented
did i just fuck it up

2024-07-08 14:12 UTC, Axionyxx approved these changes
Reapproving because only a whitespace got added

2024-07-08 14:12 UTC, merged

2024-07-08 14:12 UTC, WarMechanic commented
thank you null