Pending changes exported from your codespace
DeltaV-Station/Delta-v pull request #1474
Opened 2024-07-09 13:27 UTC by ProphetCrow

## About the PR
Adds the "Waffle Iron", which is a syndicate energy pistol that is based off the svalinn laser pistol (SLP). The weapon is currently as powerful as the laser rifle (LR), and starts with a medium powercell, giving it two less shots than the LR. Currently, this weapon is able to be purchased in any uplink for 8TC. 

## Why / Balance
It's cool. / It gives syndicates a laser weapon that operates uniquely compared to all the other energy weapons in the game, barring the SLP. 

## Technical details
*Added the WeaponLaserWaffle entity to the battery guns prototype. The code is similar to the SLP

*Added  the following component: 
- type: HitscanBatteryAmmoProvider
    proto: RedLaser
To both the Svalinn Laser Pistol and Waffle Iron during testing to see if I can change the weapon damage without changing the battery "magazine" damage. This added the "Inspect damage" verb to the weapons, but was bugged, displaying incorrect damage values as the damage is based off the magazine loaded and not the gun itself. Left the component attached, as without it, you cannot inspect damage values. 

*Adjusted projectile "RedLightLaser" damage from 7 to 14, this affects the Svalinn Laser Pistol and the Waffle Iron, doubling its base damage. This is a bandaid fix to the previously mentioned bug. 

*Added item to the weaponry tab of the uplink with its own description

*Known bug - The SLP and the Waffle Iron's ammo counter displays "x00" regardless of remaining shots. However, inspecting the weapon will accurately display the remaining charges of the tool. This is likely due to the ammo capacity being dynamically based off of powercell size instead of traditional energy tanks.  

*Known bug - Inserting a microreactor cell into the SLP or the Waffle Iron will not update the graphic whenever it gains new charges. If you deplete the charge of a microreactor cell in either weapon and let it recharge, it's sprite will display empty until the battery is ejected and reinserted. 

## Media

https://cdn.discordapp.com/attachments/1010560161888350340/1260071952534732820/Delta-v_2024-07-08_23-02-42.mp4?ex=668dfcf4&is=668cab74&hm=0b0b691c6c1fd0e8f3bc4cf66c82d4272149ca5e3cccbb9c1c719dd560516f43& / 

https://discord.com/channels/968983104247185448/1010560161888350340/1260071954694803518

- [ X ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Other

I plan to make this weapon reverse engineer-able in the future with a blue-kie sprite variant. As this affects balance, this will be in a separate PR. 

**Changelog**

:cl:
- add: Added Waffle Iron - A syndicate uplink laser pistol
- tweak: Adjusted damage of the power cell based energy weapons
- fix: Added inspection verb to the Svalinn Laser Pistol

2024-07-09 13:53 UTC, ProphetCrow commented
> This pull request has conflicts, please resolve those before we can evaluate the pull request.

resolved conflicts

2024-07-10 13:36 UTC, Yousifb26 commented
I feel like the damage should be nerfed a tad since it’s a little bit nutty that an epi antagonist can just get the upgraded version of the antique laser pistol since they can just make microreactors or print 50 high caps. I’d think that 12 damage would be a fair nerf since it’s just so easy to collect power cells

2024-07-10 15:41 UTC, ProphetCrow commented
> I feel like the damage should be nerfed a tad since it’s a little bit nutty that an epi antagonist can just get the upgraded version of the antique laser pistol since they can just make microreactors or print 50 high caps. I’d think that 12 damage would be a fair nerf since it’s just so easy to collect power cells

Sure, if the maintainers want to nerf the damage values, the code is in Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/hitscan.yml , RedLightLaser line. I modeled the damage after the laser rifle since I think that weapon is overall mediocre, but potentially infinite ammo is a concern. 

Telecrystal cost is in Resources/Prototypes/DeltaV/Catalog/uplink_catalog.yml if they want to adjust that too, I think 8 is fair when compared to the energysword and python. 

It should also be noted that the Antique laser uses RedMediumLaser - which does 17 damage currently.

2024-08-12 23:39 UTC, BlitzTheSquishy commented
There is somewhat a balancing reason on why syndicates arent provided energy weapons (disregarding the CHIMP upgrade chip and emag for the protolathe)

2024-08-20 08:43 UTC, DangerRevolution requested changes

2024-08-20 08:43 UTC, DangerRevolution commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/hitscan.yml
> +      Heat: 14 #7
```suggestion
      Heat: 14 # Delta-V : upgrades damage from 7 to 14
```

2024-08-20 08:43 UTC, DangerRevolution commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
Delta-V folder please.

2024-09-05 06:21 UTC, TadJohnson00 commented
As Blitz stated, there are pre-existing standards for balance regarding traitors. I'm generally opposed to granting them a laser weapon, first of all, let alone one with significant damage and the capability to be refilled from battery cells.

I advise against merging this PR until a proper discussion can be had on weapons balance and where traitors fall with regards to that.

2024-09-17 13:47 UTC, TadJohnson00 commented
@ProphetCrow Are you still working on this?

2024-11-08 19:16 UTC, PubliclyExecutedPig commented
ok but would EMP's affect it

2024-11-08 19:21 UTC, Avalon-Proto commented
Yes because EMPs effect all power cells

2024-11-15 05:50 UTC, TadJohnson00 commented
Closing this PR due to inactivity.

2024-11-15 05:50 UTC, closed without merging