Ports #566 from Einstein Engines : Refactor of Candy Fabrication (Nyano-code)
DeltaV-Station/Delta-v pull request #1525
Opened 2024-07-23 09:54 UTC by DangerRevolution

## About the PR

## Why / Balance

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-07-23 10:17 UTC, DangerRevolution commented
Please merge this with #1524

2024-07-26 10:57 UTC, deltanedas requested changes

2024-07-26 10:57 UTC, deltanedas commented on Content.Server/_EE/Abilities/Borgs/FabricateActionsComponent.cs
> +    public List<ProtoId<EntityPrototype>> Actions = new();
EntProtoId

2024-07-26 10:57 UTC, deltanedas commented on Content.Server/_EE/Abilities/Borgs/FabricateActionsComponent.cs
> +    public Dictionary<ProtoId<EntityPrototype>, EntityUid> ActionEntities = new();
no reason this cant just be List<EntityUid>

2024-07-26 10:57 UTC, deltanedas commented on Content.Server/_EE/Abilities/Borgs/FabricateActionsSystem.cs
> +        foreach (var actionId in entity.Comp.Actions)
add `entity.Comp.ActionEntities = new List<EntityUid>(entity.Comp.Actions.Count);`

2024-07-26 10:57 UTC, deltanedas commented on Content.Server/_EE/Abilities/Borgs/FabricateActionsSystem.cs
> +                entity.Comp.ActionEntities[actionId] = actionEntity.Value;
.Add(actionEntity.Value)

2024-07-26 10:57 UTC, deltanedas commented on Content.Server/_EE/Abilities/Borgs/FabricateActionsSystem.cs
> +        foreach (var (actionId, actionEntity) in entity.Comp.ActionEntities)
dont need to remove since its shutting down, just iterate each actionEntity in the list and ignore the index

2024-07-26 10:57 UTC, deltanedas commented on Content.Server/_EE/Abilities/Borgs/FabricateActionsSystem.cs
> +            if (actionEntity is not { Valid: true })
is not {}

2024-07-26 10:57 UTC, deltanedas commented on Content.Server/_EE/Abilities/Borgs/FabricateActionsSystem.cs
> +        if (args.Handled || !_actionBlocker.CanConsciouslyPerformAction(entity))
use `checkConsciousness: true` instead of copy pasta

2024-07-26 10:57 UTC, deltanedas commented on Content.Shared/_EE/Actions/Events/FabricateActionEvent.cs
> +    public ProtoId<EntityPrototype> Fabrication;
EntProtoId

2024-07-27 10:51 UTC, DangerRevolution commented
Will change on EE & bring back later

2024-07-27 10:51 UTC, closed without merging