Port "Supermatter Engine" from EE
DeltaV-Station/Delta-v pull request #1578
Opened 2024-08-04 06:41 UTC by WarMechanic

This one's been a long time coming. Finally, engineering gets more content.

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

Nope, it works

**Changelog**

VMSolidus, White Dream, Colin-Tel, WarMechanic
- add: Supermatter Engines have been implemented.

2024-08-04 07:30 UTC, deltanedas requested changes
all these files should be in ee or deltav folders

2024-08-04 07:30 UTC, deltanedas commented on Content.Shared/Supermatter/Components/SupermatterComponent.cs
> +    public bool Activated = false;
dont need = false

2024-08-04 07:30 UTC, deltanedas commented on Content.Shared/Supermatter/Components/SupermatterComponent.cs
> +    public string SliverPrototype = "SupermatterSliver";
EntProtoId

2024-08-04 07:30 UTC, deltanedas commented on Content.Shared/Supermatter/Components/SupermatterComponent.cs
> +    public bool SliverRemoved = false;
dont need = false

2024-08-04 07:30 UTC, deltanedas commented on Content.Shared/Supermatter/Components/SupermatterComponent.cs
> +    public string[] LightningPrototypes =
add datafield and use EntProtoId

2024-08-04 07:30 UTC, deltanedas commented on Content.Shared/Supermatter/Components/SupermatterComponent.cs
> +    public string SingularitySpawnPrototype = "Singularity";
entprotoid for all these...

2024-08-04 07:30 UTC, deltanedas commented on Content.Shared/Supermatter/Components/SupermatterComponent.cs
> +    public bool Delamming = false;
dont need

2024-08-04 07:30 UTC, deltanedas commented on Content.Shared/Supermatter/Components/SupermatterComponent.cs
> +    public bool DelamAnnounced = false;
dont need

2024-08-04 07:30 UTC, deltanedas commented on Content.Shared/Supermatter/Components/SupermatterComponent.cs
> +    public Dictionary<Gas, float> GasStorage = new Dictionary<Gas, float>()
should be using a GasMixture

2024-08-04 07:30 UTC, deltanedas commented on Content.Shared/Supermatter/Components/SupermatterComponent.cs
> +    public readonly Dictionary<Gas, (float TransmitModifier, float HeatPenalty, float PowerMixRatio)> GasDataFields = new()
GasFact exists

2024-08-04 07:57 UTC, DangerRevolution commented
THE GUIDEBOOK ENTRY NEEDS A TITLE STRING!!

2024-08-05 03:13 UTC, VMSolidus commented
> all these files should be in ee or deltav folders

Any changes you wish made to this PR should be made as a PR to the original source.

2024-08-13 01:20 UTC, VMSolidus commented
> all these files should be in ee or deltav folders

Make a PR of these to EE, the original source for the code here. I'll not have DV use an entire different version of Supermatter when it is maintained elsewhere.

2024-09-05 11:35 UTC, Samsterious commented
One of the problems we are faced with in Delta-V that is not a problem on Wizden is that teslaloose/singuloose/delam is not a fun or engaging mechanic for 99% of the station's crew. It is sudden death with zero agency. One engineer's mistake forces round end for the entire station.

I definitely think we want Supermatter, if only because they sound so fucking cool, but I think we should dedicate some time to thinking about how we can make these scenarios more engaging or whether we just want to make these engines fail gracefully (i.e. it stops working instead of killing everyone).

2024-09-07 16:06 UTC, Bonktrauma commented
> One of the problems we are faced with in Delta-V that is not a problem on Wizden is that teslaloose/singuloose/delam is not a fun or engaging mechanic for 99% of the station's crew. It is sudden death with zero agency. One engineer's mistake forces round end for the entire station. In an LRP context, "funni" is an adequate justification to blow up the station. In MRP, that does not suffice.


The thing is, You KNOW if it's going to delam, it warns you, ALOT and usually it's rather slow, so like singularity, aslong as you set it up properly, you should be fine

2024-09-20 13:13 UTC, TadJohnson00 commented
Is this still being worked on @WarMechanic?

2024-11-06 20:33 UTC, MilonPL commented
Since this PR has been set to draft and received no commits since being created 3 months ago, I will be closing it for now. If you ever return to this PR, feel free to open up a new submission.

2024-11-06 20:33 UTC, closed without merging