Adds Syndicate Robo-Neuroticist, a midround antag
DeltaV-Station/Delta-v pull request #1582
Opened 2024-08-05 22:26 UTC by Lyndomen

## About the PR
Adds Syndicate Robo-Neuroticist, a midround solo antag that spawns with the equipment to create and outfit an army of borgs. Draft PR while I finish a few loose ends, and finish up verbiage. 

## Why / Balance
Midround antag intended to pose a genuine threat to the station, one that can accomplish their objectives in a variety of methods. They start with enough equipment to create about 5ish borgs, and depending on their loadout option can have an additional one more. They have 1 Head Kill objective, an objective to steal the plutonium core, a survive objective, and a generic objective to cyborg-ify the crew. 

They have a custom shuttle with IFF, allowing them to lurk in space, but very little directly offensive tools themselves. This role is primarily limited to the ghosts and players at their disposal, as each borg must be inhabited by a player. 

## Technical details
Mostly YAML work. 

## Media
![image](https://github.com/user-attachments/assets/62a7ef1c-3f01-4b59-adc2-127c99b09ba1)
![image](https://github.com/user-attachments/assets/3ec5fee5-7bf2-4f62-ac86-6e1ffd4ec405)
![image](https://github.com/user-attachments/assets/686caceb-09aa-42a0-b206-bd423d06e11b)
![image](https://github.com/user-attachments/assets/55e3e26a-ad57-4ecd-bad7-158b47aaedd0)
![image](https://github.com/user-attachments/assets/64bf4933-35d1-4373-b476-6341fe6693ce)
![image](https://github.com/user-attachments/assets/fb5c0c8b-3de5-4569-848b-2a7faa24fd0e)
![image](https://github.com/user-attachments/assets/5e0b353c-ef18-4cac-aa38-8cbb9d4a61a4)
![image](https://github.com/user-attachments/assets/a7aec6b1-350d-4b65-8e47-2d9aa8301c0f)
![image](https://github.com/user-attachments/assets/e23a219d-6ba9-414a-bd8c-47fac7ecc5d1)
![image](https://github.com/user-attachments/assets/e6d02669-35b3-4c17-8f46-b6cefd64ca5e)
![image](https://github.com/user-attachments/assets/07c7923f-5ad0-4ec9-a7ce-fc93aa87a23e)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
No

**Changelog**
:cl:
- add: Syndicate Robo-Neuroticists have begun arriving in local space, converting entire stations into mechanical horrors

2024-08-05 22:30 UTC, deltanedas commented
we have clock cult at home

2024-09-25 10:43 UTC, MilonPL reviewed
ok here you go

2024-09-25 10:43 UTC, MilonPL commented on Resources/Locale/en-US/deltav/ghost/roles/ghost-role-component.ftl
> +                                           You are allowed to attack the crew and destroy the station without provocation.
Untouch this.

2024-09-25 10:43 UTC, MilonPL commented on Resources/Locale/en-US/deltav/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-silvia-description = You are Silvia the space snake and the CMO's charming companion.
untouch

2024-09-25 10:43 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Clothing/Eyes/hud.yml
> +  components:
you probably also want ShowHealthIcons if using the biological damageContainer

2024-09-25 10:43 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Clothing/Uniforms/jumpsuits.yml
> +
untouch

2024-09-25 10:43 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Devices/radio.yml
This could be used by security to easily intercept syndicate comms (which is what we wanted to avoid with the radio implanters) so needs further discussion.

2024-09-25 10:43 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Specific/Medical/rechargingsyndicatecrewmonitor.yml
> +- type: entity
every fucking yaml file in this PR has a different order, follow
```
type:
abstract:
parent:
id:
name:
description:
categories:
components:
```

2024-09-25 10:43 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Specific/Robotics/borg_modules.yml
yaml conventions...

2024-09-25 10:43 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Specific/Robotics/borg_modules.yml
> +  - type: ShowHealthBars
showhealthicons for biological too
if #32355 gets merged upstream the comps will default to the biological container so don't duplicate it

2024-09-25 10:43 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Objectives/roboticist.yml
> +  parent: [BaseRoboticistObjective, BaseSurviveObjective]
spaces for inline yaml, `[ BaseRoboticistObjective, BaseSurviveObjective ]`

2024-09-25 10:43 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Objectives/roboticist.yml
> +  parent: [BaseRoboticistObjective, BaseSurviveObjective]
spaces

2024-09-25 10:43 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Objectives/roboticist.yml
> +  parent: [BaseRoboticistObjective, BaseKillObjective]
spaces

2024-09-25 10:43 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Objectives/roboticist.yml
> +  parent: [BaseRoboticistObjective, BaseTraitorStealObjective]
spaces

2024-09-30 17:28 UTC, Lyndomen commented on Resources/Prototypes/DeltaV/Entities/Objects/Devices/radio.yml
only spawns right now in the borg module, and is not recoverable from said module. if they capture a borg with the module and force it to talk, kinda based

2024-09-30 17:28 UTC, Lyndomen commented on Resources/Prototypes/DeltaV/Entities/Objects/Specific/Medical/rechargingsyndicatecrewmonitor.yml
> +- type: entity
real

2024-09-30 17:28 UTC, Lyndomen commented on Resources/Prototypes/DeltaV/Entities/Objects/Specific/Robotics/borg_modules.yml
fake

2024-10-24 00:11 UTC, deltanedas commented
will need updating for https://github.com/space-wizards/space-station-14/pull/31318 too

2024-11-06 22:35 UTC, Lyndomen commented
Closed, should apparently be an issue. Who knew

2024-11-15 04:20 UTC, Lyndomen commented
waiting for AI real one day

2024-11-15 04:46 UTC, Avalon-Proto commented
I want this so badly please give it to me

Side note. How soon in round can it spawn again? Can it spawn at any time this allowing early spawns for devious long play or will it have the lone op issue where it coming spawns after the 1:30 mark

2024-11-15 04:47 UTC, Lyndomen commented
> I want this so badly please give it to me
merge ai faster 🦖 

i have to really just re-review everything about this, but the exact same timeframe as synthesist specialist- just rarer

2024-11-15 11:48 UTC, deltanedas commented
what does this need ai for

2024-11-15 11:53 UTC, Avalon-Proto commented
> what does this need ai for

He wants to give it an anti-mov board or something and give them to objective of subverting the AI

2024-11-15 11:56 UTC, deltanedas commented
just comment it out until ai is enabled :trollface:

2024-12-01 21:14 UTC, Stop-Signs commented
Holy shit, its back

2024-12-01 21:50 UTC, Yousifb26 commented
It might be worth giving them the overlord board

2024-12-01 21:54 UTC, Lyndomen commented
Yes real I was holding off on implementing this because I wanted their objectives to be related to AI and wow that's real now

2025-01-06 05:13 UTC, Lyndomen commented
this isnt strictly abandoned but @Stop-Signs indicated they might wanna pick this up for some work. afaik i left it pretty okay, objectives need work tho.

2025-02-04 21:58 UTC, Lyndomen commented
time to work through 10 morbillion merge conflicts

2025-02-04 22:01 UTC, Radezolid commented
Just draft it...

2025-02-04 22:02 UTC, Lyndomen commented
couldnt draft without unfucking merges

2025-02-17 03:41 UTC, ThataKat commented
Direction approved!

2025-02-18 21:08 UTC, deltanedas requested changes

2025-02-18 21:08 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Structures/Machines/lathe.yml
> +    board: ExosuitFabricatorMachineCircuitboard
this is for actual exofab

2025-02-18 21:08 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Objects/Tools/rechargingradiojammer.yml
> +  name: recharging radio jammer
most of this file is duped from the parent

2025-02-18 21:08 UTC, deltanedas commented on Resources/Prototypes/_DV/Entities/Clothing/Eyes/hud.yml
> +  parent: [ClothingEyesBase, ClothingEyesHudDiagnostic]
ClothingEyesBase is inherited

2025-02-18 21:08 UTC, deltanedas commented on Resources/Prototypes/_DV/Entities/Clothing/Uniforms/jumpsuits.yml
> +    sprite: _DV/Clothing/Uniforms/Jumpsuit/admin_assistant.rsi
untroll

2025-02-18 21:08 UTC, deltanedas commented on Resources/Prototypes/_DV/Entities/Clothing/Uniforms/jumpsuits.yml
> +  description: An suit fit with dozens of cybernetic gadgets.
an suit

2025-02-18 21:08 UTC, deltanedas commented on Resources/Prototypes/_DV/Entities/Markers/Spawners/ghost_roles.yml
> +      role: JobScientist
roboticist

2025-02-18 21:08 UTC, deltanedas commented on Resources/Prototypes/_DV/Entities/Markers/Spawners/ghost_roles.yml
> +      time: 14400 # 4h scientist so you know how to make robot
2h its not rocket science

2025-02-18 21:08 UTC, deltanedas commented on Resources/Prototypes/_DV/Entities/Objects/Devices/pda.yml
> +
only 1 empty line not 2

2025-02-18 21:08 UTC, deltanedas commented on Resources/Prototypes/_DV/Entities/Objects/Tools/rechargingradiojammer.yml
> +          visible: false
unindent by 4 spaces

2025-02-18 21:08 UTC, deltanedas commented on Resources/Prototypes/_DV/Entities/Objects/Tools/rechargingradiojammer.yml
> +          High: {state: jammer_high_charge}
this is inherited

2025-02-18 21:08 UTC, deltanedas commented on Resources/Prototypes/_DV/Objectives/roboticist.yml
> +  description: As precious as they are, your cyborgs are less valuable than your own life.
description below name for all these

2025-02-18 21:08 UTC, deltanedas commented on Resources/Textures/_DV/Clothing/Head/Helmets/eva_roboneuroticist.rsi/meta.json
indent meta.json to 4 spaces not mixed 4 and 2

2025-02-18 21:08 UTC, deltanedas commented on Resources/Textures/_DV/Clothing/OuterClothing/Suits/eva_roboneuroticist.rsi/meta.json
this ones indent is fucked

2025-02-19 04:17 UTC, deltanedas requested changes

2025-02-19 04:17 UTC, deltanedas commented on Resources/Prototypes/_DV/Entities/Objects/Specific/Robotics/mmi.yml
> +      stopSearchVerbPopup: positronic-brain-stopped-searching
only 2 of these fields arent inherited

also unindent these components by 2

2025-02-19 04:17 UTC, deltanedas commented on Resources/Prototypes/_DV/Entities/Structures/Machines/lathe.yml
> +  id: SyndicateExosuitFabricator
id below parent also this will inherit emag recipes as well as dynamic recipes

2025-02-19 04:17 UTC, deltanedas commented on Resources/Prototypes/_DV/Objectives/roboticist.yml
> +  parent: [ BaseRoboticistObjective, BaseTraitorStealObjective ]
BaseStealObjective

2025-02-19 04:17 UTC, deltanedas commented on Resources/Prototypes/_DV/Recipes/Lathes/Packs/robotics.yml
> +  - BorgModuleChameleonProjector
trailing newline

2025-02-19 04:17 UTC, deltanedas commented on Resources/Prototypes/_DV/Roles/Antags/roboneuroticist.yml
> +    role: JobScientist
sync with spawner

2025-02-19 04:17 UTC, deltanedas commented on Resources/Prototypes/_DV/Objectives/roboticist.yml
> +  description: The AI is causing us problems. Update its laws so it wont be an annoyance. We have given you a board on your shuttle!
its in starting gear not shuttle

2025-02-19 04:17 UTC, deltanedas commented on Resources/Prototypes/_DV/Roles/Antags/roboneuroticist.yml
> +    - AntimovCircuitBoard
wrong lawset

2025-02-19 04:24 UTC, Lyndomen commented on Resources/Prototypes/_DV/Entities/Structures/Machines/lathe.yml
> +  id: SyndicateExosuitFabricator
thats fine imo, more gaming later in a round

2025-02-21 17:27 UTC, Avalon-Proto commented
Fur some reason I can't see the requested change, but surely this is just about set to merge by now :v

2025-02-21 21:28 UTC, Lyndomen commented
> Fur some reason I can't see the requested change, but surely this is just about set to merge by now :v

yeah i got no clue

2025-02-22 00:42 UTC, deltanedas requested changes

2025-02-22 00:42 UTC, deltanedas commented on Resources/Prototypes/_DV/Entities/Objects/Specific/Robotics/borg_modules.yml
> +    - state: icon-syndicate
make an abstract parent BaseBorgModuleSyndie with the sprite to reduce copy paste

2025-02-22 00:42 UTC, deltanedas commented on Resources/Prototypes/_DV/GameRules/unknown_shuttles.yml
> +  - type: RuleGrids
this might be inherited

2025-02-22 00:42 UTC, deltanedas commented on Content.Shared/_DV/Roles/RoboticistRole.cs
rename to RoboNeuroticist or something people will think roboticist is valid in the future

2025-02-22 00:42 UTC, deltanedas commented on Resources/Textures/_DV/Clothing/Head/Helmets/eva_roboneuroticist.rsi/meta.json
these are all still mixed

2025-02-23 15:32 UTC, deltanedas requested changes

2025-02-23 15:32 UTC, deltanedas commented on Content.Shared/_DV/Roles/NeuroRoboticistRole.cs
> +[RegisterComponent]
still need to rename the class and its uses

2025-02-23 16:19 UTC, deltanedas approved these changes, later dismissed

2025-02-23 16:28 UTC, deltanedas submitted a review, later dismissed

2025-02-23 16:38 UTC, Lyndomen commented
shit i forgor a ftl file

2025-02-23 16:40 UTC, Lyndomen commented
all done now sorry for commit spam was control F searching for everything to rename, it is all 100% consistent now

2025-02-23 17:08 UTC, deltanedas approved these changes

2025-02-23 17:09 UTC, merged