Mothroach Operatives
DeltaV-Station/Delta-v pull request #1594
Opened 2024-08-10 13:41 UTC by DarkenedSynergy

## About the PR

Added a nuclear operative mothroach to the syndicate uplink, with fitting reinforcement radio.
## Why / Balance

As spoken about in https://discord.com/channels/968983104247185448/1213723732183613480! Adds more options to the "allies" section of the uplink. Similar to the mouse operative all be it with slightly different drawbacks.
## Technical details

Mainly yml.
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
(soon :tm:)
![mothperatives](https://github.com/user-attachments/assets/bd8f19c0-b866-43e9-b6fe-36ae5c9928d6)

## Breaking changes

**Changelog**

:cl:
add: Added mothroach operative reinforcements to the uplink to work alongside their cheesy brethren!

2024-08-13 17:42 UTC, DarkenedSynergy commented
Had the same issue as the mouse reinforcement teleporter having the wrong parent with the recent upstream merge

2024-08-20 08:25 UTC, MilonPL commented on Resources/Prototypes/Datasets/Names/mothroach_death_commando.yml
Should be in the DeltaV folder.

2024-08-20 08:27 UTC, DangerRevolution requested changes

2024-08-20 08:27 UTC, DangerRevolution commented on Resources/Prototypes/Datasets/Names/mothroach_death_commando.yml
Delta-V folder please

2024-08-20 08:27 UTC, DangerRevolution commented on Resources/Locale/en-US/deltav/ghost/roles/ghost-role-component.ftl
> +                                           You are allowed to attack the crew and destroy the station without provocation.
```suggestion
                                           You are allowed to attack the crew and destroy the station without provocation.

```

Leave a line for better readability

2024-08-20 08:27 UTC, DangerRevolution commented on Resources/Locale/en-US/deltav/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-silvia-description = You are Silvia the space snake and the CMO's charming companion.
why is this touched?

2024-08-20 08:27 UTC, DangerRevolution commented on Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/nukiemothroach.yml
> +  parent: MobCockroach
Why is this parented to Cockroach?

You can cut down the components to like... three or four by not parenting it to the cockroach

2024-08-20 08:27 UTC, DangerRevolution commented on Resources/Prototypes/DeltaV/Entities/Mobs/NPCs/nukiemouse.yml
> -  - type: AutoTraitor
Why are you changing this?

2024-08-20 08:27 UTC, DangerRevolution commented on Resources/Prototypes/Entities/Objects/Devices/Syndicate_Gadgets/reinforcement_teleporter.yml
> +
?

2024-08-20 08:27 UTC, DangerRevolution commented on Resources/Textures/Mobs/Animals/mothroach.rsi/meta.json
Fix this.

2024-08-20 08:27 UTC, DangerRevolution commented on Resources/Textures/DeltaV/Objects/Devices/communication.rsi/plushie-radio.png
This doesn't really fit in line with the cheese radio mouse operatives use; plus this is extremely valid

2024-08-20 08:27 UTC, DangerRevolution commented on Resources/Textures/DeltaV/Objects/Devices/communication.rsi/meta.json
> +    "size": {
?

2024-09-05 07:21 UTC, TadJohnson00 commented
Will require further discussion but, ideally, we'll be moving away from animal reinforcements in future (i.e. syndicats and mouse ops). Hopefully we'll have a consensus by the time this PR is up for review.

2024-09-17 13:58 UTC, TadJohnson00 commented
@DarkenedSynergy is this PR still being worked on?

2024-09-21 12:35 UTC, DarkenedSynergy commented
> @DarkenedSynergy is this PR still being worked on?

Ill probably get to it at somepoint, not an urgent thing to PR. But yes I plan on finishing this.

2024-11-26 10:56 UTC, MilonPL commented
Heya! Since this PR has gotten no commits or activity in the past 3 months, I'm going to close it. If you ever come back to this, feel free to open a new PR.

2024-11-26 10:56 UTC, closed without merging