Lower age requirement of command roles to 18.
DeltaV-Station/Delta-v pull request #1611
Opened 2024-08-12 22:54 UTC by flyingkarii

## About the PR
Lower age requirement of command roles to 18.

## Why / Balance
Should generally not need your character to be older than 18.

## Technical details
YML change.

## Media
None

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- tweak: Lowered command age requirement to 18.

2024-08-12 23:06 UTC, Colin-Tel reviewed
Needs Project Manager approval first.

2024-08-12 23:28 UTC, BlitzTheSquishy commented
Feels like a non-issue, wouldnt want someone JUST out of highschool running my station, and theres no real reason to up it either

2024-08-13 00:24 UTC, Alyx-Wander commented
As a project manager, my own opinion is that if this is to be changed at all, it should be towards the removal of the limit rather than lowering it to an arbitrary amount. It doesn't really add anything mechanically or in terms of roleplay, but does have the ability to exclude players who'm may want to play with non-human life-spans. As an example, synethics who set their age as their date of manufacture, some of the awakened animal characters we have (Soup is an example, although they don't play Command they do play a character with a natural cat's lifespan), and doubtless other examples.

Instead of lowering the requirement to an arbitrary number, we think it'd just be better to outright remove it for the net-zero gain the feature gives us, and the real exclusionary downside it provides as well. Even excluding a handful of players seems like too steep a price for no-benefit.

2024-08-13 07:22 UTC, deltanedas requested changes
these all need deltav comments and commenting out instead of removal

2024-08-13 07:22 UTC, deltanedas commented on Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
> +      requiredAge: 18
pro

2024-09-05 07:27 UTC, TadJohnson00 commented
Is this still being worked on @flyingkarii ?

2024-09-05 10:35 UTC, Samsterious commented
This is one of those debates that is a result of a feature nobody asked for or needed in the first place. Creating an IC age requirement to play a certain role is a strange restriction in a server that includes players 17 and up, and the "highschoolers in command" argument is an easy knee-jerk response but does not actually mean anything in the context of roleplay standards.

The reality is that we have numerous extant characters on this server that are directly harmed by this mechanic: synthetic, genetically-engineered, anomalous, and littlespace characters are all excluded from command. These types of characters are most often written by our _best_ roleplayers, not our worst.

Nobody in real life is actually benefiting from this mechanic. Its benefits are seen purely within the fiction of the world. It betrays the ethos of Delta-V by excluding a queer identity that is expressed by several of our players, including some of our administration. This PR should be merged _with haste_.

2024-09-06 21:32 UTC, ghost submitted a review, later dismissed

2024-09-06 21:43 UTC, ghost commented
@deltanedas your requested changes are preventing this from being merged and I have no clue why

2024-09-06 22:42 UTC, deltanedas approved these changes

2024-09-07 04:38 UTC, merged