Elite suit un nerf
DeltaV-Station/Delta-v pull request #1639
Opened 2024-08-16 22:13 UTC by Squishy77

## About the PR
Un-nerfed the elite suit to its previous state

## Why / Balance
The elite suits main benefit was speed - as of its description, removing that and the cost removing that aspect removes its very purpose of existence. I feel like a better balance would be had if we nerfed the defense stats rather than its speed stats if it becomes a problem on delta. 

## Technical details
changed the hard suit stats and the uplink cost to their pre nerfed version 

## Media
N/A

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

-None I hope

**Changelog**

- tweak: changed the elite suit back to its pre nerfed version.

2024-08-16 23:33 UTC, deltanedas requested changes

2024-08-16 23:33 UTC, deltanedas commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    sprintModifier: 1.0
comment

2024-08-16 23:42 UTC, Timemaster99 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 10 #dv change- makes it the same cost as it was beofre
```suggestion
    Telecrystal: 10 #DeltaV - makes it the same cost as it was before
```
Spelling error. It's also good to spell out the name so people know where exactly it came from

2024-08-17 00:11 UTC, therealDLondon commented
The elite suit was nerfed for being too powerful, and with good reason, with the heat resist it has, plus the complete and entire lack of slowdown, making it have slightly lesser speed and increased cost balances out the immense heat resist you get from such a suit.

You're paying less-so for speed, more so for heat resist. 80% is insane.

Ill still put it to an admin discussion

2024-08-17 00:32 UTC, therealDLondon commented
After a brief discussion among some admins, and testing, the heat resist and explosion resist are, infact, incredibly strong. The cost of 12TC for massive heat reduction (3 dmg from caps laser) and the ability to facetank an RPG balance the speed penalty too.
You arent paying for speed, you're paying to massively resist the stations best 2 weapons against you.

2024-08-17 00:32 UTC, closed without merging