Better insectoid glasses (round 2)
DeltaV-Station/Delta-v pull request #1670
Opened 2024-08-23 18:20 UTC by HTMLSystem

## About the PR

This adds custom sprites for arachnids and moths for all glasses and huds. 
## Why / Balance

It's so the glasses actually cover the species eyes. There are many players, myself included, that avoid wearing glasses and some huds (or have to use the eyepatches) because they look dumb on those species. This fixes that.
## Technical details

Sprite stuff and whatnot. 
## Media

![353158625-8226dbde-07bf-4c16-88e7-fda94e5c0c1c](https://github.com/user-attachments/assets/74eec0cf-becd-4327-9b8b-b349aa420151) ![353158648-2b4832d7-5157-40e3-aa11-124567cf6f49](https://github.com/user-attachments/assets/aef9c578-5a94-42c0-8631-daf85fbe241b) ![353158661-0b10124c-d04c-41de-8231-3527e9d8df3b](https://github.com/user-attachments/assets/1dc2411e-8206-4f88-a555-946625d36696)
![353158674-39825ccb-f5ce-43da-a30c-d72f9a6fe87d](https://github.com/user-attachments/assets/22167d76-f6fe-4c7b-bc7f-c76e9a95852d) ![353158683-c831ff56-55c6-41a1-aecb-289088cef589](https://github.com/user-attachments/assets/a3b00456-2cb6-4241-a25d-ce4d068a41cf) ![353158688-4ec7bc6e-ed92-4d4f-84d2-9a3811422ad3](https://github.com/user-attachments/assets/eebc58ef-0057-4c73-9a96-d49f12b57725)

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A
**Changelog**

Nuh uh

2024-08-23 20:17 UTC, HTMLSystem commented
This is ready to be merged whenever.

2024-08-26 23:43 UTC, adeinitas reviewed
Minor spelling error on most meta.jsons - modified is spelled "motified."
I've looked at all of this - and this might sound controversial, but:
the vast majority of this PR touches upstream items, so you might wanna PR it up there considering that's where moths and arachnids are maintained. 
I can help you out if you have trouble doing that.
I commend your effort to make glasses that fit arachnids and moths because there's a lot of them that just don't fit and kinda look like ass on those species

2024-08-27 02:34 UTC, HTMLSystem commented
My habit of mispelling words strikes again.
I'll fix those later. In the meantime you could dm me on discord (or I could dm you, whichever happens first) on PRing this upstream.

2024-10-13 14:19 UTC, HTMLSystem commented
So, the PR upstream has been in review for about a month and they seem a bit dead set on me using displacement maps for some of the glasses (which I'm not very willing to do). Would there be any problems if this is merged early here instead of waiting on upstream?

2024-10-13 15:39 UTC, HTMLSystem commented
The test fail seems unrelated? My dev environment boots up fine without any issues or warnings, and the yaml looks completely fine. None of the warnings look related either. Though maybe I'm overlooking something...

2024-11-03 09:37 UTC, deltanedas requested changes
ideally there would be a verb on clothing or a character preference to disable using species specific sprites

2024-11-03 09:37 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
> +    speciesId: arachnid # DeltaV - allow arachnid clothing sprite variants
add the speciesId bit to the existing Inventory component at the bottom (dont remove it just to place it here)

2024-11-03 09:37 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
> +    speciesId: arachnid #DeltaV - Allows the "dummy" in th elobby menu to wear the arachnid sprites
th elobby :trollface:

2024-11-03 09:37 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/Species/moth.yml
> +    speciesId: moth # Deltav - allows moth clothing sprite variants
same, dont move it for no reason

2025-03-07 00:16 UTC, HTMLSystem commented
Closing because it was merged upstream!!

2025-03-07 00:16 UTC, closed without merging