Minor Justice Fixes
DeltaV-Station/Delta-v pull request #1680
Opened 2024-08-25 12:18 UTC by Lyciata

## About the PR
I really just made it so now CJ nows need Clerk time again, gave CJ a flash since they were the only command with no flash and I put the Clerk's outfits inside the uniform printer

## Why / Balance
Just some minor details that I felt like could be changed

## Technical details
Haven't tried nor can I try so let's pray it works!

## Media

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Can't test it so I can't say if it will actually works

**Changelog**
:cl:
- add: Added Clerk suit and skirt into the Uniform Printer
- tweak: Chief Justice now need Clerk time again
- tweak: Chief Justice will now spawn with a flash in their backpack

2024-08-25 12:22 UTC, deltanedas requested changes

2024-08-25 12:22 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Roles/Jobs/Justice/chief_justice.yml
> +      time: 36000 # DeltaV - 10 hours
dont need deltav comment since its in deltav file

2024-08-25 12:36 UTC, deltanedas approved these changes

2024-08-25 12:37 UTC, deltanedas commented
all you need to do is add recipes in deltav folder and its good

2024-09-20 13:39 UTC, TadJohnson00 commented
@Lyciata is this still being worked on?

2024-11-03 09:42 UTC, deltanedas commented
stale

2024-11-03 09:42 UTC, closed without merging