Harpy Customization Pack 1
DeltaV-Station/Delta-v pull request #175
Opened 2023-10-14 22:27 UTC by evilexecutive

## About the PR
This is the first of the promised content PRs for harpies, and also includes some bugfixes. 

## Why / Balance
-4 new wing patterns are added. Two Tone, Three Tone, Speckled, Undertone, and Feather Tips
-The HUD bug has been fixed
-Sparrow Tail has been removed for REASONS. 

## Media

![New customization](https://github.com/DeltaV-Station/Delta-v-rebase/assets/16548818/ed0303bd-3354-4a6f-a7ff-64e4ac8a47a2)

2023-10-15 16:34 UTC, Colin-Tel commented
![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/113523727/3201435d-8f87-439a-8d74-8921c517a487)
The "Phoenix Tail" seems to be the default tail, the only reason a player would add it again is if they want to change the color of the tail. It comes across as a bug-at-first-sight, which I think could be addressed by just calling it "Basic Tail" much like the "Basic Wings"

2023-10-15 16:36 UTC, Colin-Tel commented
![image](https://github.com/DeltaV-Station/Delta-v-rebase/assets/113523727/cee2c0ee-ce9a-46c6-bc64-aba69fee3c79)
There's also missing localization strings when it comes to *all* harpy markings.

2023-10-15 17:29 UTC, evilexecutive commented
I've made the requested changes.

2023-10-16 07:15 UTC, DebugOk requested changes

2023-10-16 07:15 UTC, DebugOk commented on Content.Server/DeltaV/Harpy/HarpySingerSystem.cs
Why subscribe to the same event twice

2023-10-16 23:04 UTC, evilexecutive commented on Content.Server/DeltaV/Harpy/HarpySingerSystem.cs
Let's hope the rogue semicolon doesn't strike again

2023-10-16 23:05 UTC, DebugOk commented
I still like how the customization code makes markings flesh colored by default. Flesh wings!

2023-10-16 23:06 UTC, DebugOk commented
> ![image](https://user-images.githubusercontent.com/113523727/275340133-cee2c0ee-ce9a-46c6-bc64-aba69fee3c79.png) There's also missing localization strings when it comes to _all_ harpy markings.

This is a bug:tm: unrelated to harpies (probably)

I also saw it on moths

2023-10-16 23:07 UTC, evilexecutive commented
>This is a bug™️ unrelated to harpies (probably)
>I also saw it on moths

Oh it's not, check the localization files on this PR for the fix. You can also apply that to moths

2023-10-16 23:07 UTC, DebugOk approved these changes, later dismissed
Code looks good enough, the rest Colin can review

2023-10-16 23:25 UTC, DEATHB4DEFEAT reviewed
muh formatting

2023-10-16 23:25 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/Harpy/HarpySingerSystem.cs
> +        public override void Initialize()
```suggestion
        [Dependency] private readonly InstrumentSystem _instrument = default!;
        [Dependency] private readonly MobStateSystem _mobState = default!;


        public override void Initialize()
```

2023-10-16 23:25 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/Harpy/HarpySingerSystem.cs
> +        {
```suggestion
        }


        //Immediately closes the Midi UI window if a Singer is incapacitated
        private void HarpyStopSinging(EntityUid uid, InstrumentComponent component, MobStateChangedEvent args)
        {
```

2023-10-17 21:04 UTC, Colin-Tel approved these changes
🐦

2023-10-17 21:12 UTC, merged