upstream merge 7/9
DeltaV-Station/Delta-v pull request #1762
Opened 2024-09-07 13:39 UTC by deltanedas

## Notable additions
- uplink discounts are real, deltav and nyano listings updated for it
- atmos alerts computer is now functional
- grappling gun is roundstart gear
- ai is less buggy
- ghost role rule updates, deltav ones still used where they override things like spiders and slimes

## Notable exclusions
- removed instant death snail from the event
- mysta keeps the binary key until ai is rolled out

**Changelog**
:cl:
- add: Merged upstream changes from last week.

2024-09-08 04:12 UTC, TadJohnson00 requested changes
Taking a brief peep through the commits, apparently these were the only lines that raised issues.

2024-09-08 04:12 UTC, TadJohnson00 commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml
> +    WeaponGrapplingGun: 2
Following review, we'd appreciate this commented out. Grapple guns break the physics too much and may be pending removal from research also.

2024-09-08 04:12 UTC, TadJohnson00 commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml
> +    ClothingMaskNeckGaiterRed: 3
Please comment out

2024-09-08 04:12 UTC, TadJohnson00 commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/secdrobe.yml
> +    ClothingHeadHelmetJustice: 1
Please also comment out

2024-09-08 04:31 UTC, IamVelcroboy commented
Really curious about the action bar change in mapping after you load a few maps....will there be any screen left? 

(Side note: I should just PR the load acts files so everyone can ignore that anyway)

2024-09-09 15:20 UTC, TadJohnson00 approved these changes
Requested changes done, direction stamp of approval given.

2024-09-09 15:20 UTC, merged