adds centcomm jello
DeltaV-Station/Delta-v pull request #177
Opened 2023-10-15 05:17 UTC by toasterpm87

## About the PR

## Why / Balance

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2023-10-15 15:56 UTC, Colin-Tel requested changes
There's no way to obtain this in-game.

2023-10-15 15:56 UTC, Colin-Tel commented on Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Food/snack.yml
> +  parent: FoodsnackBase
```suggestion
  parent: FoodSnackBase
```

2023-10-15 15:56 UTC, Colin-Tel commented on Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Food/snack.yml
> +      state: jello
```suggestion
      state: Jello
```

2023-10-15 15:56 UTC, Colin-Tel commented on Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Food/snack.yml
> +          maxVol: 1
```suggestion
          maxVol: 3
```
The reagents that compose the jello exceed the capacity of the jello.

2023-10-15 19:35 UTC, toasterpm87 commented
> There's no way to obtain this in-game.

thats intentional

2023-10-15 20:03 UTC, DebugOk requested changes

2023-10-15 20:03 UTC, DebugOk commented on Resources/Textures/DeltaV/Objects/Consumable/Food/centcommjello.rsi/meta.json
> +    "copyright": "Adei",
Adei? Adei who? From where?

2023-10-15 20:06 UTC, toasterpm87 commented on Resources/Textures/DeltaV/Objects/Consumable/Food/centcommjello.rsi/meta.json
> +    "copyright": "Adei",
discord, she plays lukusha and valentin

2023-10-26 14:54 UTC, Colin-Tel commented
Closing this for now.

2023-10-26 14:54 UTC, closed without merging