feat: Different Oracle Bark Types, default to Never
DeltaV-Station/Delta-v pull request #1786
Opened 2024-09-10 20:56 UTC by DisposableCrewmember42

## About the PR
This PR shuts the Oracle up, as requested by Game Directors [in Discord](https://discord.com/channels/968983104247185448/1283094866670129163/1283100648128254052).

## Why / Balance
The Oracle's barking does not fit the proposed lore and is deemed too obnoxious.

## Technical details
This PR introduces a new enum, OracleBarkType, with three variants:
- Timed: The current behavior
- NewDemand: Bark on NextItem call
- Never: Do not send barks.

It adds a new attribute, BarkType, to the OracleComponent, which is set to Never by default.

I introduced these variations since there was discussion of barking being added with different messages. This way, it could be reintroduced by simply changing the attribute override in the oracle prototype YAML.

## Media

https://github.com/user-attachments/assets/5ba7ab77-a93c-4e3a-b18c-636260bb97f5

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

- New attribute added to OracleComponent: BarkType

**Changelog**

:cl: DisposableCrewmember42
- tweak: Shut the oracle up. Scientists may now research in peace.

2024-09-11 17:13 UTC, TadJohnson00 reviewed
I support this change, all that's pending now is review from someone who does C#. Thanks for the PR 😎

2024-09-11 17:13 UTC, TadJohnson00 commented on Content.Server/Nyanotrasen/Research/Oracle/OracleBarkType.cs
<sub>I'm just a yamltainer but a newline at the end would be cool</sub>

2024-09-11 17:19 UTC, DisposableCrewmember42 commented
oh god i fucked up the rebase

2024-09-12 02:51 UTC, deltanedas requested changes

2024-09-12 02:51 UTC, deltanedas commented on Content.Server/Nyanotrasen/Research/Oracle/OracleBarkType.cs
> +public enum OracleBarkType {
this has no namespace + should just be in the components file + add `: byte`

2024-09-12 02:51 UTC, deltanedas commented on Content.Server/Nyanotrasen/Research/Oracle/OracleComponent.cs
> +    [DataField("barkType")]
remove ("barkType")

2024-09-12 12:58 UTC, deltanedas commented
move it into the file, not nested

2024-09-12 19:14 UTC, deltanedas approved these changes

2024-09-17 14:08 UTC, TadJohnson00 approved these changes
Dir. approval. yippee

2024-09-17 14:09 UTC, merged