port pitbulls from legacy
DeltaV-Station/Delta-v pull request #1835
Opened 2024-09-16 18:07 UTC by deltanedas

## About the PR
mostly the same as they were with some key changes:
- vent pitbulls have their own event instead of being tacked onto mouse migration
- if you fail to pet a pitbull it just retaliates instead of permanently making you KOS, meaning youd have to always kill the pitbull once someone failed to pet it. now they can run away and they will forget
- made walter the base for pitbull to reduce copy paste and removing 90% of duplicate components from walter in an upstream file

not added to cargo yet

## Why / Balance
poor old baby wouldnt hurt a fly
baby:

## Technical details
add `HostileOnInteractFail` that uses https://github.com/space-wizards/space-station-14/pull/32216

## Media
:trollface:

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
no

**Changelog**
:cl:
- add: Pitbulls are back, couriers beware of what comes from the vents....

2024-09-16 23:33 UTC, ghost requested changes
Looked at the current yaml, seems fine, but I noticed one thing. Also I can see TJ having opinions on this

2024-09-16 23:33 UTC, ghost commented on Resources/Prototypes/Nyanotrasen/Datasets/Names/pitbull.yml
> +  - Cuddles
Cuddles is in here twice, at line 16 and 25, is this intentional? Do we want to diversify the names of these?

2024-09-17 00:38 UTC, deltanedas commented on Resources/Prototypes/Nyanotrasen/Datasets/Names/pitbull.yml
> +  - Cuddles
im gonna sort it too

2024-09-17 07:19 UTC, ghost commented
pro

2024-09-17 07:21 UTC, ghost approved these changes

2024-09-17 07:21 UTC, ghost commented
Still needs Game Director and general maint approval

2024-09-17 13:23 UTC, deltanedas commented
and needs upstream pr :trollface:

2024-09-17 23:05 UTC, VileSloth commented
If these are going to be added, I suggest that they do not attack anyone for no reason, IE attacking a courier just because they are wearing courier clothes, as it perpetuates a stereotype that leads to animal abuse.

2024-09-18 09:39 UTC, TadJohnson00 commented
Hey, so, direction here.
We'd appreciate it if this wasn't brought back from Nyano. Sorry for the inconvenience

2024-09-18 10:27 UTC, deltanedas commented
couriers on top

2024-09-18 10:27 UTC, closed without merging