Remove nukies axe plating prying capabilities.
DeltaV-Station/Delta-v pull request #1844
Opened 2024-09-17 05:12 UTC by Radezolid

## About the PR

Removed the ability to pry plating as I think the intent behind https://github.com/DeltaV-Station/Delta-v/pull/1700 was to make only the atmos (and bridge) axe being able to pry plating.

## Why / Balance

Nukies are going back to the old meta of carrying the axe spacing every room they are in with it.

## Technical details

I inverted the inheritance so the nukie fire axe doesn't get the `Axing` tag.

## Media

Before

https://github.com/user-attachments/assets/b15ca132-4011-44a8-8e95-bd00f0479857

After

https://github.com/user-attachments/assets/e9d152a9-07fc-4fb2-ad41-cbfb7a76b3db

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

I hope none.

**Changelog**

:cl:
- fix: Nuclear operatives fire axe is no longer able to pry plating.

2024-09-17 05:29 UTC, Radezolid commented
Insight on why the YAML Linter test failed would be appreciated. The part it complains about was not modified

2024-09-17 05:45 UTC, deltanedas submitted a review, later dismissed
you are completely mangling upstream files without even putting comments

2024-09-17 09:36 UTC, ghost requested changes
1. Deltanedas was straight to the point about it, but yes. Worth it to comment things and document what you have changed so that if there's suddenly a merge to add functionality to fireaxes it doesn't explode in the upstream merge

2. The reason why the yaml linter is choking is because, *if I had to guess with my currently tired brain,* the fields for that aren't defined to go with the flaming fireaxe (the parents of that item are baseitem and base engi contra), and swapping the inheritance may not be this simple. It'd be easier to do this in a different way, but it might be more trouble than it's worth 🤷

2024-09-17 09:36 UTC, ghost commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
> +    sprite: Objects/Weapons/Melee/fireaxeflaming.rsi
Comment that you reversed the inheritance.

2024-09-17 09:36 UTC, ghost commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
> +    wideAnimationRotation: 90
Comment that you reversed the inheritance, should be something like "# DeltaV - reversed fireaxe prying capabilities" or it should point to the PR number

2024-09-17 09:36 UTC, ghost commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
> +  description: Truly, the weapon of a madman. Who would think to fight fire with an axe?
Same things as said above goes for this one, I think.

2024-09-17 13:35 UTC, TadJohnson00 commented
I'm gonna let Adei take the lead on trying to address the YAML side of all this. As for the Direction side, can't promise this is gonna sail, will get back to you on whether this'll go through or not.

2024-09-17 16:58 UTC, Radezolid commented
> 1. Deltanedas was straight to the point about it, but yes. Worth it to comment things and document what you have changed so that if there's suddenly a merge to add functionality to fireaxes it doesn't explode in the upstream merge
> 
>     2. The reason why the yaml linter is choking is because, _if I had to guess with my currently tired brain,_ the fields for that aren't defined to go with the flaming fireaxe (the parents of that item are baseitem and base engi contra), and swapping the inheritance may not be this simple. It'd be easier to do this in a different way, but it might be more trouble than it's worth 🤷

Thanks for the corrections, still learning this. If able what would be the different way? Make a new yml just for the nukie one?


> I'm gonna let Adei take the lead on trying to address the YAML side of all this. As for the Direction side, can't promise this is gonna sail, will get back to you on whether this'll go through or not.

Sure thing, I was about to make a issue about the axe, but I tried my hand at it.

2024-09-17 23:18 UTC, deltanedas commented
can you not just do `qualities: []` to disable it for fire axe

2024-09-17 23:31 UTC, Radezolid commented
> can you not just do `qualities: []` to disable it for fire axe

Tested it, worked perfectly, I should have done that. Thanks, as I said still learning this.

2024-09-18 02:04 UTC, ghost commented
> > can you not just do `qualities: []` to disable it for fire axe
> 
> Tested it, worked perfectly, I should have done that. Thanks, as I said still learning this.

Was gonna suggest making an abstract fire axe and then parenting the atmos and nukie fire axes to this, but I guess this works, so well done.

2024-09-18 02:05 UTC, ghost approved these changes

2024-09-18 02:06 UTC, ghost commented
Deltanedas, unrequest your change and merge it, it's one of the things where I can't

2024-09-18 08:57 UTC, merged