add mediborg to silicons department
DeltaV-Station/Delta-v pull request #1850
Opened 2024-09-17 18:13 UTC by deltanedas

## About the PR
title

## Why / Balance
borg is silicon
mediborg is silicon

no cl

2024-09-18 01:56 UTC, ghost commented
`The job MedicalBorg has more than 1 primary department!`

`Assert.That(primaries, Is.EqualTo(1))`
  `Expected: 1`
  `But was:  2`
  
  You should probably do this for any other borgs that have job prototypes / things in anticipation for AI (I say that because Secborg might have one.)

2024-09-18 04:03 UTC, MilonPL requested changes

2024-09-18 04:03 UTC, MilonPL commented on Resources/Prototypes/Roles/Jobs/departments.yml
You have to change silicon to not be a primary department for the tests to pass. Having no primary department (like captain does) is fine and shouldn't break anything.

2024-09-20 13:52 UTC, TadJohnson00 commented
@deltanedas thoughts on putting station AI under the command dept. as well?

2024-09-20 13:54 UTC, deltanedas commented
it makes sense playtime wise and i think its how a lot of ss13 servers do it too

2024-09-20 14:05 UTC, TadJohnson00 approved these changes
dir. approved or some shit

2024-09-20 14:17 UTC, merged