Einstein Engines Cybernetic Limbs
DeltaV-Station/Delta-v pull request #1857
Opened 2024-09-18 23:03 UTC by Aikakakah

## About the PR
Imported the cybernetic limbs from EE. 

## Why / Balance
I'm sure there's plenty of players who would appreciate finally being able to give their characters a robotic limb! 

## Technical details
Adjusted species files to increase marking limits, added both variations of the EE cybernetic limbs.

## Media
![image](https://github.com/user-attachments/assets/1de7d683-3979-4ebc-b37d-e3745b67beea)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: Aikakakah
- add: Added cybernetic limbs!

2024-09-19 05:01 UTC, MilonPL requested changes

2024-09-19 05:01 UTC, MilonPL commented on Resources/Prototypes/Einstein-Engines/Entities/Mobs/Customization/cyberlimbs/bishop.yml
Dwarf, HumanoidFoxes unnecessary all throughout the file.

2024-09-19 05:01 UTC, MilonPL commented on Resources/Prototypes/Einstein-Engines/Entities/Mobs/Customization/cyberlimbs/hesphiastos.yml
Dwarf, HumanoidFoxes unnecessary all throughout the file.

2024-09-19 09:16 UTC, ghost reviewed
Milon, god's strongest YML warrior 😸 

Seems pretty normal as YAML, didn't catch anything wrong. I would approve, but I'm gonna pull Game Directors so they look at this because it incorporates corporations from 13 into the game via the Names :tm: and also to, if nothing else, have a third pair of eyes on it. I hate to be that fuckin' nerd but I gotta be.

2024-09-20 14:01 UTC, TadJohnson00 commented
Mixed on this, will get back to you shortly.

2024-09-21 03:28 UTC, Astrumif-y commented
Definitely a must-have for delta , ive always wanted to give a character or two a robot limb after an important moment that would justify such a thing

2024-09-21 05:56 UTC, TadJohnson00 commented
Alright, yep, I'll be fine with approving this if you remove the company names from the locale and replace it with numbers (right robotic arm 1, etc.)

2024-09-22 05:37 UTC, ghost approved these changes
Looks fine with the generic-ization of these, now.

2024-09-22 05:45 UTC, MilonPL approved these changes

2024-09-22 06:04 UTC, merged