I am SO fucking smart
DeltaV-Station/Delta-v pull request #1866
Opened 2024-09-19 15:38 UTC by MilonPL

## About the PR

fixes https://github.com/DeltaV-Station/Delta-v/issues/1865

## Why / Balance

deltanedas trolled it with the last upstream merge, condemning billions 

## Technical details

basically same shit as before but better, uses a query instead of importing the entitymanager or whatever they were cooking

## Breaking changes

**Changelog**
:cl:
- fix: Fixed barefoot felinids making footsteps sounds.

2024-09-19 15:39 UTC, MilonPL commented
oops forgot to change the title from the commit message :blunt:

2024-09-19 20:28 UTC, deltanedas requested changes

2024-09-19 20:28 UTC, deltanedas commented on Content.Shared/Movement/Systems/SharedMoverController.cs
> +        if (NoShoesSilentQuery.TryComp(uid, out var _) &
hascomp

2024-09-20 00:50 UTC, MilonPL commented on Content.Shared/Movement/Systems/SharedMoverController.cs
> +        if (NoShoesSilentQuery.TryComp(uid, out var _) &
fuck you're right

2024-09-20 03:38 UTC, deltanedas approved these changes

2024-09-20 03:38 UTC, merged