make cats attack mouse toy
DeltaV-Station/Delta-v pull request #1877
Opened 2024-09-21 01:59 UTC by deltanedas

## About the PR
added cat faction to all cats so they attack mice and mouse toy
added mouse faction to mouse toy

## Why / Balance
piep

## Media
all cats attack the toy...
bingus doesnt attack since bingus isnt actually a cat
![02:55:32](https://github.com/user-attachments/assets/50f58672-1edd-4a26-a8b3-86a84ef1b242)

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- tweak: Cats will now play with mouse toys.

2024-09-21 03:21 UTC, TadJohnson00 commented
Does this fuck with medhuds? Do mouse toys actually appear alive?

2024-09-22 23:37 UTC, Bonktrauma commented
Bingus is a sphynx, what are you on about

2024-09-23 02:15 UTC, deltanedas commented
bingus is a simplemob

2024-09-23 19:21 UTC, MilonPL approved these changes
small change, everything looks good

2024-09-23 19:26 UTC, MilonPL requested changes
minor oversight

2024-09-23 19:26 UTC, MilonPL commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +    damageContainer: Inorganic # not actually destructible, just lets it be attacked
oh fuck the diagnostic hud shows health bars/icons for inorganic and silicon containers, you'd want to use `StructuralInorganic` instead

2024-09-24 03:29 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Fun/toys.yml
> +    damageContainer: Inorganic # not actually destructible, just lets it be attacked
![04:28:55](https://github.com/user-attachments/assets/f9c8ab37-9dde-4a5d-b555-ec75973b746b)
yes its fixed now

2024-09-24 07:11 UTC, MilonPL approved these changes

2024-09-24 07:15 UTC, merged