make teslas great again
DeltaV-Station/Delta-v pull request #1916
Opened 2024-09-26 13:44 UTC by MilonPL

## About the PR

Added a passive drain to teslas (3 per second, might need to be adjusted). Once it reaches 100 power, a bunch of lightning balls spawn and power goes back to 0. If it reaches -100, the tesla despawns.
Also replaced the ChasingWalk with RandomWalk so it has randomized pathfinding like the singulo.
Uncommented the spawns, cargo can order it too.

## Why / Balance

There was a bunch of discussion about it before, I think it ended up with "wyci" so I coded it. Yippee. 
The main point against having teslas was that it was a guaranteed round end, so well, it's not a guaranteed round end anymore. Also you need the PA to be constantly on, like with the singulo, or it's just going to die. Can't wait for engi to fuck up.

## Technical details

Uncomments spawns, minor changes to the yaml file, I tried to avoid touching upstream code so this only adds two datafields to the component (which could be done with a separate component too but that feels like just bloat at this point), the actual updates are being handled by a separate system using the public AdjustEnergy() method. Had to add access to the component to modify the DataFields, again, could be all done in a separate TeslaPassiveEnergyDrainComponent instead or whatever.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Re-added teslas!
- tweak: Tesla now has a random pathfinding and a passive energy drain. Don't forget to leave the PA on!

2024-09-26 13:57 UTC, Avalon-Proto commented
THE GRAND RETURN OF LORD TESLOTH!

2024-09-26 16:33 UTC, dotCatshark commented
consider changing it so that the tesla only loses energy when it eats something. i think making it require the pa to run removes some of the uniqueness of it. you might be able to cannibalize the code for that from the singulo code (singulo should gain energy as it consumes stuff. if it  doesnt then that particular mechanic from 13 wasnt ported... for some reason)

2024-09-26 16:39 UTC, MilonPL commented
> consider changing it so that the tesla only loses energy when it eats something. i think making it require the pa to run removes some of the uniqueness of it. you might be able to cannibalize the code for that from the singulo code (singulo should gain energy as it consumes stuff. if it doesnt then that particular mechanic from 13 wasnt ported... for some reason)

All you'd have to do is flip `ConsumeStuffEnergy` from 2 to -2 technically. But then the tesla is kinda guaranteed to fade away pretty soon.

2024-09-26 16:59 UTC, deltanedas commented
if it lost energy by consuming i think it would be fine to keep the targeted walk since it would go after power infrastructure etc then die

2024-10-05 19:00 UTC, MilonPL commented
@deltanedas this is ready for review fyi, game directors fake anyways and I haven't heard any other ideas regarding how to implement this

2024-10-27 20:45 UTC, deltanedas requested changes
i forgot to request changes ages ago

2024-10-27 20:45 UTC, deltanedas commented on Content.Server/DeltaV/Tesla/TeslaEnergyBallSystem.PassiveDrain.cs
> +            component.NextUpdateTime = curTime + TimeSpan.FromSeconds(1);
have the timespan be a system constant or a component field

2024-10-27 20:45 UTC, deltanedas commented on Content.Server/Tesla/Components/TeslaEnergyBallComponent.cs
> +using Robust.Shared.Timing; // DeltaV
put it in the other file

2024-10-27 20:45 UTC, deltanedas commented on Content.Server/Tesla/Components/TeslaEnergyBallComponent.cs
> +    public TimeSpan NextUpdateTime = default!;
TimeSpan.Zero

2024-10-27 20:45 UTC, deltanedas commented on Content.Server/Tesla/Components/TeslaEnergyBallComponent.cs
> +    [DataField]
use TimeOffsetSerializer and use AutoPausedField+AutoGenerateComponentPause

2024-10-27 20:47 UTC, MilonPL commented
> i forgot to request changes ages ago

no fucking way i though you just hated it

2024-10-27 20:49 UTC, deltanedas commented
forgot to click a button highly real

2024-10-27 20:53 UTC, MilonPL commented on Content.Server/Tesla/Components/TeslaEnergyBallComponent.cs
> +using Robust.Shared.Timing; // DeltaV
??? 
needed for `IGameTiming.CurTime` in the summary

2024-10-27 23:05 UTC, deltanedas commented on Content.Server/Tesla/Components/TeslaEnergyBallComponent.cs
> +using Robust.Shared.Timing; // DeltaV
real

2024-10-27 23:05 UTC, deltanedas approved these changes

2024-10-27 23:05 UTC, merged