untroll glimmermobspawnrule
DeltaV-Station/Delta-v pull request #1980
Opened 2024-10-07 14:10 UTC by MilonPL

## About the PR

changes it so that GlimmerMobSpawn will no longer try spawning glimmer creatures outside the station

## Why / Balance

annoying AS FUCK

## Technical details

blah code is clear enough but it does the same thing as the RandomSpawnRule basically

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: Glimmer mobs will no longer spawn on CentCom or the evac shuttle.

2024-10-07 20:36 UTC, deltanedas requested changes

2024-10-07 20:36 UTC, deltanedas commented on Content.Server/DeltaV/StationEvents/Events/GlimmerMobSpawnRule.cs
> +                if (CompOrNull<StationMemberComponent>(xform.GridUid)?.Station == station)
GetOwningStation

2024-10-07 20:36 UTC, deltanedas commented on Content.Server/DeltaV/StationEvents/Events/GlimmerMobSpawnRule.cs
> +        if (TryGetRandomStation(out var station))
this should only be called once or it could split across stations if there are multiple

2024-10-07 23:34 UTC, MilonPL commented on Content.Server/DeltaV/StationEvents/Events/GlimmerMobSpawnRule.cs
> +                if (CompOrNull<StationMemberComponent>(xform.GridUid)?.Station == station)
ok real copy and paste ops failed

2024-10-14 16:01 UTC, MilonPL commented
test fail fake but there's no way we got rate limited

2024-10-14 16:07 UTC, deltanedas commented
as in pass station as argument to GetCoords

2024-10-14 16:32 UTC, MilonPL commented
> as in pass station as argument to GetCoords

i don't think it needs to now, since it just checks whether the owning station is valid?

2024-10-14 16:40 UTC, deltanedas commented
wouldnt handle multistation properly, just have the event pick 1 station at the start and use that for all rolls so its futureproof

2024-10-14 16:46 UTC, MilonPL commented
ok got it i think

2024-10-14 23:43 UTC, deltanedas approved these changes

2024-10-14 23:43 UTC, merged