Pullreq
DeltaV-Station/Delta-v pull request #2003
Opened 2024-10-13 19:28 UTC by sheepism1

## About the PR

Added a blender, a bruise-o-mat instead of an emagged booze-o-mat, binary keys for Listening Post ops, more stamps in the forgery locker, and a kitty!
## Why / Balance

Binary keys to spy on too, blenders so they can make meds (they could just eat it before) and additional stamps to ensure there's plenty of tomfoolery that you can get up to impersonating the Psychologist, Chief Justice, Lawyer, or Greytide.
## Technical details

Added binary key to interceptor headsets (NOT THE NUKIE OR TRAITOR ONES, ONLY THE LP ONES)
Added a kitty spawner (generic)
Added a bruise-o-mat
Blender for.. I dunno, more options to do in Syndicate Botany. LARP as a synthesis specialist!
Stamps are put in the locker, not prototyped cause fun fact it's just a renamed locker
## Media

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

If any of you can delete "QOLInterceptPost.yml" I will be grateful (unfinished ver of the post!)
**Changelog**

:cl:
Avalon
- add: Added QOL items, additional stamps, and more to the Listening Post! Syndicate spies rejoice!
- tweak: Binary keys are now on Listening Post headsets by default. Not even the Borgs are safe from snooping!
![QOLed_on_godo](https://github.com/user-attachments/assets/f75b101c-6635-4281-9245-5eff28da9b87)

2024-10-13 19:30 UTC, sheepism1 commented
I forgot a good name, check my next pr instead

2024-10-13 19:32 UTC, sheepism1 commented
#2004

2024-10-13 19:33 UTC, sheepism1 commented
I'm back!

2024-10-13 23:42 UTC, sheepism1 commented
passes checks on my repo

2024-10-13 23:44 UTC, sheepism1 commented
I dunno if I ran  `fixgridatmos` :trollface:

2024-10-14 01:35 UTC, sheepism1 commented on Resources/Maps/Shuttles/DeltaV/listening_post.yml
map file

2024-10-14 02:23 UTC, sheepism1 commented
works in game 👍

2024-10-14 02:39 UTC, sheepism1 commented
cat intentionally kills the mouse-toy when it spawns, but I doubt that'll be an issue tho

2024-10-14 19:33 UTC, sheepism1 commented
I hope #2009 works w/ this, (it should, its gonna be fun to have the Smoke and Mirrors NEARLY OVERHAUL of the LP)

2024-10-16 17:20 UTC, perryprog commented
This might be off limits but... I have had times as LPO where I really wanted a CentComm stamp. That might be asking for too much, though. :)

2024-10-16 21:34 UTC, Radezolid commented
> This might be off limits but... I have had times as LPO where I really wanted a CentComm stamp. That might be asking for too much, though. :)

That is a big no, CC stamp is meant to be a certified document from admins, LPOs wouldn't be able to get their hands on it. Best chance you get is CC responding to a fax of yours and forgetting to make it non-editable.

2024-11-02 14:28 UTC, deltanedas requested changes
the stamps should just be made into a prototype so adding new stamps doesnt require mapping

2024-11-02 14:28 UTC, deltanedas commented on Resources/Maps/Shuttles/DeltaV/listening_post.yml
> +      parent: invalid
remove all invalids

2024-11-15 06:04 UTC, TadJohnson00 commented
@sheepism1 I see that UnknownGhost has taken up this PR in #2155. Do you want this PR closed?

2024-11-25 22:22 UTC, sheepism1 commented
feel free to close - continuation is approved

2024-11-29 20:03 UTC, deltanedas commented
#2155

2024-11-29 20:03 UTC, closed without merging