Elegance Station
DeltaV-Station/Delta-v pull request #2020
Opened 2024-10-17 03:15 UTC by IAmNotGray

## About the PR
Elegance, or "Lady Elegance" in full, is a service-oriented station somewhere in between the size of Submarine and Hammurabi with a minimum player count of 40.
In addition to this, Elegance features its own unique evac shuttle, dubbed the "NTES Transport."
(Original got closed because of branch stuff.)
## Why / Balance
I like the idea of a service-oriented station, and I haven't seen anyone else attempt to do anything similar to this.
_I also couldn't help myself as a service main..._
## Media
![Elegance-0](https://github.com/user-attachments/assets/565700b6-9f68-4e60-8e15-ec2737994533)
Elegance
![image](https://github.com/user-attachments/assets/14b24a78-ed20-43cf-989c-8e62833686f8)
NTES Transport

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl: This_Is_Gray
- add: Elegance, a service station, is now recieving crew members!
- add: The new NTES Transport is here to take you to Central Command. _In style!_

2024-10-17 11:33 UTC, deltanedas commented
some things i noticed from looking at the render

engi
- teg has a bunch of manual valves you would only use to sabotage it, particularly the cold loop
- burn chamber doors dont use logic gates, they will get stuck open at some point by a clueless atmos or ce guaranteed, make them either single doors or use logic gates to have them bolt when either door is open (just linking the doors directly will break)

botany:
- no botanist lockers
- no biogenerator
- no chemmaster

freezer:
- map render may be trolling but very suspicious that theres just an air vent with no passive vent for the freezer

epi:
- there is next to no gas control for the artifact chambers, just space blast doors and thats it

2024-10-17 12:01 UTC, Avalon-Proto commented
Personally my biggest gripe is the fact the sec hardsuits are in the part of the armory that's most likely to get spaced. So the sec armored hardsuits are likely to be lost the moment nukies hit

2024-10-17 16:31 UTC, FieldCommand commented
Its an interesting station, but my gripe is the maintenance on this station. They are huge, mostly double wide corridors or sometimes triple or more. And they are very uniform/monotone, with hardly any clutter in them, few to no lockers/wall lockers, or interesting sightings and ester eggs.

2024-10-17 17:06 UTC, IAmNotGray commented
> some things i noticed from looking at the render
> 
> engi
> 
> * teg has a bunch of manual valves you would only use to sabotage it, particularly the cold loop
> * burn chamber doors dont use logic gates, they will get stuck open at some point by a clueless atmos or ce guaranteed, make them either single doors or use logic gates to have them bolt when either door is open (just linking the doors directly will break)
> 
> botany:
> 
> * no botanist lockers
> * no biogenerator
> * no chemmaster
> 
> freezer:
> 
> * map render may be trolling but very suspicious that theres just an air vent with no passive vent for the freezer
> 
> epi:
> 
> * there is next to no gas control for the artifact chambers, just space blast doors and thats it
On the burn chamber doors, I can go ahead and fix that very easily.
And about the freezer, I didn't think it'd matter if there was a passive vent or a normal air vent. I've gone ahead and changed that.

As for Epistemics, I've tried to fit in a way to add gas to the chambers, there's just not enough. If you saw the steel, though, that's for ol' John Research Assistant to set it up!

Gone ahead and touched up everything else you've adressed as well.

2024-10-17 17:22 UTC, IAmNotGray commented
> Personally my biggest gripe is the fact the sec hardsuits are in the part of the armory that's most likely to get spaced. So the sec armored hardsuits are likely to be lost the moment nukies hit

I've moved some things around.

2024-10-17 17:29 UTC, IAmNotGray commented
> Its an interesting station, but my gripe is the maintenance on this station. They are huge, mostly double wide corridors or sometimes triple or more. And they are very uniform/monotone, with hardly any clutter in them, few to no lockers/wall lockers, or interesting sightings and ester eggs.

I made the decision to make the maintenance tunnels this way pretty early on, so I don't remember WHY I did it exactly, but I'm pretty sure I've been told by several people that big maints are pretty neat?-

2024-10-17 18:35 UTC, FieldCommand commented
> I made the decision to make the maintenance tunnels this way pretty early on, so I don't remember WHY I did it exactly, but I'm pretty sure I've been told by several people that big maints are pretty neat. -

I don't mind big maintenance, but this is a bit excessive. All this space, and there is barely anything going on here. You have a disposal room, you should move the recycler out of the corner. and you have a secret room, the syndicate baner can be seen from outside and should be replaced with a free-standing one. And for how big this is, its very monotonous. There are some lockers and some canisters, but not all of them are at the access points. When an emergency arises, I would have to walk through all this to find an N2 or O2 locker. and I don't see any wall lockers at all. And this should also be partitioned into sections with firelocks, it has a lot of volume, and spacing would be a disaster here and take for ever to fill again.

![Capture10](https://github.com/user-attachments/assets/59e75a6a-cbee-4852-85cf-10c73176a243)

2024-10-17 18:37 UTC, IAmNotGray commented
> > I made the decision to make the maintenance tunnels this way pretty early on, so I don't remember WHY I did it exactly, but I'm pretty sure I've been told by several people that big maints are pretty neat. -
> 
> I don't mind big maintenance, but this is a bit excessive. All this space, and there is barely anything going on here. You have a disposal room, you should move the recycler out of the corner. and you have a secret room, the syndicate baner can be seen from outside and should be replaced with a free-standing one. And for how big this is, its very monotonous. There are some lockers and some canisters, but not all of them are at the access points. When an emergency arises, I would have to walk through all this to find an N2 or O2 locker. and I don't see any wall lockers at all. And this should also be partitioned into sections with firelocks, it has a lot of volume, and spacing would be a disaster here and take for ever to fill again.
> 
> ![Capture10](https://private-user-images.githubusercontent.com/159087063/377587915-59e75a6a-cbee-4852-85cf-10c73176a243.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxOTA0NDcsIm5iZiI6MTcyOTE5MDE0NywicGF0aCI6Ii8xNTkwODcwNjMvMzc3NTg3OTE1LTU5ZTc1YTZhLWNiZWUtNDg1Mi04NWNmLTEwYzczMTc2YTI0My5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxODM1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjMzNTZiYzAyNGVlY2UxYjAzN2M4ZTQwYTQ5MDU0OTgxYWM0ZTRkMzdjOTNiYjJlNWQ2NWFhZWE1MzJhMzM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-2o1O3Scnue08K0Meebbc1X0fCSDN63aqPbxTX3OSgA)

Oh, yeah, I see exactly what you mean here. Yikes, I might have forgotten about that area. I'll be spending a lot of time touching up maints...

2024-10-19 04:05 UTC, IAmNotGray commented
I've ended up addressing the issues brought up with the station with the update here. Mostly the maintenance tunnels, but I've also ended up moving around the security suits in the armory, among other small things.

2024-11-10 01:52 UTC, IAmNotGray commented
I completely overhauled Epistemics. A big issue with this station was the amount of unused space and hopefully I fixed that for the most part.

2024-11-23 05:56 UTC, IAmNotGray commented
Okay. That's hopefully the last update I'm doing until Elegance gets reviewed. Thanks to everyone for all the feedback!

2024-11-23 12:50 UTC, Kr8art commented
Love this! The shuttle looks great too!

2025-01-10 22:13 UTC, IamVelcroboy requested changes

2025-01-10 22:13 UTC, IamVelcroboy commented on Content.IntegrationTests/Tests/PostMapInitTest.cs
>              "Chibi" // DeltaV
need a comma

2025-02-01 01:54 UTC, IamVelcroboy commented
![image](https://github.com/user-attachments/assets/c3541d06-6d9f-40b7-92ad-9ef901fc59d7)

2025-02-01 05:04 UTC, IAmNotGray commented
> ![image](https://private-user-images.githubusercontent.com/107660393/408767249-c3541d06-6d9f-40b7-92ad-9ef901fc59d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgzODY0NDgsIm5iZiI6MTczODM4NjE0OCwicGF0aCI6Ii8xMDc2NjAzOTMvNDA4NzY3MjQ5LWMzNTQxZDA2LTZkOWYtNDBiNy05MmFkLTllZjkwMWZjNTlkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIwMVQwNTAyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjIwODYwMDk1ZTAzNDQyOTcyNTkyZTY0MjBiZDNhYzIyNjQzYzE1NjZlMjNlMjk0OWU2YTcxZjk1MTQwZmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yMgasV0FBikBOwz6qDjc_Nn0XIwL5b6g7R0NipPChEQ)

Oh dear god.

2025-02-01 20:39 UTC, IAmNotGray commented
Oh, I blundered the commit name. (3/3)*
:blunt:

2025-02-02 03:08 UTC, IAmNotGray commented
Gamers, it's ready.

2025-02-02 03:28 UTC, IamVelcroboy commented on Resources/Maps/elegance.yml
> +    - type: GroupExamine
Dang, I did a thing. These lines need to be removed

2025-02-02 03:28 UTC, IamVelcroboy commented on Resources/Maps/elegance.yml
>  - proto: AlwaysPoweredLightColoredFrostyBlue
Missed this always powered

2025-02-02 03:28 UTC, IamVelcroboy commented on Resources/Maps/elegance.yml
>  - proto: AlwaysPoweredSmallLightMaintenance
and this one

2025-02-02 03:28 UTC, IamVelcroboy commented on Resources/Maps/elegance.yml
> +    - type: GroupExamine
lines 85874-85889

2025-02-02 03:34 UTC, IamVelcroboy approved these changes

2025-02-02 04:03 UTC, merged