Syndie Raid Suit Cold Protection
DeltaV-Station/Delta-v pull request #2025
Opened 2024-10-20 04:47 UTC by ThataKat

## About the PR
Gave the Syndie Raid suit insulation against the cold. 

## Why / Balance
So we can actually use the atmospheric suit on the one station with an atmosphere (glacier)

## Technical details
Modified armor.yml to give the suit the same cold insulation as a winter coat (still not as a good as a hardsuit). Didn't give it any heat insulation.

## Media
![image](https://github.com/user-attachments/assets/270c0787-742c-480e-9142-2a4509ea8f53)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
None

**Changelog**

2024-11-03 09:34 UTC, deltanedas requested changes

2024-11-03 09:34 UTC, deltanedas commented on Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml
> +  - type: TemperatureProtection
add deltav comment

2024-11-03 09:34 UTC, deltanedas commented on Resources/Prototypes/Entities/Clothing/OuterClothing/armor.yml
> +    heatingCoefficient: 1.0
1 is the default you can remove this

2024-12-10 07:52 UTC, MilonPL commented
Since the last commit was almost 2 months ago, I will be closing this. Feel free to open up a new PR if you ever come back to this.

2024-12-10 07:52 UTC, closed without merging