Adds e-shotgun
DeltaV-Station/Delta-v pull request #2069
Opened 2024-10-28 22:18 UTC by Stop-Signs

## About the PR
Energy shotgun has been nerfed significantly since its release, re-adds it to the HoS locker at round start.

## Why / Balance
Nukie win-rate has been through the roof recently, and HoS headache rate is at an all time high. Since it was added to upstream 3 months ago it has been nerfed significantly.

## Technical details
N/A

## Media
N/A

## Requirements

- [x ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

2024-10-28 22:21 UTC, Radezolid commented
Without auto recharge i doubt it will make a difference, also while at it it might be better to give it to the warden since HOS already has a gun.

2024-10-28 22:37 UTC, Stop-Signs commented
> Without auto recharge i doubt it will make a difference, also while at it it might be better to give it to the warden since HOS already has a gun.

how would we feel about moving the x-01 to warden locker and giving HoS the shotgun

looking at you @MilonPL

2024-10-28 23:35 UTC, Radezolid commented
> > Without auto recharge i doubt it will make a difference, also while at it it might be better to give it to the warden since HOS already has a gun.
> 
> how would we feel about moving the x-01 to warden locker and giving HoS the shotgun
> 
> looking at you @MilonPL

Shotgun feels more balanced for a warden than the X-01 IMO.

2024-10-29 17:25 UTC, Stop-Signs commented
After some extensive testing, I've compared the eshotgun to all of the main guns that security typically have access to, along with the weapons that sec can currently research. all of these tests were shooting the respective gun until it was completely empty.

Kammerer
![image](https://github.com/user-attachments/assets/a8582018-892a-4652-a4a1-698f7daebc8c)

Eshotgun
![image](https://github.com/user-attachments/assets/f869ad34-13e1-4956-a49c-a0212df3519f)

MK58
![image](https://github.com/user-attachments/assets/24244e87-d6c6-4fa7-8f5c-93c90b78cbbf)

Drozd
![image](https://github.com/user-attachments/assets/3ad7a4e9-1695-4466-b0c3-5df24faf942f)

Universal
![image](https://github.com/user-attachments/assets/8fac57b8-ba83-47c2-9b1f-573031074484)

IK-60
![image](https://github.com/user-attachments/assets/55443812-fdfe-4dfa-bc37-43fc648b17c2)

Laser Cannon
![image](https://github.com/user-attachments/assets/38b8666d-09b5-492a-9665-a8787584ce26)

RPG
![image](https://github.com/user-attachments/assets/bf2e149d-e901-4d16-8c86-affd83f79d68)


I believe the fact that you need a powered recharger to reload the e-shotgun, keeps it balanced. A kammerer which can easily be reloaded does more damage than the e-shotgun, this alone shows that there shouldn't be any major balance issues.

2024-10-29 17:29 UTC, Radezolid commented
> I believe the fact that you need a powered recharger to reload the e-shotgun, keeps it balanced. A kammerer which can easily be reloaded does more damage than the e-shotgun, this alone shows that there shouldn't be any major balance issues.

The whole point of the shotgun is that it SHOULD be stronger than a kammerer because if not why take the worse gun with you?.

2024-10-29 17:55 UTC, MilonPL commented
> After some extensive testing, I've compared the eshotgun to all of the main guns that security typically have access to, along with the weapons that sec can currently research. all of these tests were shooting the respective gun until it was completely empty, and every shot hit the respective targets.

These test are kind of inadequate because real people don't stand still during nuke ops. The benefit of e-shotgun over other energy based weapons is that you're able to hit at least *some* of your shots. That being said, I think discussing lasers game balance is a bit silly when an antag can just spend 12 TC to decide they don't want to deal with lasers.

2024-10-29 21:47 UTC, Stop-Signs commented
> These test are kind of inadequate because real people don't stand still during nuke ops. The benefit of e-shotgun over other energy based weapons is that you're able to hit at least _some_ of your shots. That being said, I think discussing lasers game balance is a bit silly when an antag can just spend 12 TC to decide they don't want to deal with lasers.

the testing was more to show that even at its max potential, the energy shotgun isn't any more powerful than the current options for sec. Lasers are somewhat of a beast to balance, as its almost the only thing sec get out of research, and they all do the same type of damage. Thankfully i am not here to balance lasers ;).

2024-10-29 23:04 UTC, deltanedas commented
the projectile needs to be changed to pass through windows like regular lasers do, otherwise its just a hard to recharge enforcer (which can use beanbags for stunmeta)

2024-10-29 23:06 UTC, MilonPL requested changes
the laser bullets are broken and won't go through windows or hit holocarps, needs to have the `Opaque` mask
https://github.com/DeltaV-Station/Delta-v/blob/af2746cd30774f838eea31bbc48bac32d1e3d8af/Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml#L1032-L1034

2024-10-31 21:38 UTC, MilonPL requested changes

2024-10-31 21:38 UTC, MilonPL commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> -        - BulletImpassable
comment these out rather than removing them

2024-10-31 22:16 UTC, MilonPL approved these changes

2024-11-01 00:03 UTC, therealDLondon reviewed
I believe at this time we will not be adding the energy shotgun in its current state

2024-11-01 00:03 UTC, closed without merging

2024-11-04 06:31 UTC, therealDLondon commented
An addendum to the above:
In its current state, the E-Shotgun is too powerful for being a free round-start weapon, from what I have observed on servers with it enabled and my own tests, being able to 2-Shot an unarmored target from almost 5 tiles away is far too strong. It feeds into the idea of the HOS Being "Just a Secoff but better" which I do not believe fits the vision of security on DeltaV. The X01 is still a good weapon, and the HOS still gets free pickings of the armoury should they need a bigger gun.

2024-11-04 18:27 UTC, Avalon-Proto commented
While fair on the whole 2 shots from 5 tiles. Can't *most* shotguns do that to unarmored targets?