Reverted "Block emotes for sleeping" (upstream PR #32779)
DeltaV-Station/Delta-v pull request #2084
Opened 2024-11-01 12:11 UTC by Radezolid

## About the PR
Reverted "Block emotes for sleeping" per asking of [WYCI Suggestion](https://discord.com/channels/968983104247185448/1301835443909955584/1301835443909955584).

## Why / Balance
The emote system apparently was being abused in LRP when you got slept, as a MRP server we should have less problems with it while it helps with RP of narcoleptic people.

## Technical details
Commented out the PRs added lines out of `SleepingSystem.cs`.

## Media

https://github.com/user-attachments/assets/15e5cd77-8cfd-4bdf-9f08-bdd927a252fb

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: You can use emotes while sleeping to enhance narcoleptic RP.

2024-11-01 22:05 UTC, Lyndomen commented
I have never seen this be overly abused here; I wholeheartedly support this as someone who was very confused why I couldn't @snore.

2024-11-03 06:59 UTC, deltanedas requested changes

2024-11-03 06:59 UTC, deltanedas commented on Content.Shared/Bed/Sleep/SleepingSystem.cs
> +        //SubscribeLocalEvent<SleepingComponent, EmoteAttemptEvent>(OnEmoteAttempt); # DeltaV - Reverted "Block emotes for sleeping" (upstream PR #32779)
just make the pr this line to keep conflicts in the future completely minimal

2024-11-03 15:33 UTC, deltanedas approved these changes

2024-11-03 15:33 UTC, merged