Added smiley face to the medibot.
DeltaV-Station/Delta-v pull request #2087
Opened 2024-11-01 15:25 UTC by Radezolid

## About the PR
:)
Requested by [WYCI Suggestion](https://discord.com/channels/968983104247185448/1291013833229467749/1291013833229467749).

## Why / Balance
It looks friendlier and people seem to like the idea of a smiley medibot.

## Technical details

None.

## Media

![image](https://github.com/user-attachments/assets/18a6ca1a-619f-4d09-8c6a-2cda77fdc7e2)
![image](https://github.com/user-attachments/assets/70e5b707-118a-4c52-97d9-0f0c778426ab)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None.

**Changelog**

:cl:
- tweak: Medibots now smile!

2024-11-01 19:46 UTC, deltanedas commented
put it in deltav folder and add `sprite: DeltaV/Mobs/Silicon/Bots/medibot.rsi` to the medibot prototype with a comment

2024-11-03 07:03 UTC, deltanedas requested changes

2024-11-03 07:03 UTC, deltanedas commented on Resources/Textures/Mobs/Silicon/Bots/medibot.rsi/medibot.png
revert changes to the upstream texture now :trollface:

2024-11-03 17:26 UTC, Radezolid commented on Resources/Textures/Mobs/Silicon/Bots/medibot.rsi/medibot.png
I just removed it from the changes before this comment, i think it shouldn't affect it

2024-11-03 17:40 UTC, deltanedas commented on Resources/Textures/Mobs/Silicon/Bots/medibot.rsi/medibot.png
youre right its fixed now, github was doing a funny and showed both of them

2024-11-03 17:40 UTC, deltanedas approved these changes

2024-11-03 17:40 UTC, merged