Arsenal tech overhaul
DeltaV-Station/Delta-v pull request #2104
Opened 2024-11-03 20:45 UTC by Stop-Signs

## About the PR
Merges a some of the redundant techs, reduces the amount of content locked behind getting t3 arsenal. adjusts some pricing and moves the incendiary ammo and uranium ammo techs to tier 2. 

To Do: create a new t3 that is essentially a security kanabou

## Why / Balance
The 2 laser cannons being single item techs really wasnt doing sec any favors, neither was having the pdw and ik60 cost 20k combined. merging them with a slight price increase should overall be better for the game. moving the advanced munitions to t2 is kind of just where i thought they fit better, they are t1's that both cost a large amount of money, and they aren't exactly basic things for sec. Svallins being moved to t2 shouldn't cause many issues as the gun sucks and sec can just confiscate them(if needed I can move the recipe location, remove the tech alltogether, or move it back to t3) Basic shuttle armament is now a t1, but you have to get explosive tech and salv weaponry first. advanced shuttle armament is now a t2. hopefully with events involving shuttles coming soon, this will allow sec to be able to have those oh so fun shuttle battles. Advanced laser pistol is remaining a t3 for obvious reasons.

## Technical details
Comments were left on everything (i hope) still working on that new t3, will update when I do.

## Media

None yet!
## Requirements

- [x ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
We shall see :3

**Changelog**

2024-11-04 01:33 UTC, Stop-Signs commented
why did it request velcro?? no offense

2024-11-04 01:39 UTC, Stop-Signs commented
i have a feeling that these errors are not fake :3

2024-11-04 23:48 UTC, IamVelcroboy commented on Resources/Prototypes/Recipes/Lathes/security.yml
> +    - type: latheRecipe
Indented too far

2024-11-05 00:55 UTC, IamVelcroboy commented on Resources/Prototypes/Research/arsenal.yml
> +  - type: technology
Another over-indent here

2024-11-05 00:57 UTC, IamVelcroboy commented on Resources/Prototypes/Research/arsenal.yml
> +
Only leave 1 extra line at the end of the file

2024-11-05 01:01 UTC, IamVelcroboy commented on Resources/Prototypes/Recipes/Lathes/security.yml
> +
remove a line here

2024-11-05 01:02 UTC, IamVelcroboy commented on Resources/Prototypes/Research/arsenal.yml
> +
remove a line here

2024-11-05 01:13 UTC, MilonPL commented
@IamVelcroboy for the love of all that is holy why did you submit this as 5 individual reviews

2024-11-05 02:35 UTC, Stop-Signs commented
I HOPE that fixed it, we shall see

2024-11-05 03:21 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Research/arsenal.yml
> +    sprite: Objects/Weapons/Melee/Advanced trunch
If you want the truncheon icon this should be the path.
`Resources\Textures\Objects\Weapons\Melee\truncheon.rsi`

2024-11-05 03:53 UTC, Stop-Signs commented on Resources/Prototypes/DeltaV/Research/arsenal.yml
> +    sprite: Objects/Weapons/Melee/Advanced trunch
i made my own sprites, but didnt label the file as RSI. is that an issue?

2024-11-05 05:26 UTC, IamVelcroboy commented
> @IamVelcroboy for the love of all that is holy why did you submit this as 5 individual reviews

🤷‍♂️ I was on my phone, looking through the file changes

2024-11-05 13:07 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Research/arsenal.yml
> +    sprite: Objects/Weapons/Melee/Advanced trunch
I mean, it's literally why the YAML linter is dying.
` [ERRO] go.comp.sprite: Unable to load RSI '/Textures/Objects/Weapons/Melee/Advanced trunch'.`

2024-11-05 16:36 UTC, Radezolid commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/advanced_truncheon.yml
This file should go in the DeltaV folder

2024-11-05 16:37 UTC, Radezolid commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/advanced_truncheon.yml
> +    sprite: Objects/Weapons/Melee/Advanced trunch
Need to update the sprite path here.

2024-11-05 18:40 UTC, deltanedas requested changes

2024-11-05 18:40 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Research/arsenal.yml
> +    sprite: DeltaV/Objects/Weapons/Guns/Battery/energygun_carbine.rsi #changed sprite to ik-60
dont need this comment

2024-11-05 18:40 UTC, deltanedas commented on Resources/Locale/en-US/deltav/research/technologies.ftl
> +research-technology-robust-melee = Robust Melee
file needs to end in a newline

2024-11-05 18:40 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Research/arsenal.yml
> +- type:  technology
pro space

2024-11-05 18:40 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Research/arsenal.yml
> +#  - WeaponGunLaserCarbineAutomatic
just remove dont comment it out

2024-11-05 18:40 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/advanced_truncheon.yml
it should, and also inherit truncheon

2024-11-05 18:40 UTC, deltanedas commented on Resources/Textures/Objects/Weapons/Melee/meta.json
> +{
delete

2024-11-05 18:40 UTC, deltanedas commented on Resources/Prototypes/Research/arsenal.yml
you reordered half the techs in this file for no reason which will make 10000 conflicts and makes it infinitely harder to review

2024-11-05 18:40 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/advanced_truncheon.yml
> +  name: Advanced Truncheon
advanced truncheon

also parent -> id -> name -> description, reorder the fields

2024-11-05 18:50 UTC, deltanedas commented on Resources/Textures/Objects/Weapons/Melee/meta.json
bro delete the file :godmode:

2024-11-05 18:50 UTC, Stop-Signs commented on Resources/Textures/Objects/Weapons/Melee/meta.json
without the fi------ nevermind i see the issue

2024-11-05 19:33 UTC, Stop-Signs commented
@MilonPL its done

2024-11-05 23:55 UTC, deltanedas commented
this pr still mangles upstreams arsenal.yml

2024-11-06 00:27 UTC, Stop-Signs commented
> this pr still mangles upstreams arsenal.yml

the techs are laid in order of tier, i just moved them into those areas, i can move them back but It wouldnt be organized the same way as upstream

2024-11-06 00:47 UTC, Stop-Signs commented
> this pr still mangles upstreams arsenal.yml
what would yall prefer me do. i could comment out the techs and copy paste them onto the delta tech files. or i could move everything back where it was and have techs be in the inappropriate tier-section, but still be in place for upstream

2024-11-06 16:11 UTC, deltanedas commented
the sections dont matter, conflicts do

2024-11-06 17:01 UTC, Stop-Signs commented
> the sections dont matter, conflicts do

should be fixed

2024-11-06 18:13 UTC, Colin-Tel commented
![image](https://github.com/user-attachments/assets/594fa0b8-860e-4d93-9930-6cdc71ff6c6d)
Please reduce your changelog to just one or two lines.

2024-11-06 18:19 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Research/arsenal.yml
> +  tier: 3
i still dont see non antags getting tier 3 arsenal for funny kanabou

2024-11-06 18:22 UTC, deltanedas approved these changes, later dismissed
im happy codewise, just above

2024-11-06 23:23 UTC, MilonPL requested changes

2024-11-06 23:23 UTC, MilonPL commented on Resources/Prototypes/Research/arsenal.yml
> +  tier: 2 #Delta-V moved to t2 from t1
Remove the hyphen in `Delta-V`.

2024-11-06 23:23 UTC, MilonPL commented on Resources/Prototypes/Research/arsenal.yml
> +  tier: 2 #Delta-V moved to t2 from t1
Remove the hyphen in `Delta-V`.

2024-11-06 23:51 UTC, MilonPL requested changes

2024-11-06 23:51 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Recipes/Lathes/security.yml
newline at the end of file

2024-11-06 23:51 UTC, MilonPL commented on Resources/Prototypes/Research/arsenal.yml
> +  tier: 2 #DeltaV moved to t2 from t1
trailing space
```suggestion
  tier: 2 # DeltaV moved to t2 from t1
```

2024-11-06 23:51 UTC, MilonPL commented on Resources/Prototypes/Research/arsenal.yml
> +  tier: 2 #DeltaV moved to t2 from t1
trailing space

2024-11-07 01:13 UTC, Stop-Signs commented
ubuntu error is fake, this is ready to merge

2024-11-07 01:20 UTC, MilonPL requested changes

2024-11-07 01:20 UTC, MilonPL commented on Resources/Prototypes/Research/arsenal.yml
> +  tier: 2 #DeltaV moved to t2 from t1
trailing space still.

2024-11-07 01:20 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Research/arsenal.yml
> +    sprite: DeltaV/Objects/Weapons/Guns/Battery/energygun_carbine.rsi
remove the space after `energygun_carbine.rsi`

2024-11-07 01:26 UTC, MilonPL approved these changes

2024-11-07 01:36 UTC, merged