Map Updates: Arena
DeltaV-Station/Delta-v pull request #2138
Opened 2024-11-07 04:27 UTC by IamVelcroboy

## About the PR
**Arena**
- Adds AI
- Remodels the medbay
- Moves/adds cameras around for better AI
- FIxes [#2122](https://github.com/DeltaV-Station/Delta-v/issues/2122)
- Adds robo airlocks and spawnpoint for [#2028](https://github.com/DeltaV-Station/Delta-v/pull/2028)
- Adds Morgue airlocks
- Places proper bio

## Why / Balance
🥊

## Technical details
n/a

## Media
![image](https://github.com/user-attachments/assets/4168d196-cf78-4a7a-be0d-e3917cd8ee06)

## Requirements
n/a

## Breaking changes
n/a

**Changelog**
:cl: Velcroboy
- tweak: Changed Arena medbay layout

2024-11-07 04:29 UTC, MilonPL commented
HUGE

2024-11-07 04:29 UTC, IamVelcroboy commented
ooo buttholes, I forgot alarms

2024-11-07 09:31 UTC, deltanedas commented
@IamVelcroboy forgot job slots for ai and roboticist

2024-11-07 13:14 UTC, IamVelcroboy commented
> @IamVelcroboy forgot job slots for ai and roboticist

I thought that would be in a separate PR when those roles are merged? No?

2024-11-07 13:23 UTC, deltanedas commented
if the roles are enabled before any maps have slots itll be impossible to play them when you ready up for them
if maps have slots before roles are enabled all that happens is it makes tests fail, theres no ingame consequence

2024-11-07 14:05 UTC, IamVelcroboy commented
Makes sense

2024-11-10 04:06 UTC, JustTNE requested changes

2024-11-10 04:06 UTC, JustTNE commented on Resources/Prototypes/Maps/arena.yml
> +            AI: [ 1, 1 ]
The job slot here is incorrect.

```suggestion
            StationAi: [ 1, 1 ]
```

2024-11-30 15:50 UTC, therealDLondon approved these changes

2024-11-30 16:27 UTC, merged