Fix research
DeltaV-Station/Delta-v pull request #2144
Opened 2024-11-07 19:35 UTC by Stop-Signs

## About the PR
Removed the lockout on T3 research

## Why / Balance
Epi always getting t3 industrial just so they can have funny bags and powercells. this creates an issue where adding t3 tech (or anything service or arsenal related) is useless as epi will almost never research it.
## Technical details

## Media

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:

- remove: Removed the T3 Lockout on epi techs

2024-11-07 19:38 UTC, Avalon-Proto commented
Now we just need to make it so they need to research x amount of T1/T2 to level up tech

2024-11-07 19:39 UTC, Stop-Signs commented
> Now we just need to make it so they need to research x amount of T1/T2 to level up tech

This is already a thing, i could just raise the value

2024-11-07 19:41 UTC, Stop-Signs commented
Oh this also fixes an upstream error where you cant put research disks in the server without your dev env crashing

2024-11-07 20:16 UTC, MilonPL requested changes
noob change the lockout tier to 4 inside of the prototypes instead of whatever this is

2024-11-07 20:16 UTC, MilonPL commented
> Oh this also fixes an upstream error where you cant put research disks in the server without your dev env crashing

pr it upstream then

2024-11-07 20:19 UTC, Stop-Signs commented
> > Oh this also fixes an upstream error where you cant put research disks in the server without your dev env crashing
> 
> pr it upstream then

its already pr'd upstream ;)

2024-11-07 20:19 UTC, MilonPL commented
cherry pick in a separate PR

2024-11-07 21:18 UTC, MilonPL requested changes

2024-11-07 21:18 UTC, MilonPL commented on Content.Shared/Research/Prototypes/TechDisciplinePrototype.cs
set this in yaml

2024-11-07 21:18 UTC, MilonPL commented on Resources/Prototypes/Research/disciplines.yml
deltav comments

2024-11-07 22:43 UTC, ewokswagger commented
> cherry pick in a separate PR

[This is said pr](https://github.com/space-wizards/space-station-14/pull/33205) Its already marked as approved so I imagine it won't be long before it's here anyways.

2024-11-07 23:41 UTC, MilonPL requested changes, later dismissed

2024-11-07 23:41 UTC, MilonPL commented on Resources/Prototypes/Research/disciplines.yml
deltav comments

2024-11-07 23:41 UTC, MilonPL commented on Resources/Prototypes/Research/disciplines.yml
> +  lockoutTier: 4
.

2024-11-07 23:41 UTC, MilonPL commented on Resources/Prototypes/Research/disciplines.yml
> +  lockoutTier: 4
.

2024-11-07 23:41 UTC, MilonPL commented on Resources/Prototypes/Research/disciplines.yml
> +  lockoutTier: 4
.

2024-11-07 23:41 UTC, MilonPL commented on Resources/Prototypes/Research/disciplines.yml
> +  lockoutTier: 4
.

2024-11-07 23:41 UTC, MilonPL commented on Content.Shared/Research/Prototypes/TechDisciplinePrototype.cs
this file doesn't need any changes

2024-11-11 02:31 UTC, Colin-Tel submitted a review, later dismissed
Looks good to me and the curators I've asked.

2024-11-11 02:34 UTC, deltanedas requested changes

2024-11-11 02:34 UTC, deltanedas commented on Content.Shared/Research/Prototypes/TechDisciplinePrototype.cs
> +using Robust.Shared.Prototypes;
untouch

2024-11-11 02:36 UTC, Spielern commented
Epi, with the recent RE changes, has become a lot more stale. I just had a round 30 minutes ago where I had Svalinns, Microreactor Cells, Speed Boots, and Bluespace bags off of a single research server. The only thing stopping people from doing this every shift is the occasional RA that goes unchecked and raises glimmer by 500 with artifacts. This just seems insanely overpowered. I already dislike how epi's balance is, and I can see the department getting way more unbalanced and unfun with this. This could be a unique opinion to me, but I play an insane amount of epi and have heard similar discontent from other epi players in game through LOOC.

2024-11-11 02:45 UTC, deltanedas approved these changes

2024-11-11 02:46 UTC, Colin-Tel approved these changes

2024-11-11 02:48 UTC, Stop-Signs commented
> Epi, with the recent RE changes, has become a lot more stale. I just had a round 30 minutes ago where I had Svalinns, Microreactor Cells, Speed Boots, and Bluespace bags off of a single research server. The only thing stopping people from doing this every shift is the occasional RA that goes unchecked and raises glimmer by 500 with artifacts. This just seems insanely overpowered. I already dislike how epi's balance is, and I can see the department getting way more unbalanced and unfun with this. This could be a unique opinion to me, but I play an insane amount of epi and have heard similar discontent from other epi players in game through LOOC.

Not once in here did you mention the other t3's that get ignored by epi. bluespace syringes and beakers, as well as the advanced laser pistol and the Advanced truncheon are all things that epi doesn't benefit greatly from, but other departments do. the problem this PR seeks to solve is epistemics researching only for themselves instead of for everyone. If cloning got added to the civillian services tree as a t3, do you think epi would get that instead of their designer bags and needlessly infinite power cells?

2024-11-11 02:57 UTC, merged

2024-11-11 03:05 UTC, Spielern commented
> Not once in here did you mention the other t3's that get ignored by epi. bluespace syringes and beakers, as well as the advanced laser pistol and the Advanced truncheon are all things that epi doesn't benefit greatly from, but other departments do. the problem this PR seeks to solve is epistemics researching only for themselves instead of for everyone. If cloning got added to the civillian services tree as a t3, do you think epi would get that instead of their designer bags and needlessly infinite power cells?

I didn't mention any of the other T3s because I believe we should be heading the opposite way of this PR with Epi. IMO, T3 technologies were designed to be extremely good and rare, not something the crew is entitled to.
A large reason that I have seen Industrial being the only T3 chosen recently is BECAUSE of the fact that speed boots are able to be obtained for free. Before that, it was really just a coin flip depending on who is playing. I'd see arsenal and civilian both be picked fairly often, although Industrial still was the most common. Before the arsenal changes, all of the T3s except civilian benefit Epi AND the crew. People would just choose whatever they felt like in the moment, or whatever RA #3 accidentally pressed. I see no issue with how it was before, and still completely regret the RE changes. 
If your sole goal is to make Epi less selfish with their T3 picks, I firmly believe reverting the RE additions would be much more productive for both sides.

2024-11-11 03:16 UTC, deltanedas commented
- bluespace beakers have basically no use for epi, and limited use for med since chems arent infinite and if you are farming oxygen you will quickly run into the sink generation speed limit
- so many jobs benefit from speedboots, for one sec
- realistically only salv needs bags of holding, everyone else can manage a satchel within reason, bar atmos or paramed storing their suits
- engi, med, sec, salv all benefit from microreactors which is why theyre such a strong pick already
- t3 arsenal is solely for warops and syndies emagging lathes, you never see it otherwise
- t3 experimental is a 100% meme that benefits noone. half the time its made is just for exploiting 1 of 1000 bugs with the qsi, theres very little utility for anyone