New justice stamps and minor loadout adjustments
DeltaV-Station/Delta-v pull request #2158
Opened 2024-11-09 15:22 UTC by Tomce795

## About the PR
Added new stamps for Prosecutor and Clerk. Also adjusted their round-spawn equipment so they start with their respective stamps and with a Space Law book (like Attorney),

## Why / Balance
There are specific documents that can only be approved by certain members of Justice. Prosecutor can approve warrants, Court Clerk can approve parole. But these roles only have access to the same Lawyer stamp, like Attorney. This should help differentiate who actually stamped what and miiiight encourage more Justices to do more paperwork.

## Technical details
Added 2 new stamp sprites and 2 new stamped paper sprites. Adjusted meta.json for said new sprites
Added 2 rubber stamp prototypes with appropriate stamp components
Adjusted Prosecutor and Clerk loadouts to have the new stamps and a Space Law book.

## Media
![Stamp example](https://github.com/user-attachments/assets/f4884d60-0680-495b-abe8-26caff75502a)

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
Probably none?

**Changelog**
:cl:
- add: New stamps for Prosecutor and Clerk
- tweak: Adjusted default round-start equipment for Prosecutor and Clerk. They will now spawn with their respective stamps and a Space Law book.

2024-11-09 15:30 UTC, Tomce795 commented
Unironically unsure if the new sprites are supposed to be in here or the Delta-V folder which has the mantis one. I'm sure one of you's will yell at me thou :blunt:

2024-11-09 15:39 UTC, Avalon-Proto commented
I feel like I should mention this. The clerk already has a stamp which is called the Notary Stamp. So the clerk stamp here is irrelevant

2024-11-09 15:41 UTC, Tomce795 commented
Guh. Where does this stamp spawn? In a Clerk locker or something?

2024-11-09 15:42 UTC, Avalon-Proto commented
Yep, it does

2024-11-09 15:59 UTC, Tomce795 commented
Okay general idea is to then to remove the Clerk stamp, make the prosec one the only one added. Also probably shift about the stamp to the Delta-V resource folder (but the notary stamped paper sprite isn't there for some reason?). Do Prosec get their own locker? If not, I'll keep the loadout changes so that they spawn with it.

2024-11-09 16:07 UTC, Radezolid commented
Prosec doesn't get a locker, gotta add it to their loadout.

2024-11-09 22:49 UTC, Tomce795 commented
I dunno why the upstream files are still... modified, but that's to figure out later or to webedit away :blunt:

I believe the other stuff is okay, so nap time for me.

2024-11-09 23:00 UTC, Unkn0wnGh0st333 commented
Uhh change the 🆑 to only be one bullet, don't need two different change logs for the same PR (unless it's a massive PR) :blunt:

2024-11-10 07:00 UTC, MilonPL requested changes

2024-11-10 07:00 UTC, MilonPL commented on Resources/Locale/en-US/paper/stamp-component.ftl
untouch this file

2024-11-10 07:00 UTC, MilonPL commented on Resources/Prototypes/Entities/Objects/Misc/rubber_stamp.yml
untouch

2024-11-10 07:43 UTC, Tomce795 commented
Untouched upstream files. `git checkout upstream/master` to the rescue. GitHub is wacky and confuzzling but I think this is now good to merge after tests.

2024-11-12 04:15 UTC, MilonPL approved these changes

2024-11-12 04:15 UTC, merged