Genaric radio implants are no longer syndicate branded
DeltaV-Station/Delta-v pull request #2159
Opened 2024-11-09 18:42 UTC by beck-thompson

## About the PR

It didn't really make sense that they were syndicate branded! This also resolves the issue of finding a syndicate implant and not being able to do a search because it could be legal. Now all syndicate implants are illegal!

## Media

![image](https://github.com/user-attachments/assets/6f733bbb-61eb-4e0b-b12e-d5563dea734f)

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl: Beck Thompson
- tweak: Generic radio implants are no longer syndicate branded.

2024-11-09 21:46 UTC, beck-thompson commented
The implant name and stuff is a little weird (You wont get the name unless you drop it and then pick it up again) but I think that's an unrelated issue

2024-11-09 23:26 UTC, deltanedas commented
yeah thats normal

2024-11-15 07:38 UTC, TadJohnson00 commented
Direction has requested that you remove it from the uplink and at it to the logistics catalogue on the consideration that it lacks syndicate branding and has dubious legality.

2024-11-17 05:57 UTC, beck-thompson commented
> Direction has requested that you remove it from the uplink and at it to the logistics catalogue on the consideration that it lacks syndicate branding and has dubious legality.

Execution has acknowledged Directions request and has made the required changes

2024-11-17 06:20 UTC, LadyDanger2743 commented
> > Direction has requested that you remove it from the uplink and at it to the logistics catalogue on the consideration that it lacks syndicate branding and has dubious legality.
> 
> Execution has acknowledged Directions request and has made the required changes

Beautiful. The Director approves. Something something glory to NanoTrasen.

2024-11-17 12:55 UTC, deltanedas requested changes

2024-11-17 12:55 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/medical.yml
> +  description: Communicate without having to have that pesky headset on your ear.
needing a
having to have my beloved

2024-11-17 18:12 UTC, beck-thompson commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/medical.yml
> +  description: Communicate without having to have that pesky headset on your ear.
Grammar issues are always my downfall 😆

2024-11-17 19:02 UTC, deltanedas approved these changes

2024-11-17 19:06 UTC, merged