New weapon - Cold Laser
DeltaV-Station/Delta-v pull request #2170
Opened 2024-11-11 03:25 UTC by Stop-Signs

## About the PR
Added a Cold Laser for epi to research, will likely be thrown in the same tech as x-ray and laser cannons. Credit for the name I.C.E.E. ( Ionized Cryogenic Emission Equipment) goes to Pris Nero

## Why / Balance
A gun that slows people and does cold damage sounds cool, with speed playing such a big part in combat, it'd be nice to give it some solid counterplay. also RIP slime peoples.

## Technical details
TO DO
- [x] Make the projectile
- [ ] Sprite the weapon (likely a recolor of the laser cannon
- [ ]  tech tree
- [ ] lathe recipe
- [ ] Weapon code itself
- [ ] Possibly more that im forgetting :3

## Media
None yet

## Requirements

- [ ] I have tested all added content and changes.
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: I.C.E.E, a laser that deals cold, is now available for epi to research

2024-11-11 17:39 UTC, Stop-Signs commented
Right, so the main issue im dealing with is the lack of a way to make a hitscan laser modify body temp. if anyone knows how to do that please let me know.

2024-11-11 17:58 UTC, ThataKat commented
I am totally talking off the top of my head here but have you looked into the ice wing watcher code? It's projectile isn't hitscan to my recollection, but it does exactly what you're talking about.

2024-11-11 18:22 UTC, Stop-Signs commented
> I am totally talking off the top of my head here but have you looked into the ice wing watcher code? It's projectile isn't hitscan to my recollection, but it does exactly what you're talking about.

so that only works for projectiles, not hitscan. hitscan is shitcode and im currently working out a way to fix it

2024-11-11 20:07 UTC, Stop-Signs commented
errors are from the sprites and i honestly dont know how to fix it

2024-11-11 23:22 UTC, Radezolid approved these changes
Looks good to me now.

2024-11-12 04:20 UTC, MilonPL requested changes

2024-11-12 04:20 UTC, MilonPL commented on Content.Server/Weapons/Ranged/Systems/GunSystem.cs
> +using Content.Server.Temperature.Systems;
DeltaV comment

2024-11-12 04:20 UTC, MilonPL commented on Content.Server/Weapons/Ranged/Systems/GunSystem.cs
> +    [Dependency] private readonly TemperatureSystem _temperature = default!;
DeltaV comment

2024-11-12 04:20 UTC, MilonPL commented on Content.Shared/Weapons/Ranged/HitscanPrototype.cs
> +    [ViewVariables(VVAccess.ReadWrite), DataField("heatChange")]
VV + tag in the datafield are redundant

2024-11-12 04:20 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Projectiles/hitscan.yml
> +  heatChange: -50000
EOF newline

2024-11-12 15:28 UTC, MilonPL requested changes

2024-11-12 15:28 UTC, MilonPL commented on Content.Shared/Weapons/Ranged/HitscanPrototype.cs
>      public float StaminaDamage;
missing a line break

2024-11-12 15:28 UTC, MilonPL commented on Content.Server/Weapons/Ranged/Systems/GunSystem.cs
> +using Content.Server.Temperature.Systems;// DeltaV Heat Change system
missing a space

2024-11-12 15:28 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +
only one linebreak here

2024-11-12 15:28 UTC, MilonPL commented on Resources/Textures/DeltaV/Objects/Weapons/Guns/Battery/cold_cannon.rsi/meta.json
> +	"copyright": "Taken from vgstation at https://github.com/vgstation-coders/vgstation13/commit/125c975f1b3bf9826b37029e9ab5a5f89e975a7e, backpack sprite by Peptide, backpack sling sprite edited by Boa
is this even the right commit lmao

2024-11-21 05:15 UTC, CybersunOperative commented
I like the concept of a cold laser. Gives security some added utility with a weapon that both slows and wounds targets. Seems fitting for a T3 damage wise. 

Other voices in direction have voiced that they like it as well. Direction approves :3

2024-11-26 17:28 UTC, MilonPL requested changes

2024-11-26 17:28 UTC, MilonPL commented on Content.Server/Weapons/Ranged/Systems/GunSystem.cs
> +                            _stamina.TakeStaminaDamage(hitEntity, hitscan.StaminaDamage, source: user);
why

2024-11-26 17:28 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  parent: [BaseWeaponBattery, BaseGunWieldable, BaseRestrictedContraband]
spaces with inline yaml lists `[ Entity1, Entity2 ]`

2024-11-26 17:28 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  components:
prototype order

2024-11-27 06:59 UTC, deltanedas requested changes

2024-11-27 06:59 UTC, deltanedas commented on Content.Server/Weapons/Ranged/Systems/GunSystem.cs
> +
this just broke the staminadamage thing, move this if statement below it

2024-11-27 06:59 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  parent: [ BaseWeaponBattery, BaseGunWieldable, BaseRestrictedContraband ]
should be security contraband incase it ever gets reenabled

2024-12-17 04:56 UTC, Lyndomen approved these changes, later dismissed

2024-12-19 03:34 UTC, deltanedas approved these changes
ill fix nitpicks later

2024-12-19 03:34 UTC, merged