Xeno Buffs- Make Xenos actually scary
DeltaV-Station/Delta-v pull request #2183
Opened 2024-11-12 23:30 UTC by Avalon-Proto

## About the PR
This PR is a buff across the board to all xenos, to make them actually scarry. Doubles, sometimes triples their HP, and increases damage

## Why / Balance
Xenos as they stand are nowhere near as scary as slimes despite having their own massive rare event. So now, they will be scary as hell

## Technical details
Bumped HP and damage values considerably

## Media

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

🆑 
 - tweak: Xenos have become far hardier and scarier beasts to hunt on the station. Don't wander the maints alone

2024-11-12 23:34 UTC, deltanedas commented
this doesnt help rp in any way, it just makes it easier for new players to get killed by the untelegraphed xeno spawn(s) that immediately attacks you. you shouldnt need to have xenos be able to instagib you to rp being afraid of them

port xeno antag instead :trollface:

2024-11-12 23:38 UTC, Avalon-Proto commented
Not even gonna consider making them scarier till someone ports over the stuff from RMC?

2024-11-13 00:11 UTC, deltanedas commented
as i said more damage just hurts new players, you get absolutely no warning before a xeno/slime/spider/etc spawns ontop of you and if you dont know how to lose them while being slowed by damage, you die

2024-11-13 00:53 UTC, IamVelcroboy commented
Didn't actually look at the values of this PR but xenos def need to be buffed though. Right now they are way too squishy/weak.

2024-11-13 00:58 UTC, Lyndomen commented
the problem is when we have good things spawn completely randomly, it fuckign sucks to just die to rng.

2024-11-13 01:39 UTC, Radezolid commented
Why not an announcement about xeno signatures in the ventilation system trying to escape, give it a solid 30 seconds or so for people to get ready to run/hide

2024-11-13 02:33 UTC, Avalon-Proto commented
> Why not an announcement about xeno signatures in the ventilation system trying to escape, give it a solid 30 seconds or so for people to get ready to run/hide

If I knew how to do this I would v.v

2024-11-13 10:47 UTC, deltanedas commented
the thing is they spawn from vents/scrubbers so its essentially make a xeno free room with a wrench and crowbar or go into a toilet or something

2024-12-22 17:12 UTC, flowerfall-system commented
We definitely need to have stronger xenos! As it stands right now they're basically Vent Critters +, they need to carry more *weight.* If untelegraphed xeno attacks are the problem, telegraph them! Make an announcement a minute or maybe even thirty seconds before they spawn, let people prepare, et cetera.

Xenos deserve better rep! Delta V needs to be more dangerous!

2025-02-03 17:39 UTC, Avalon-Proto commented
Hey now that Xeno spawn is telegraphed to appear in a certain location maybe we can look at this PR again? :blunt:

2025-02-03 18:37 UTC, PAFFhassoocks commented
Xenos have telepathy comms, also they have a 30s raffle instead of the normal 10s raffle for other vent critters, this makes them extremely vulnerable for 30s as they cannot be controlled by players which are smarter than AIs.

2025-02-03 18:43 UTC, Lyndomen commented
xenos should spawn as a big group in space with telepathy

2025-02-03 18:46 UTC, PAFFhassoocks commented
xenos are also rarer than fucking ninjas and crumple like paper, they should be a red alert threat capable of killing a whole department's personnel, we dont really have an antag that has that objective, space dragons do this though and are given the tools fit for the job (they can actually kill people)
xenos have the ability to talk but they are KOS like dragons... they should have atleast 150-250 effective health for the drone/warriors.
xeno queens should be able to make babies more often, perhaps every 40s-60s.
xenos should be able to crit instead of dying instantly, perhaps with an addition of a healing xeno...

2025-02-03 19:40 UTC, deltanedas commented
make them use rmc health so you need 9 guys with ss14 guns to kill 1 drone :trollface:

2025-06-24 05:10 UTC, Avalon-Proto commented
Seeing as how the mobs all spawn from 1 vent/scrubber/passive vent now. And the Xeno vents still give the loud alarm alert that's unique to all the others. I am going to reopen this PR

2025-06-24 05:11 UTC, Avalon-Proto commented
Oh, I can't. Cause @deltanedas closed it

2025-06-24 05:24 UTC, deltanedas commented
7 months ago real

2025-06-24 17:08 UTC, Proxysseia commented
direction review 21 hours

2025-06-25 01:21 UTC, deltanedas requested changes

2025-06-25 01:21 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> + #    25: 0.5
just leave it since 25 is 1/6 health, might as well slow down then

2025-06-25 01:21 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +      150: Dead # DeltaV - Make Xenos Scary
was 50

2025-06-25 01:21 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +    speedModifier: 3 # DeltaV - Make them faster at door prying so they can actually get around
was 1.5

2025-06-25 01:21 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +        Structural: 35 # DeltaV - Some Xenos are good at breakign stuff
begin/end before types and after structural instead of commenting 2/3 lines added

2025-06-25 01:21 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +      250: Dead  # DeltaV - Make Xenos Scary
was 100

2025-06-25 01:21 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> + #     50: 0.7
similarly its 1/5 might as well just keep it

2025-06-25 01:21 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +        Slash: 20 # DeltaV - Make Xenos Scary
comment goes on the component, only need to specify damage everything else is the same

2025-06-25 01:21 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +        Slash: 10 # DeltaV - Make Xenos Scary
same stuff

2025-06-25 01:21 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +       Structural: 60 # DeltaV - The queen is VERY good at breaking stuff
.

2025-06-25 01:21 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +      200: Dead
missing comment entirely

2025-06-25 01:21 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +#      50: 0.7
.

2025-06-25 01:21 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +      125: Dead # DeltaV - Make Xenos Scary
comment on the component

2025-06-25 01:21 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +          Caustic: 15 # DeltaV - Make Xenos Scary
was 5

2025-06-25 01:24 UTC, Avalon-Proto commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> + #    25: 0.5
Fair

2025-06-25 01:24 UTC, Avalon-Proto commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +        Structural: 35 # DeltaV - Some Xenos are good at breakign stuff
Got it

2025-06-25 05:32 UTC, fow111 commented
shake bro pls

2025-06-25 20:43 UTC, Proxysseia commented
Direction Review:
These numbers make Xenos very strong, we will be keeping an eye on Xenos performance in the coming week.

Direction approved.

2025-06-25 20:46 UTC, Avalon-Proto commented
WOOHOO!

2025-06-26 16:19 UTC, deltanedas requested changes

2025-06-26 16:19 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +       Slash: 10 # DeltaV - Was 5 Brute
fix comment here too

2025-06-26 17:04 UTC, Avalon-Proto commented on Resources/Prototypes/Entities/Mobs/NPCs/xeno.yml
> +       Slash: 10 # DeltaV - Was 5 Brute
woops

2025-06-26 17:14 UTC, deltanedas approved these changes

2025-06-26 18:16 UTC, merged