Ports Bloodstains And Footprints from EE
DeltaV-Station/Delta-v pull request #2186
Opened 2024-11-13 03:40 UTC by Lyndomen

## About the PR
Puddles now get everywhere, and footprints can be cleaned up. Ported from https://github.com/Simple-Station/Einstein-Engines/pull/1190/

## Why / Balance
Its neat, I want it, and it will make the station more immersive. Also uh, something about janitors weeping. 

## Technical details
Lotta C#, ported from EE. I moved stuff to EE namespace, good luck us. 

## Media
![image](https://github.com/user-attachments/assets/500f48a5-afc5-420f-bafe-b746df16e279)
![image](https://github.com/user-attachments/assets/d3aaef4a-4f8b-4bcd-951d-43193f10a4e6)
![image](https://github.com/user-attachments/assets/ac540b4d-dd9f-4b69-abab-4cd83a685fc5)

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
I mangled the C# a bit to put it in a EE namespace. 

**Changelog**
:cl:
- add: Ported footprints and bloodstains from EE. Sorry Janitors.

2024-11-13 06:19 UTC, MilonPL requested changes, later dismissed

2024-11-13 06:19 UTC, MilonPL commented on Content.Shared/EE/Footprint/PuddleFootPrintsComponent.cs
> +    [ViewVariables(VVAccess.ReadWrite)]
these are already ReadWrite by default

2024-11-13 06:19 UTC, MilonPL commented on Content.Shared/EE/Footprint/PuddleFootPrintsComponent.cs
> +    [ViewVariables(VVAccess.ReadWrite)]
these are already ReadWrite by default

2024-11-13 06:19 UTC, MilonPL commented on Resources/Prototypes/Entities/Effects/puddle.yml
> +
what is this random line break

2024-11-13 06:19 UTC, MilonPL commented on Resources/Prototypes/Entities/Effects/puddle.yml
> +  - type: PuddleFootPrints #DeltaV- Begin updates from EE Blood Puddle
trailing space

2024-11-13 06:19 UTC, MilonPL commented on Resources/Prototypes/Entities/Effects/puddle.yml
> +  - type: Appearance #DeltaV-End updates from EE Blood Puddle
trailing space

2024-11-13 06:19 UTC, MilonPL commented on Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
> +    leftBarePrint: "footprint-left-bare-spider" #DeltaV port from EE, blood splatter
trailing space

2024-11-13 06:19 UTC, MilonPL commented on Resources/Prototypes/Entities/Mobs/Species/base.yml
> +  - type: FootPrints  #DeltaV port from EE, blood splatter
trailing space

2024-11-13 06:19 UTC, MilonPL commented on Resources/Prototypes/Entities/Mobs/Species/arachnid.yml
> +  - type: FootPrints
comment should start on the type declaration

2024-11-13 06:19 UTC, MilonPL commented on Resources/Prototypes/Entities/Mobs/Species/diona.yml
> +  - type: FootPrints
again trailing space + comment on the type

2024-11-13 06:19 UTC, MilonPL commented on Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
> +    rightBarePrint: "footprint-right-bare-dwarf" #DeltaV port from EE, blood splatter
trailing space + comment on the type

2024-11-13 06:19 UTC, MilonPL commented on Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
> +    rightBarePrint: "footprint-right-bare-lizard" #DeltaV port from EE, blood splatter
only needs comment at line 80 + trailing space

2024-11-13 06:19 UTC, MilonPL commented on Resources/Prototypes/Entities/Mobs/Species/slime.yml
> +    rightBarePrint: "footprint-right-bare-slime" #DeltaV port from EE, blood splatter
only one comment + space

2024-11-13 06:19 UTC, MilonPL commented on Resources/Prototypes/Entities/Mobs/Species/vox.yml
> +    rightBarePrint: "footprint-right-bare-lizard" #DeltaV port from EE, blood splatter
only one comment + space

2024-11-13 06:43 UTC, Lyndomen commented on Resources/Prototypes/Entities/Effects/puddle.yml
> +
EE code has a slip multiplier here for whatever reason so I put it in to track differences. No longer necessary I'll remove it when I wake up

2024-11-13 09:40 UTC, flowerfall-system commented
Yay yay yay let's DO it!!! :D

2024-11-13 10:10 UTC, dvir001 commented
This might sound like a small issue, but the folders should be ``_EE`` not ``EE``
This has a major effect on all forks that use code from EE and already has it as ``_EE`` folders, making it harder to cherry-pick in and out.

2024-11-13 10:36 UTC, deltanedas requested changes
i believe this was already used on goob and ended up ddosing the server with endless entity spam, if this is the same code it needs either timed despawn like goob added or fixing cleaning methods and limiting the amount of them per tile

2024-11-14 02:11 UTC, Lyndomen commented
yes it is same code, I will import https://github.com/Goob-Station/Goob-Station/pull/847 tmrw

2024-11-14 23:06 UTC, Lyndomen commented
![image](https://github.com/user-attachments/assets/52e6ed22-602a-489f-b959-d35902bfee37)
footprints despawn in 60 secs now, and requested tidying up has happened.

2024-11-15 01:13 UTC, IamVelcroboy commented
> footprints despawn in 60 secs now, 

Not that this whole PR isn't cool and I understand the performance concerns but doesn't this sort of defeat the purpose of footprints being a source of forensics evidence and creating work for janitors?

2024-11-15 03:23 UTC, Lyndomen commented
> > footprints despawn in 60 secs now,
> 
> Not that this whole PR isn't cool and I understand the performance concerns but doesn't this sort of defeat the purpose of footprints being a source of forensics evidence and creating work for janitors?

Yeah, it kinda does, but its maybe better than nothing? idk, Im down to change the timer if we wanna set it to 5 mins or something. All depends on the performance.

2024-11-15 03:43 UTC, ThataKat commented
I feel like they should persist a lot longer than 60 seconds, for the same reasons already given

2024-11-15 11:54 UTC, deltanedas commented
the main issue that led to it needing despawning is that you can have a stupid amount of them in a small area and cleaning didnt work, if they were limited and cleanable it would be fine

2024-11-15 12:01 UTC, MilonPL commented
we can revert it if the performance dies :blunt:

2024-11-15 12:21 UTC, deltanedas commented
it WILL die, on goob the janitors couldnt clean them no matter what and it ruined the tps

2024-11-15 17:23 UTC, Lyndomen commented
> the main issue that led to it needing despawning is that you can have a stupid amount of them in a small area and cleaning didnt work, if they were limited and cleanable it would be fine

cleaning works fwiw now 
![385575512-ac540b4d-dd9f-4b69-abab-4cd83a685fc5](https://github.com/user-attachments/assets/d1160750-8a6c-415e-b351-4093c39a9844)

2024-11-16 02:31 UTC, Aidenkrz commented
> it WILL die, on goob the janitors couldnt clean them no matter what and it ruined the tps

It was client side TPS :trollface: the visualizer should just be modified to only show the 10 top most footprints or whatever per tile
and cleaning should be fixed

2024-11-20 00:59 UTC, deltanedas approved these changes

2024-11-20 01:00 UTC, merged

2024-11-20 01:00 UTC, deltanedas commented
5 tps incident incoming

2024-11-20 01:04 UTC, MilonPL commented
i cant wait

2024-11-22 06:29 UTC, Emily9031 commented
It seems this was expected, but last night during a round there was a ton of blood on the evac shuttle, and the new footsteps caused a ton of performance issues from everything being in such a small space. I confirmed with other players that it seemed to be affecting everyone, even people with very good hardware such as myself.

Maybe detectives can be given a device similar to the t-ray scanner that shows footprints nearby that were cleaned or dried up.

TLDR more optimization needs to be done.

2024-11-22 06:56 UTC, MilonPL commented
who could've seen this coming