Space law guidebook
DeltaV-Station/Delta-v pull request #2187
Opened 2024-11-13 04:56 UTC by Unkn0wnGh0st333

## About the PR
Takes the cool part out of https://github.com/DeltaV-Station/Delta-v/pull/2076 and slaps it in its own PR

## Why / Balance
Do we really need to discuss why

## Media
![image](https://github.com/user-attachments/assets/419c7283-c542-4887-95ac-c09815c4320a)

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an in-game showcase.

**Changelog**
🆑 MilonPL, Unkn0wnGh0st333
- add: Space Law and SOP have been added to the guidebooks. Space Law books will now work as intended.

2024-11-13 04:57 UTC, Lyndomen commented
fire emoji

2024-11-13 05:51 UTC, LadyDanger2743 commented
Love this a lot, looking forward to it being in the game, Direction gold star of approval. 

As a warning, though, I'm working on a rewrite of SOP/SpLaw/CoPo, nearly finished everything. Don't let that stop the merge, but be advised that I'll need a hand in updating the guidebook entries with the new documents if you merge this before I'm ready to update the documentation.

2024-12-06 22:52 UTC, deltanedas commented
![10:52:16](https://github.com/user-attachments/assets/e02fff47-027d-499b-a32a-51bd7563e9d7)

2025-01-01 14:54 UTC, deltanedas commented
@LadyDanger2743 are you going to update space law soon or is this good for now

2025-01-01 14:56 UTC, deltanedas submitted a review, later dismissed

2025-01-01 14:56 UTC, LadyDanger2743 commented
> @LadyDanger2743 are you going to update space law soon or is this good for now

I'll get the space law update done in 24 hours. Apologies for the delay.

2025-01-01 14:58 UTC, deltanedas commented
real

2025-01-06 01:56 UTC, deltanedas commented
![01:56:17](https://github.com/user-attachments/assets/a5287412-9480-4fc3-aa5e-218ab225b093)

ITS REAL

2025-01-06 01:57 UTC, deltanedas requested changes
https://wiki.delta-v.org/view/Space_Law

2025-01-06 02:00 UTC, Lyndomen commented
Crime codes are being modified a bit

2025-01-06 20:53 UTC, Unkn0wnGh0st333 commented
time to finish this

2025-04-08 11:29 UTC, Toby222 commented
Hey what's the status of this?

2025-06-23 07:04 UTC, closed without merging