stamina projectile damage resist
DeltaV-Station/Delta-v pull request #2190
Opened 2024-11-13 19:34 UTC by MilonPL

## About the PR

adds a resist to incoming projectile stamina damage
most hardsuits provide a 10% protection, sec and syndicate hardsuits provide 70% protection, with exceptions for raid suits, jugg, elite, hos, warden, etc, whatever makes sense to be higher

## Why / Balance

stumeta bad and i'm cooking
you can't shift click it to meta the thing with highest stamina damage resist

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Hardsuits and armor vests now provide protection against incoming stamina projectile damage.

2024-11-13 20:21 UTC, deltanedas requested changes
i like an old prs stamina damage specifiers better, allows for more control over the different types of stuns

also the logic for not having an examine is terrible, if theres no examine the average player wont know it exists and the pro gamers will just grep the source anyway giving them an advantage

2024-11-13 20:23 UTC, MilonPL commented
> also the logic for not having an examine is terrible, if theres no examine the average player wont know it exists and the pro gamers will just grep the source anyway giving them an advantage

yes real i'm just coping with stamina not being a damage type 

i think that melee weapons should use the stamina resist based on blunt damage coefficient rather than having a separate value, and then the StaminaDamageCoefficent only works for projectiles (or maybe takes the higher value out of the two?)

2024-11-13 20:36 UTC, Lyndomen commented
I had started work on this yesterday to do a similar thing, by changing the YAML of all stamina weps to use bluntdamagestamina, which is then reduced by armor. Was advised this was maints hell 

https://github.com/DeltaV-Station/Delta-v/commit/3749fcadc9cf4d962ed41b1b4d1fb02e835d0fab

2024-11-13 20:44 UTC, ThataKat commented
Particulars might have to be tweaked but holy based. No more stunning nukies with rubbers?

2024-11-13 23:12 UTC, Stop-Signs commented
I really appreciate someone taking the time to do this. I do agree with delta in that you should be able to examine to see the stamina res, else it's only going to be abused by the "pros" and noobs will have a harder time understanding.

2024-11-14 08:15 UTC, deltanedas submitted a review, later dismissed
stunmeta is dead piemeta is new king

2024-11-14 08:16 UTC, deltanedas commented
change cl to reflect batong change

2024-11-14 08:24 UTC, MilonPL commented
> change cl to reflect batong change

hold on i was cooking

2024-11-14 08:26 UTC, MilonPL commented
conflicts no longer that evil

2024-11-14 14:08 UTC, deltanedas requested changes

2024-11-14 14:08 UTC, deltanedas commented on Content.Shared/DeltaV/Damage/StaminaSystem.Resist.cs
> +    public void TakeStaminaDamageWithMeleeCoefficient(EntityUid target, float damage, StaminaComponent? stamina = null, EntityUid? source = null, EntityUid? with = null, bool visual = true, SoundSpec
TakeMeleeStaminaDamage for the love of god

2024-11-14 14:08 UTC, deltanedas commented on Content.Shared/DeltaV/Damage/StaminaSystem.Resist.cs
> +    public void TakeStaminaDamageWithProjectileCoefficient(EntityUid target, float damage, StaminaComponent? stamina = null, EntityUid? source = null, EntityUid? with = null, bool visual = true, Soun
.

2024-11-14 14:10 UTC, MilonPL commented on Content.Shared/DeltaV/Damage/StaminaSystem.Resist.cs
> +    public void TakeStaminaDamageWithMeleeCoefficient(EntityUid target, float damage, StaminaComponent? stamina = null, EntityUid? source = null, EntityUid? with = null, bool visual = true, SoundSpec
:trollface:

2024-11-14 14:19 UTC, deltanedas approved these changes

2024-11-14 14:19 UTC, deltanedas commented
nukies are back

2024-11-14 14:28 UTC, merged