pain system
DeltaV-Station/Delta-v pull request #2192
Opened 2024-11-13 21:10 UTC by MilonPL

## About the PR

adds the pain system
currently can be only picked with the chronic pain trait
adds chromatic aberration to your screen + popups
has two status effects `InPain` and `SuppressPain` to interact with it
to-do:
- [ ] popups
- [ ] chronic pain trait
- [ ] integrate with painkillers

## Why / Balance

roleplay
tbd

## Technical details

## Media

![image](https://github.com/user-attachments/assets/137c154a-dba0-4636-8646-ec2568fd2051)

## Requirements

- [ ] I have tested all added content and changes.
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-11-13 21:34 UTC, HTMLSystem commented
This seems really cool!! I love the idea of a chronic pain trait! Question though: Is the chromatic aberration constant or only when the pain flares up?

2024-11-13 21:35 UTC, MilonPL commented
> This seems really cool!! I love the idea of a chronic pain trait! Question though: Is the chromatic aberration constant or only when the pain flares up?

Goes away when you're on painkillers

2024-11-13 21:44 UTC, HTMLSystem commented
Nah, i think it going away while on pain killers would be good. Either way I'm excited for this :)!!

2024-11-14 11:14 UTC, MilonPL commented
@deltanedas you're going to love this one
i was high, drunk and/or sleep deprived while coding all this, and i have no idea how or why half of it works

2024-11-19 19:51 UTC, alterae commented
massively, massively, MASSIVELY in favor of this to a degree that I cannot properly express

2024-11-19 20:49 UTC, deltanedas requested changes

2024-11-19 20:49 UTC, deltanedas commented on Content.Server/DeltaV/Pain/PainSystem.cs
> +        SubscribeLocalEvent<PainComponent, ComponentStartup>(OnInit);
use MapInitEvent

2024-11-19 20:49 UTC, deltanedas commented on Content.Shared/DeltaV/Pain/SharedPainSystem.cs
> +        UpdatePainSuppression(ent, duration, level);
just pass `(uid, comp)` dont need new Entity

2024-11-19 20:49 UTC, deltanedas commented on Content.Shared/DeltaV/Pain/SharedPainSystem.cs
> +public enum PainSuppressionLevel
make it extend byte

2024-11-19 20:49 UTC, deltanedas commented on Resources/Prototypes/Reagents/narcotics.yml
> +      - !type:ChemRerollPsionic #Nyano - Summary: lets the imbiber become psionic.
bad line changed

2024-11-19 20:49 UTC, deltanedas commented on Resources/Prototypes/_CD/Reagents/medicine.yml
> +          - !type:ReagentThreshold
line

2024-11-19 20:49 UTC, deltanedas commented on Resources/Prototypes/_CD/Reagents/medicine.yml
> +          - !type:ReagentThreshold
line

2024-11-20 00:58 UTC, deltanedas approved these changes

2024-11-20 00:59 UTC, merged