Build Diona Different
DeltaV-Station/Delta-v pull request #2204
Opened 2024-11-15 18:09 UTC by Lyndomen

## About the PR
Somewhat restores Nyano diona, they are slower & more tanky, and cooler. 

## Why / Balance
Janitor diona is the worst experience

- Slows sprint 4.5 > 3
- Slows Walk 2.5 > 1, notably this means they can walk on space lube and not slip. 

- Piercing:  1 > 0.6
- Blunt: .7 > .6
- Slash:  .8 > .7

Changes Ignite threshold (max heat damage taken before ignition)
12 > 20. A diona with zero armor takes 21 heat from a normal laser and will still ignite. 10% heat resistance will put them under that threshold- or a bigger laser. 

## Technical details
only yaml

## Media
![image](https://github.com/user-attachments/assets/d511c7a3-7bed-47d2-b4c7-810da8f8a3ca)
my video was too big but they slow

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- tweak: Diona are substantially more tanky, and ignite less frequently
- tweak: Diona are much slower

2024-11-15 22:19 UTC, Bonktrauma commented
FINALLY!!! THE RETUEN TO OUR GLORY DAYS OF SLOW DIONA

2024-11-19 02:08 UTC, CybersunOperative commented
Hi. Direction here. Seems fine from a balance perspective. Heat damage ignite threshold has probably been long overdue for an increase. I'm sure our three total Diona players will enjoy being able to RP their epic slowness again.

Other voices in direction have said that they support this PR as well. :3

2024-11-19 02:18 UTC, Bonktrauma commented
> Hi. Direction here. Seems fine from a balance perspective. Heat damage ignite threshold has probably been long overdue for an increase. I'm sure our three total Diona players will enjoy being able to RP their epic slowness again

This is hilariously accurate,  I can go like 3 shifts without seeing a single other diona player

2024-12-05 04:15 UTC, MilonPL requested changes

2024-12-05 04:15 UTC, MilonPL commented on Resources/Prototypes/Entities/Mobs/Species/diona.yml
> +  - type: FootPrints # begin DeltaV
should really just be two separate comments, ond on the footprints and one on the movement modifier comp

2024-12-09 05:43 UTC, MilonPL approved these changes

2024-12-09 05:44 UTC, merged