feat: HydroCo - Beverage Powders
DeltaV-Station/Delta-v pull request #2210
Opened 2024-11-16 03:15 UTC by DisposableCrewmember42

## About the PR
- Added HydroCo Dairy and Juice crates. They contain beverage powders that, when mixed with water in a 1:1 ratio and stirred, create the advertised beverage.
- Each tin contains 50u of powder, which can create 100u of liquid
- The dairy crate costs 1500 Spesos and contains
  - 3 Milk tins
  - 1 Soy Milk tin
- The juice crate costs 2000 Spesos and contains one tin each of
  - Orange
  - Lime
  - Lemon
  - Pineapple
  - Banana
  - Berry
  - Watermelon
  - Grape
  - Apple
  - Cherry
  - Carrot
- Both crates further contain two spoons and a note from HydroCo
- The HydroCo (HYD) stock was added to StockTrade
- If powder is eaten straight, it causes coughing. If more than 15u is consumed, there is a chance of vomiting.
- The more acidic juice powders (pineapple, lemon, lime) cause 1 caustic damage per unit consumed

## Why / Balance
Requested in [The Drawing Board](https://discord.com/channels/968983104247185448/1152625672020316200/1306820163622142043) and further discussed in a [dedicated thread](https://discord.com/channels/968983104247185448/1307145855199084644/1307145855199084644).

Regarding balance:
I believe the prices are justified and high enough to discourage buying lots of juice instead of cooperating with Botany, especially since you can't order specific types in bulk.

## Technical details
YML changes mostly inline with everything else in each file. For the tins, I created a new base type, since neither the FoodTinBase prototype nor the ReagentPacketBase suited my exact needs.

The texture uses the Sprite color attribute and an overlay to avoid lots of pointless and tiring work, and make it easy to add new types in the future.

## Media

![tins](https://github.com/user-attachments/assets/7de71d0e-c3c4-4a52-a056-01f9b769e0dc)
![notice](https://github.com/user-attachments/assets/fcb8889e-1f4a-4795-bd6d-0ac5387843bc)
![inspect](https://github.com/user-attachments/assets/a6321889-45eb-420b-b0e9-9d628d0d7bfa)

https://github.com/user-attachments/assets/2a199100-7938-44ce-92cd-5bbce76dd9da

https://github.com/user-attachments/assets/84ec0289-ac4d-4f5f-a53f-d896859bec2e

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: DisposableCrewmember42
- add: NanoTrasen has established business relations with HydroCo! You can now order powdered milk and juice via your Logistics department and bet on the success of the HYD stock.

2024-11-17 16:56 UTC, IamVelcroboy commented
This is really neat. My main suggestion would be to reduce the contents of the fruit crates to 4 and use rng group [tables](https://docs.spacestation14.com/en/space-station-14/core-tech/entity-tables.html).  
With like: 
- group 1 citrus (Lemon, Lime, Orange) 
- group 2 berry (berry, cherry, grape) 
- group 3 tropical (pineapple, banana, watermelon) 
- group 4 other (apple, carrot)

2024-11-17 17:45 UTC, dvir001 commented
Please add a crate for energy drinks versions. (GFuel, GamerSupps).

Call it GamerDonkCo / CyberFuel / SyndijuiceSupps etc

2024-11-17 17:51 UTC, IamVelcroboy commented
Another suggestion, one or two of these would probably be a good addition to the perma SusVend

2024-11-17 17:59 UTC, Avalon-Proto commented
> Another suggestion, one or two of these would probably be a good addition to the perma SusVend

Speaking of that machine, it needs a restock or something. Currently doesn't have one and it'd be nice to be able to restock it so the Perma players have somewhat reliable food besides what they make

2024-11-17 18:15 UTC, IamVelcroboy commented
> > Another suggestion, one or two of these would probably be a good addition to the perma SusVend
> 
> Speaking of that machine, it needs a restock or something. Currently doesn't have one and it'd be nice to be able to restock it so the Perma players have somewhat reliable food besides what they make

Definitely out of scope for this PR but it would be an easy PR for anyone to do.

2024-11-18 00:06 UTC, DisposableCrewmember42 commented
> Please add a crate for energy drinks versions. (GFuel, GamerSupps).
> 
> Call it GamerDonkCo / CyberFuel / SyndijuiceSupps etc

I'll probably PR more variations of beverages at a later point, but I'd consider that out of scope for now. I was thinking of also adding syrups for SpaceUp and stuff like that, but powdered energy drinks would work too.

2024-11-18 00:07 UTC, DisposableCrewmember42 commented
> This is really neat. My main suggestion would be to reduce the contents of the fruit crates to 4 and use rng group [tables](https://docs.spacestation14.com/en/space-station-14/core-tech/entity-tables.html). With like:
> 
>     * group 1 citrus (Lemon, Lime, Orange)
> 
>     * group 2 berry (berry, cherry, grape)
> 
>     * group 3 tropical (pineapple, banana, watermelon)
> 
>     * group 4 other (apple, carrot)

Makes sense, I'll do that and reduce the price to 1500.

2024-11-18 06:25 UTC, DisposableCrewmember42 commented
oh god i fucked up the rebase

2024-11-18 07:33 UTC, DisposableCrewmember42 commented
This doesn't modify C#, label can be removed. Should be the final changes, ready for review!

2024-11-19 02:25 UTC, IamVelcroboy commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/food.yml
> +          amount: 1
Amounts of 1 don't need to be specified. They are the default value.

2024-11-19 02:25 UTC, IamVelcroboy commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/food.yml
> +          amount: !type:ConstantNumberSelector
Same with this and all the rest down the line. Value of 1 is default.

2024-11-19 02:25 UTC, IamVelcroboy commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/food.yml
> +- type: entityTable
This doesn't look to be used anywhere. See comment I left you in Discord.

2024-11-19 02:25 UTC, IamVelcroboy commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/food.yml
> +- type: entityTable
Modular tables like this works but they *could* be condensed. See: [comment](https://discord.com/channels/968983104247185448/1307145855199084644/1308253511133171772) in Discord.

2024-11-19 09:28 UTC, DisposableCrewmember42 commented
i rebased and reworded a commit to retrigger the flaky test and did the thing again, apparently that's not a great idea after merge commit

2024-11-21 19:01 UTC, MilonPL requested changes
https://docs.spacestation14.com/en/general-development/codebase-info/conventions.html#yaml-conventions

2024-11-21 19:01 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Drinks/powdered_drinks.yml
> +  components:
wrong order

2024-11-21 19:01 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Misc/paper.yml
> +  parent: Paper
wrong order

2024-11-21 19:01 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Misc/paper.yml
> +  parent: Paper
above

2024-11-23 01:05 UTC, DisposableCrewmember42 commented
not sure why it still shows 1 change requested, i marked everything as resolved

2024-11-24 10:16 UTC, MilonPL requested changes

2024-11-24 10:16 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/food.yml
> +  parent: CratePlastic
move parent above id

2024-11-24 10:16 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/food.yml
> +  parent: CratePlastic
above

2024-11-24 10:16 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/food.yml
> +    #Citrus
comments should have trailing spaces like
`# Comment`

2024-11-24 10:16 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Drinks/powdered_drinks.yml
> +  abstract: true
abstract should be above parent

2024-11-24 10:54 UTC, DisposableCrewmember42 commented
test failures unrelated

2024-11-25 06:23 UTC, DisposableCrewmember42 commented
Conflicts resolved

2024-11-29 09:39 UTC, MilonPL approved these changes

2024-11-29 09:51 UTC, merged