feat: Add emergency pie delivery
DeltaV-Station/Delta-v pull request #2211
Opened 2024-11-16 04:05 UTC by DisposableCrewmember42

## About the PR
> Then let them eat cake.

Added emergency pie delivery crate, containing 4 banana cream pies and setting Logistics back by 666 Spesos.

## Why / Balance
Requested [in Discord](https://discord.com/channels/968983104247185448/1307145855199084644/1307150175780733009).

## Technical details
Added FoodEmergencyPie and CrateFoodEmergencyPie along with necessary i18n

## Media
None

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl: DisposableCrewmember42
- add: Hungry? Stuff your face with cream from an emergency pie delivery for a change!

2024-11-16 04:11 UTC, deltanedas requested changes

2024-11-16 04:11 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/food.yml
> +- type: entity
this should have the locale here for english, ent- is for translation

2024-11-25 05:21 UTC, deltanedas requested changes

2024-11-25 05:21 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/food.yml
> +    - type: StorageFill
unindent a level

2024-11-25 05:21 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/food.yml
> +        - id: FoodPieBananaCream
unindent a level

2024-11-25 05:25 UTC, DisposableCrewmember42 commented
*screams*

2024-11-25 05:30 UTC, deltanedas approved these changes

2024-11-25 05:30 UTC, merged