Adjust Security Loadouts, adds alternative firearms
DeltaV-Station/Delta-v pull request #2214
Opened 2024-11-16 21:01 UTC by Lyndomen

## About the PR
Removed MK58 from security equipment, and removed spare magazine.  Removes Inspector & speedloaders from detective belt. 

Adds new loadout category for HOS, Warden, Corpsman, Prison Guard, & Officer: **Security Firearm**
- Pollock 
- SLP-57
- Mk 58
- disabler
- fitz special
- k-38 masterpiece

Adds new loadout category for HOS, Warden, Corpsman, Prison Guard, & Officer: **Ammunition**
- .35 lethal
- .35 rubber
- .38 special lethal speedloader
- .38 special rubber speedloader

Adds new loadout category for Detective: **Security Revolver**
- Inspector
- Snubbed .45

Adds new loadout category for Detective: **Ammunition**
- .45 magnum speedloader
- .45 magnum rubber speedloader

Cadets also gain a disabler. 

## Why / Balance
More gun options is cool. None of these dramatically adjust balance, if anything they are worse than the MK58. Compare guns & talk to people. Bring your own gun to work day

## Technical details
YAML loadouts

## Media
![image](https://github.com/user-attachments/assets/82de329d-0f52-41b6-8bae-d0183120e1c6)
![image](https://github.com/user-attachments/assets/9e4056eb-9623-4c50-9482-0d0d0e64e932)
![image](https://github.com/user-attachments/assets/6c01f6cd-de16-4f0f-beb8-7d3107f71982)
![image](https://github.com/user-attachments/assets/9a5449fe-4f53-4809-bda5-2e4a9b516fd0)
![image](https://github.com/user-attachments/assets/d0fa1a70-0c71-4b4a-974d-b6c05c21d340)
![image](https://github.com/user-attachments/assets/fc82f378-0861-4811-af2c-c34b2ea79ceb)

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
no

**Changelog**
:cl:
- add: Security roles may select their service weapon in loadouts, along with their ammunition of choice

2024-11-16 21:06 UTC, deltanedas requested changes

2024-11-16 21:06 UTC, deltanedas commented on Resources/Locale/en-US/deltav/preferences/loadout-groups.ftl
> +
extra line bad

2024-11-16 21:06 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Roles/Jobs/Security/brigmedic.yml
> + #  pocket1: WeaponPistolMk58Nonlethal # DeltaV loadouts
`DeltaV - loadouts` for these

2024-11-16 21:06 UTC, deltanedas commented on Resources/Prototypes/Loadouts/Jobs/Security/detective.yml
> +- type: loadout # DeltaV
put these in the deltav folder

2024-11-16 21:06 UTC, deltanedas commented on Resources/Prototypes/Loadouts/Jobs/Security/security_officer.yml
> +- type: loadout # DeltaV
.

2024-11-16 21:06 UTC, deltanedas commented on Resources/Prototypes/Loadouts/role_loadouts.yml
> +  - SecurityStar
sus

2024-11-16 23:56 UTC, ThataKat commented
Pollock my beloved. Maybe some of these should have playtime requirements so only cool kids get cool guns?

2024-11-17 00:10 UTC, Radezolid commented
The .38 guns should be Senior Officer minimum IMO

2024-11-17 00:43 UTC, deltanedas requested changes

2024-11-17 00:43 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Loadouts/loadout_groups.yml
> +
untroll

2024-11-17 00:43 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Loadouts/loadout_groups.yml
> +
untroll

2024-11-17 00:43 UTC, deltanedas commented on Resources/Prototypes/Loadouts/role_loadouts.yml
> +  - SecurityStar
this line is still changed erroneously

2024-11-17 00:43 UTC, deltanedas commented
gatekeeping guns is already done with cadet vs secoff :trollface:

2024-11-17 00:53 UTC, Lyndomen commented
I don't love gatekeeping things with mechanical differences between hours played, can feel a bit shit imo for new players

2024-11-17 00:54 UTC, deltanedas submitted a review, later dismissed
approved codewise but the guns balance need to be looked at so theres not a clear meta

2024-11-17 00:55 UTC, Lyndomen commented
> approved codewise but the guns balance need to be looked at so theres not a clear meta

Real was gonna nerf .45 in another PR soon, gotta test it more. Or just axe universals idk, op ass guns

2024-11-17 19:57 UTC, CybersunOperative commented
Hi, Hello. Direction here (val). We would rather not give regular officer's .38s. We are more receptive to giving Detective access to .38 revolvers (And I personally recommend the "Lucky 37" since it looks cooler and is pretty much the same as the K-38.)

I request that the Snubnose is removed from an option. It's performance is questionable and unbefitting security. 

I am unsure if you are aware, but the K-38 loads with rubbers already loaded. This is fine, but you might want to change that so it's in line with the other weapons.

HoS/Warden should also have access to the revolver options that the detective has.

after that, it should be alright. more loadout options for security is based.

2024-11-17 20:20 UTC, Lyndomen commented
HOS Warden Loadout: 
![image](https://github.com/user-attachments/assets/5b4ee210-778f-4d52-8925-ecad1c1b9819)


Det loadout: 
![image](https://github.com/user-attachments/assets/926fa7a3-99de-4a4c-8dd1-7567b6053a46)


Officer loadout: 
![image](https://github.com/user-attachments/assets/2576164e-a909-440d-a932-9b9c05dca431)


38 special guns now spawn with lethals: 
![image](https://github.com/user-attachments/assets/e4e4cb71-12ba-47c4-bc3c-87d2a519252d)

2024-11-17 21:39 UTC, CybersunOperative commented
I have no further balance questions, seems fine to merge if Deltanades says the code is fine. No one else in direction has commented on this PR who I haven't already voiced the opinion of.

2024-11-18 00:24 UTC, deltanedas requested changes

2024-11-18 00:24 UTC, deltanedas commented on Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
> +    pocket1: WeaponDisabler # DeltaV - loadouts
comment should stay the same

2024-11-18 01:56 UTC, deltanedas approved these changes

2024-11-18 02:08 UTC, merged