Add Changelog Entry for Teach Lesson
DeltaV-Station/Delta-v pull request #2225
Opened 2024-11-18 15:12 UTC by Lyndomen

## About the PR
Changelog missing from https://github.com/DeltaV-Station/Delta-v/pull/2184

## Why / Balance
It is important to let people know

## Technical details
yaml, but idk if its better of CL it here too

## Media
no

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
no...?

2024-11-18 15:14 UTC, deltanedas requested changes

2024-11-18 15:14 UTC, deltanedas commented on Resources/Changelog/DeltaVChangelog.yml
> +  id: 683
pro

2024-11-18 15:21 UTC, MilonPL requested changes
just add it to this pr's cl and wait for publish

2024-11-18 15:30 UTC, Lyndomen commented on Resources/Changelog/DeltaVChangelog.yml
> +  id: 683
nothingburger commit

2024-11-18 15:30 UTC, Lyndomen commented
if someone can check the CL, i think its the double person that fucked it up fucked if i know

2024-11-18 15:36 UTC, MilonPL approved these changes

2024-11-18 15:37 UTC, MilonPL commented
yes real it was the dot in the name

2024-11-18 15:49 UTC, Lyndomen commented
> yes real it was the dot in the name

:trollface:

2024-11-19 03:58 UTC, deltanedas approved these changes

2024-11-19 03:58 UTC, merged

2024-11-19 18:14 UTC, jimmy12or commented
But... you're not allowed to remember.

2024-11-19 18:47 UTC, Lyndomen commented
> But... you're not allowed to remember.

People can tell you "bruh you just got eaten by carp, who did you piss off"

2024-11-19 18:49 UTC, Radezolid commented
> But... you're not allowed to remember.

You are not allowed to remember your killer, you can recall being beaten up with a bat "for some weird shit they were yelling that it was my fault" or something alike.