Beam Devestator (RPG Replacement)
DeltaV-Station/Delta-v pull request #2231
Opened 2024-11-18 19:45 UTC by Stop-Signs

## About the PR
Adds the beam devastator, a much more powerful version of the beam cannon in #2221. Since the RPG is on the chopping block this could serve as a worthy replacement. It shoots several small damage beams a second and can be sprayed effectively. mag size of 500. takes incredibly long to recharge (about 10 minutes with a standard recharger), however it can be slotted into a cage recharger which has also been buffed, at this rate it takes ~3 minutes to fully charge.

IMPORTANT NOTE!!!!!!:  This item is UNOBTAINABLE and in order to replace the RPG will need to be MAPPED to do so. I am willing to map it myself but I don't exactly know how to do so.

## Why / Balance
Curators were looking for an RPG replacement, this gun has a fairly low TTK and instead relies on sustained fire to be as oppressively as it is. A worthy successor to the RPG while not being just a no-skill one-tapinator

## Technical details

## Media
Github says the videos are too big. heres the sprite instead
![base](https://github.com/user-attachments/assets/b6dfb683-9ca4-42ce-aa7c-28fa07189c93)

## Requirements
- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.>

:cl:
- add: NT is looking into replacing each stations RPG with a Beam Devastator, keep an eye out for it!
- tweak: The Cage Recharger can now charge lasers.

2024-11-18 20:08 UTC, Lyndomen commented
![image](https://github.com/user-attachments/assets/21958497-d14c-4173-b7ac-1bd9b0dd8973)

https://github.com/user-attachments/assets/99be5a2c-51a6-4419-9512-a52eea683a23

Both of these weapons are balanced by their frankly **bad** time to kill, being about twice that of a Universal. To compensate, they have massive ammo capacities and are intended to hold down an area with suppressing fire. 

The projectile sprite itself is sped up on its frame time to feel more snappy, and feel more like a "beam". Similarly, the sound is a bass-y hum rather than a sharp pop- to accommodate for the hearing of everyone else.

2024-11-18 21:58 UTC, ThataKat commented
Makes sense for security to have a "heavy" weapon that's more defensive (doesn't literally punch a hole in their own vessel).

2024-11-18 22:29 UTC, Lyndomen commented
> Makes sense for security to have a "heavy" weapon that's more defensive (doesn't literally punch a hole in their own vessel).

For direction's discussion, the Devestator **does do structural damage.** 
![image](https://github.com/user-attachments/assets/0be866de-5235-4923-a455-bc8abbb8888b)

However, its still a laser and infinity more controllable. It also takes a GOOD bit of time and ammo, but is genuinely feasible. This gives security a reliable "breaching" weapon as long as what they are breaching into isn't a window :trollface:  

I intend to PR a researchable "mining/deconstruction" version of this gun eventually.

2024-11-18 22:31 UTC, Lyndomen commented
Also quick note that walls & structures reduce Structural damage by 10, and then another percentage, so "20 structural" is a lot less than 30. It takes time to breach, I recommend playing with the gun in a sandbox.

2024-11-18 22:53 UTC, Radezolid commented
I think it isn't a good replacement for the RPG, for example a nuclear operative can just buy a E-Shield to counter the devastator and forget about it.

2024-11-18 23:00 UTC, Lyndomen commented
> I think it isn't a good replacement for the RPG, for example a nuclear operative can just buy a E-Shield to counter the devastator and forget about it. Besides that, i love the guns.

Real, I was thinking about reducing shield reflect chance and buffing it's health value anyway

2024-11-18 23:03 UTC, Stop-Signs commented
it takes ~100 shots to bust a reinforced wall

2024-11-18 23:05 UTC, Radezolid commented
Also, it won't really help as a breaching tool unless you're breaching an airlock since the lasers go thru the girders + the slowdown, you can just use a breaching charge instead

2024-11-21 04:48 UTC, Lyndomen commented
Requesting review, should be good to go honestly as it's balance approved & the RPG replacement happens per map.

2024-11-21 05:26 UTC, CybersunOperative commented
RPG REPLACEMENT REAL RAAAAGH.
I like it. It feels more suppressive instead of "Fire and Forget" antag obliterator. Zombie Mains weeping. 

This sentiment is shared by direction. (Who also hate the RPG) :blunt:
I would ask mappers after this PR is merged about this change.

2024-11-21 19:28 UTC, LadyDanger2743 commented
Really the only thing that I'm curious about is how effective it is at clearing standard and reinforced walls. Other than that, it has the Direction Seal Of Approval.

2024-11-21 19:29 UTC, Stop-Signs commented
> Really the only thing that I'm curious about is how effective it is at clearing standard and reinforced walls. Other than that, it has the Direction Seal Of Approval.

I did test this, it takes over 100 shots to do so!

2024-11-21 19:30 UTC, LadyDanger2743 commented
> > Really the only thing that I'm curious about is how effective it is at clearing standard and reinforced walls. Other than that, it has the Direction Seal Of Approval.
> 
> I did test this, it takes over 100 shots to do so!

Alright, that's all I really need. This has Direction's approval to merge.

2024-11-26 17:31 UTC, MilonPL requested changes

2024-11-26 17:31 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  components:
prototype order

2024-11-26 17:31 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  components:
above

2024-11-26 17:31 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  parent: [BaseWeaponBattery, BaseGunWieldable, BaseSecurityContraband]
spaces in inline lists

2024-11-26 17:31 UTC, MilonPL commented on Resources/Prototypes/Entities/Structures/Power/chargers.yml
> -        name: Power cage
comments

2024-11-26 17:31 UTC, MilonPL commented on Resources/Prototypes/Entities/Structures/Power/chargers.yml
> +          - HitscanBatteryAmmoProvider
above

2024-11-26 17:31 UTC, MilonPL commented on Resources/Prototypes/Research/arsenal.yml
> +  # End of modified code
why, just do a single comment

2024-11-29 16:27 UTC, therealDLondon commented
This isnt code approval, but its approved as far as im concerned.
Direction approved, millions must merge

2024-11-29 19:33 UTC, deltanedas requested changes

2024-11-29 19:33 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  name: Beam Cannon
not a proper noun, beam cannon

2024-11-29 19:33 UTC, deltanedas commented on Resources/Prototypes/Entities/Structures/Power/chargers.yml
> +          - HitscanBatteryAmmoProvider # DeltaV - allows hitscan guns to be charged
blacklist power cells too or this is just gamer turbo charger

2024-11-29 19:33 UTC, deltanedas commented on Resources/Textures/DeltaV/Objects/Weapons/Guns/Battery/beam_cannon.rsi/meta.json
> +  },
fix indent

2024-11-29 20:20 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +      - PowerCage
unindent this by 2 spaces :trollface:

2024-11-29 20:21 UTC, deltanedas commented on Resources/Textures/DeltaV/Objects/Weapons/Guns/Battery/beam_cannon.rsi/meta.json
> +  },
this is still 2 spaced

2024-11-29 20:44 UTC, deltanedas approved these changes

2024-11-29 20:45 UTC, deltanedas commented
removed the beam devastator line from cl as this pr doesnt replace anything and it isnt likely to get migrated for every map

2024-11-29 20:45 UTC, merged