EE Tail Wagging (Real)
DeltaV-Station/Delta-v pull request #2241
Opened 2024-11-19 21:48 UTC by Unkn0wnGh0st333

## About the PR
Ports Einstein Engine's Vulpkanin Tail Wagging & Vulpkanin custom screams.

## Why / Balance
Wagging tail on command will be the new stunmeta since everyone will be so scared of your aura when your tail stops wagging

## Technical details

- [ ] Einstein-Engine Tail Wagging System
- [ ] Vulpkanin Custom Screams
- [ ] Felinid Tail Wagging on command (Unfinished)

## Media
(remind me to add)

## Requirements
- [ ] I have tested all added content and changes.
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
I'm dead

**Changelog**
🆑 
- add: Vulpkanins and Felinids can wag (and stop wagging) their tail on command! (Uses the EE system!)
- add: Ported EE Vulpkanin screams! **AAAAAAAA!**

2024-11-20 06:39 UTC, Monotheonist commented
Massive W for vulp players.

2024-11-20 22:13 UTC, deltanedas requested changes

2024-11-20 22:13 UTC, deltanedas commented on Content.Server/Wagging/WaggingSystem.cs
> +        wagging.Wagging = !wagging.Wagging; // Einstein-Engines
comment not needed

2024-11-20 22:13 UTC, deltanedas commented on Resources/Prototypes/Actions/types.yml
> +  noSpawn: true
remove

2024-11-20 22:13 UTC, deltanedas commented on Resources/Prototypes/Actions/types.yml
> +      icon: { sprite:  Einstein-Engines/Interface/Actions/wagging.rsi, state: icon } # Einstein-Engine
remove extra spare after sprite:

2024-11-20 22:13 UTC, deltanedas commented on Resources/Prototypes/Actions/types.yml
> +      iconOn: { sprite: Einstein-Engines/Interface/Actions/wagging.rsi, state: icon-on } # Einstein-Engine
above

2024-11-20 22:18 UTC, Unkn0wnGh0st333 commented on Resources/Prototypes/Actions/types.yml
> +  noSpawn: true
woops missed one

2024-11-20 22:18 UTC, Unkn0wnGh0st333 commented on Resources/Prototypes/Actions/types.yml
> +      icon: { sprite:  Einstein-Engines/Interface/Actions/wagging.rsi, state: icon } # Einstein-Engine
my b

2024-11-20 22:19 UTC, Unkn0wnGh0st333 commented on Resources/Prototypes/Actions/types.yml
> +      iconOn: { sprite: Einstein-Engines/Interface/Actions/wagging.rsi, state: icon-on } # Einstein-Engine
there is no extra one on that one like the first it seems

2024-11-21 00:18 UTC, sleepyyapril commented
I wonder what commit with message Tail Wagging (Real) does. Or Tail Wagging (Real)? Maybe Tail Wagging (Real) too?

Anyways how does that happen?

2024-11-29 16:48 UTC, Unkn0wnGh0st333 commented
> Massive W for vulp players. Also, on the topic of the cat ears / tails, I'm pretty sure the reasoning there was because they fit on felinids, you should probably make sure they work with vulps as well. Otherwise I can envision some real cursed vulps.

I know but this was a week ago but to dismiss your concern. Look at a felinids, look at its pixels, realize it's just a shrunken human sprite, horror takes over your body, realize the tails were originally sprited to fit on humans. Yes the tails fit just fine lol

2024-12-18 21:18 UTC, Lyndomen commented
Direction review, 24 hours

2024-12-19 20:52 UTC, Lyndomen approved these changes, later dismissed
Sprites look great, thank you

2025-01-16 17:37 UTC, Lyndomen submitted a review, later dismissed

2025-02-06 15:59 UTC, Lyndomen commented
is this tail wagging real or fake

2025-02-23 16:32 UTC, deltanedas requested changes

2025-02-23 16:32 UTC, deltanedas commented on Resources/Locale/en-US/deltav/markings/vulpkanin.ftl
> +marking-VulpTailCorgi-corgi = Crogi tail
crogi

2025-02-23 16:32 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Mobs/Customization/Markings/vulpkanin.yml
> +  speciesRestriction: []
lizards can use this???

2025-02-23 16:32 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Voice/speech_emote_sounds.yml
> +      collection: VulpkaninScreams # Einstein-Engines
replace FemaleScreams too

2025-02-23 16:32 UTC, deltanedas commented on Resources/Prototypes/Nyanotrasen/Entities/Mobs/Customization/Markings/felinid.yml
> +# Felinid Tail Wag (DeltaV)
put them in deltav folder pro

2025-02-23 16:32 UTC, deltanedas commented on Resources/Prototypes/Nyanotrasen/Entities/Mobs/Customization/Markings/felinid.yml
> +  speciesRestriction: [Felinid, Vulpkanin] #Delta-V - Vulp Cat tails :troll:
for all these comments use `# DeltaV - `

2025-03-08 13:03 UTC, Unkn0wnGh0st333 commented on Resources/Locale/en-US/deltav/markings/vulpkanin.ftl
> +marking-VulpTailCorgi-corgi = Crogi tail
![image](https://github.com/user-attachments/assets/c2ed04fc-1602-41df-884f-100de2592d19)


I have no idea

2025-03-08 13:04 UTC, Unkn0wnGh0st333 commented on Resources/Prototypes/DeltaV/Entities/Mobs/Customization/Markings/vulpkanin.yml
> +  speciesRestriction: []
No, that makes it so NO one can use it.

2025-03-08 13:05 UTC, Unkn0wnGh0st333 commented on Resources/Prototypes/DeltaV/Voice/speech_emote_sounds.yml
> +      collection: VulpkaninScreams # Einstein-Engines
![image](https://github.com/user-attachments/assets/61952fb2-66ce-4207-8af7-b77e039f5d51)

I must have fixed all this ages ago

2025-03-08 13:15 UTC, Unkn0wnGh0st333 commented on Resources/Prototypes/DeltaV/Entities/Mobs/Customization/Markings/vulpkanin.yml
> +  speciesRestriction: []
![image](https://github.com/user-attachments/assets/16fc3b3b-e935-4e6b-b671-ea7333e9c14b)

2025-03-08 15:51 UTC, deltanedas requested changes

2025-03-08 15:51 UTC, deltanedas commented on Resources/Prototypes/Nyanotrasen/Entities/Mobs/Customization/Markings/felinid.yml
> +  speciesRestriction: [Felinid, Vulpkanin] #DeltaV - Vulp Cat ears :troll:
dont need deltav commands in nyano files

2025-03-08 15:51 UTC, deltanedas commented on Resources/Prototypes/_DV/SoundCollections/vulpkanin.yml
> +  - /Audio/Einstein-Engines/Voice/Vulpkanin/vulpscream5.ogg
if its from EE put it in _EE

2025-04-08 10:55 UTC, Screampuff commented
Current status on this one?

2025-04-08 11:04 UTC, Toby222 requested changes

2025-04-08 11:04 UTC, Toby222 commented on Resources/Audio/Einstein-Engines/Voice/Vulpkanin/attritbutions.yml
> +  license: https://www.soundsnap.com/licence
`3(g) [You may not] [c]opy all or a significant part of the Sounds on the Soundsnap website for the purpose of redistributing the Sounds “as is”.`
Does that qualify here?

2025-04-08 11:04 UTC, Toby222 commented on Resources/Prototypes/_DV/Entities/Mobs/Customization/Markings/vulpkanin.yml
> -      state: vulp_wag-tip #fade
Stay consistent with indentation

2025-06-23 07:04 UTC, closed without merging