Hardsuits now block defibulators
DeltaV-Station/Delta-v pull request #2251
Opened 2024-11-21 05:09 UTC by beck-thompson

## About the PR

Title! Defibs now are blocked by hardsuits.

## Why / Balance

I asked in the discord, majority of people seemed to want it. It makes sense and will make medical have to think about defibbing fully armored security.

Also, requires:
https://github.com/space-wizards/space-station-14/pull/31147
To be merged before it works!

## Media

todo

## Requirements

- [ ] I have tested all added content and changes.
- [ ] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Hardsuits now block defibrillators

2024-11-21 05:12 UTC, BlitzTheSquishy commented
Gonna need to make sure that softsuits, (Prisoner, Emergancy, Basic, Clown, Mime, Syndicate) dont, and yes clown and mime are softsuits, not hardsuits (despite their name)

2024-11-21 05:13 UTC, Lyndomen commented
💯💯

2024-11-21 05:13 UTC, beck-thompson commented
> Gonna need to make sure that softsuits, (Prisoner, Emergancy, Basic, Clown, Mime, Syndicate) dont, and yes clown and mime are softsuits, not hardsuits (despite their name)

Sounds good, when the required PR actually gets merged I'll do more testing to make sure it works on the right things and stuff

2024-11-21 05:14 UTC, BlitzTheSquishy commented
> > Gonna need to make sure that softsuits, (Prisoner, Emergancy, Basic, Clown, Mime, Syndicate) dont, and yes clown and mime are softsuits, not hardsuits (despite their name)
> 
> Sounds good, when the required PR actually gets merged I'll do more testing to make sure it works on the right things and stuff

Also currently where that's placed- it looks like EVERY outer slot item will block defib (would include vox tank harnesses i believe)

2024-11-21 05:15 UTC, beck-thompson commented
> also you should be testing it BEFORE it gets merged

How? I mean I guess I could like chery pick the required PR ahead of time but I personally don't think that's worth the effort. I mostly made this early so people could give their opinions. If people don't want it, then I wont bother putting the work in finding all the weird hardsuit edge cases

2024-11-21 05:17 UTC, BlitzTheSquishy commented
> > also you should be testing it BEFORE it gets merged
> 
> How? I mean I guess I could like chery pick the required PR ahead of time but I personally don't think that's worth the effort. I mostly made this early so people could give their opinions. If people don't want it, then I wont bother putting the work in finding all the weird hardsuit edge cases

pull the merge to your dev or make a dev enviro on wizden (which its already merged) and test there, cause we use similar stuff so

2024-11-21 08:29 UTC, MilonPL requested changes

2024-11-21 08:29 UTC, MilonPL commented on Content.Shared/DeltaV/BlockDefibrillator/BlockDefibrillatorComponent.cs
> +[RegisterComponent, NetworkedComponent]
access

2024-11-21 08:29 UTC, MilonPL commented on Content.Shared/DeltaV/BlockDefibrillator/BlockDefibrillatorComponent.cs
> +    public string OnBlockPopupMessage = "The defibrillator cannot find a pulse through the armor!";
locid + localization

2024-11-21 08:29 UTC, MilonPL commented on Content.Shared/DeltaV/BlockDefibrillator/BlockDefibrillatorSystem.cs
> +    [Dependency] private readonly SharedPopupSystem _popupSystem = default!;
just _popup

2024-11-21 08:29 UTC, MilonPL commented on Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
> +  - type: BlockDefibrillator // Delta-V
pro

2024-11-21 18:40 UTC, beck-thompson commented on Content.Shared/DeltaV/BlockDefibrillator/BlockDefibrillatorComponent.cs
> +[RegisterComponent, NetworkedComponent]
Add comments

2024-11-21 18:40 UTC, beck-thompson commented on Resources/Prototypes/Entities/Clothing/OuterClothing/base_clothingouter.yml
> +  - type: BlockDefibrillator // Delta-V
Remember to double check all the weird edge cases for hardsuits. There are a lot :(

2024-12-17 04:37 UTC, beck-thompson commented
This isn't too hard to fix but I have more interesting things I'd rather work on! Anyone feel free to copy / re-open this (The code isn't very good so I wouldn't recommend it but whatever 😆)

2024-12-17 04:37 UTC, closed without merging