Nerfed E-Shield
DeltaV-Station/Delta-v pull request #2252
Opened 2024-11-21 05:36 UTC by Radezolid

## About the PR
Modified values on the e-shield to make it a bit less mindless.

## Why / Balance
Why? Because Lyndo was too lazy to PR it so I did it for them.

Balance:
With the upcoming devastator RPG replacement + most of the crew weapons being lasers it's kinda a mindless buy to nullify those weapons.

## Technical details
YAML changes.

## Media

https://github.com/user-attachments/assets/400254dd-84d9-4b4f-957c-8c31394c0497

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None.

**Changelog**

:cl:
- tweak: The E-Shield now has a 50% reflect chance but it's durability is 3 times bigger.

2024-11-21 05:37 UTC, Lyndomen commented
And resistances went up. Also it wasn't that I'm lazy, I'm just in bed and webedits are now illegal

2024-11-21 05:39 UTC, Radezolid commented
> And resistances went up. Also it wasn't that I'm lazy, I'm just in bed and webedits are now illegal

You lazy :3

2024-11-21 19:06 UTC, CybersunOperative commented
Hi. Hello. Direction here. This has probably been a long time coming nerf for the energy shield. The trade off for the reduction in reflect being additional shield HP seems fine enough. A competent operator will get more out of their shield than someone just mindlessly tanking bullets now, which is ideal.

Direction approves :3

2024-11-21 19:11 UTC, Avalon-Proto commented
I still feel 50 is too big of a nerf- for a 10tc items that costs more than the weapon you pair with it in most cases, I feel a reduction to the 65-75 area is more reasonable. 95 was ridiculous yes, but cutting it down to nearly half of what it once was makes this item too expensive to be worth it

2024-12-21 07:20 UTC, deltanedas requested changes

2024-12-21 07:20 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Shields/shields.yml
> +      reflectProb: 0.5
all of these need deltav comments

2024-12-21 10:28 UTC, Radezolid commented
Half asleep comments lmao

2024-12-21 11:02 UTC, deltanedas approved these changes
inb4 price reduction pr now that its a meme

2024-12-21 11:02 UTC, merged

2024-12-22 15:38 UTC, jink23 commented
> Hi. Hello. Direction here. This has probably been a long time coming nerf for the energy shield. The trade off for the reduction in reflect being additional shield HP seems fine enough. A competent operator will get more out of their shield **than someone just mindlessly tanking bullets** now, which is ideal.
> 
> Direction approves :3

You mean, Doing what a shield is supposed to do, block damage. If most the station is using lasers and the item costs 10tc it should be 'mindlessly blocking bullets' because that's what a shield SHOULD be doing having it be more durable isn't really much of a tradeoff