Sprite For Vulps 101
DeltaV-Station/Delta-v pull request #2254
Opened 2024-11-21 15:14 UTC by Kr8art

## About the PR
Added a custom sprite for Lyndo's "Vulpkanin 101" book. 

## Why / Balance
Questionable life choices. 

## Technical details
- Added a book.rsi to DeltaV textures
- Created a new icon for the book
- Changed the books.yml of "Vulpkanin 101" to adopt the new icon

## Media
![image](https://github.com/user-attachments/assets/da940d30-e160-464f-94c2-44ad7966582a)

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
n/a

**Changelog**
:cl:
- tweak: Vulpkanin 101 now has a custom icon!

2024-11-21 15:19 UTC, Lyndomen commented
hell yeah

2024-11-21 18:50 UTC, deltanedas requested changes

2024-11-21 18:50 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Objects/Misc/books.yml
> +    - state: icon_kiss
add the `sprite: DeltaV/...` to this layer so you dont have to duplicate the other states

2024-11-21 18:50 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Objects/Misc/books.yml
> +    sprite: DeltaV/Objects/Misc/books.rsi
undo

2024-11-21 18:50 UTC, deltanedas commented on Resources/Textures/DeltaV/Objects/Misc/books.rsi/meta.json
> +      "name": "cover_strong"
remove other states and update copyright

2024-11-22 14:13 UTC, Kr8art commented
Addressed requested changes!

2024-11-22 22:51 UTC, deltanedas approved these changes

2024-11-22 22:51 UTC, merged

2024-11-22 22:51 UTC, deltanedas commented
youre a secmain vulp arent you, you like arresting tiders