Add soretizone to starting kit of chronically ill characters
DeltaV-Station/Delta-v pull request #2259
Opened 2024-11-22 01:46 UTC by pontaoski

## About the PR & Why

At the start of a shift, it's quite frequent that chemists are both unable to and too busy to make painkillers for chronically ill characters for quite some time, leaving them to rot at the start of the round.

This remedies that by giving them 5 pills of soretizone when they spawn in, so that they have a buffer before they need to consult the ship's chemist.

## Technical details
- add soretizone pill entity
- add soretizone pill canister entity
- set soretizone pill canister as the trait gear of chronic pain trait

## Media
![grafik](https://github.com/user-attachments/assets/f6c362c3-47f9-4b73-ab74-c5f1157d8120)

## Requirements
- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- add: Characters with the "chronic pain" trait now spawn with 5 pills of 10u soretizone to tide them over at the start of a shift

2024-11-22 01:56 UTC, Lyndomen commented
awesome, this is great!

2024-11-22 02:43 UTC, deltanedas requested changes

2024-11-22 02:43 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Objects/Specific/Medical/healing.yml
> +  name: pill
remove this line

2024-11-22 02:43 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Objects/Specific/Medical/healing.yml
> +  suffix: Soretizone 10u
move this line below id

2024-11-22 02:43 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Objects/Specific/Medical/healing.yml
> +  name: pill canister
remove

2024-11-22 02:46 UTC, pontaoski commented
yaml has been reformatted to requests

2024-11-22 03:04 UTC, Radezolid commented
You can ask for a review by pressing the button at the top right.
![image](https://github.com/user-attachments/assets/e84b0745-ec31-41e3-9f9f-89909a3c21db)
Should appear next to the request changes icon

2024-11-22 22:56 UTC, MilonPL approved these changes

2024-11-24 03:47 UTC, deltanedas approved these changes

2024-11-24 03:47 UTC, merged