Allows secborgs to use the L6 module
DeltaV-Station/Delta-v pull request #2262
Opened 2024-11-22 04:29 UTC by Stop-Signs

## About the PR
title explain it all

## Why / Balance
the module can only be obtained as rare expedition loot or from looting a fallen syndie borg, i feel like our secborgs should be able to receive said upgrade on rare occasion and it shouldnt lead to too many issues
## Technical details

## Media

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-11-22 04:34 UTC, Avalon-Proto commented
Ultra rare item that gives a borg a mega power boost, sounds like fun. Just hope its not emagged

2024-11-22 09:34 UTC, deltanedas commented
infinite L6 for the shadow factory yummy

2024-11-26 17:31 UTC, MilonPL requested changes

2024-11-26 17:31 UTC, MilonPL commented on Resources/Prototypes/Entities/Objects/Specific/Robotics/borg_modules.yml
> +        - BorgModuleSecurity # DeltaV allows secborgs to use
comment on first line

2024-11-29 16:24 UTC, therealDLondon commented
Im going to be real.
Im very much on the page of denying this one, I dont like  the idea of secborgs with L6s, especially with the laws being the way they are rn

2024-11-29 17:11 UTC, closed without merging