Delta-V Specific Posters!
DeltaV-Station/Delta-v pull request #2303
Opened 2024-11-27 21:38 UTC by IAmNotGray

## About the PR
Adds seven new posters for mappers to use in their maps.
## Why / Balance
I'd like to see more Delta-specific posters. Also wanted to make posters for the game, anyway... Credits to JustAnOrange for making some of the posters featured in this PR!

## Technical details
Posters + meta files and the like
Hassled for hours trying to get it to work.
Random Spawns included

## Media
![dangernana](https://github.com/user-attachments/assets/4143c7cc-8fb4-45f7-8ffb-a08af16c87fa)
![getwork](https://github.com/user-attachments/assets/5981d8af-1f08-4b9f-99f3-52579b42c5a7)
![syndicateandyou](https://github.com/user-attachments/assets/e25d01b2-025a-445f-845e-2fd3fae015c1)
![nanotrasenandyou](https://github.com/user-attachments/assets/13e4de53-13f2-4825-8ee2-f9723f156e7f)
![nanotrasenwork](https://github.com/user-attachments/assets/187284d8-8905-4845-b347-7e1d717cb011)
![syndicatework](https://github.com/user-attachments/assets/fcbac183-7712-442d-b4e6-b1b5e421c73a)
![l6poster](https://github.com/user-attachments/assets/61b15523-55e0-46eb-a613-acac6a2aa620)

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
Posters..?-

**Changelog**

2024-11-27 21:45 UTC, Kr8art commented
Very cool! Can't wait to slip on a banana peel while the nearby clown gleefully spam-points at first poster.

2024-11-27 21:46 UTC, Unkn0wnGh0st333 commented on Resources/Prototypes/DeltaV/Entities/Structures/Wallmounts/Signs/posters.yml
> +  description: "The notorious L6 light machine gun. Produced by Donk Co., This monster of a weapon is capable of cutting down dozens of people in mere moments. And to think this company also makes pa
```suggestion
  description: "The notorious L6 light machine gun. Produced by Waffle Co., This monster of a weapon is capable of cutting down dozens of people in mere moments. And to think this company also makes party supplies!"
```

2024-11-27 21:47 UTC, IAmNotGray commented on Resources/Prototypes/DeltaV/Entities/Structures/Wallmounts/Signs/posters.yml
> +  description: "The notorious L6 light machine gun. Produced by Donk Co., This monster of a weapon is capable of cutting down dozens of people in mere moments. And to think this company also makes pa
Insert Nerd Emoji Here

2024-11-27 21:47 UTC, Unkn0wnGh0st333 commented on Resources/Prototypes/DeltaV/Entities/Structures/Wallmounts/Signs/posters.yml
> +  description: "The notorious L6 light machine gun. Produced by Donk Co., This monster of a weapon is capable of cutting down dozens of people in mere moments. And to think this company also makes pa
:trollface:

2024-11-27 21:49 UTC, deltanedas requested changes
add these to legit and contraband spawners

2024-11-27 21:49 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Structures/Wallmounts/Signs/posters.yml
> +    state: dangernana
add newline to end of file

2024-11-27 21:49 UTC, deltanedas commented on Resources/Textures/DeltaV/Structures/Wallmounts/Posters/grayposters.rsi/meta.json
> +		{
indents fucked

2024-11-27 22:08 UTC, IAmNotGray commented
I forgot to remove the test.rsi folder before making the PR. I'm so good at this.

2024-11-27 22:13 UTC, deltanedas commented
almost every line of that file has mixed tabs/spaces

2024-11-27 22:20 UTC, IAmNotGray commented
> almost every line of that file has mixed tabs/spaces
You can tell how good at this I am.

2024-11-27 22:40 UTC, deltanedas requested changes

2024-11-27 22:40 UTC, deltanedas commented on Resources/Textures/DeltaV/Structures/Wallmounts/Posters/grayposters.rsi/meta.json
> +        },
last one

2024-11-27 22:40 UTC, deltanedas commented on Resources/Textures/DeltaV/Structures/Wallmounts/Posters/grayposters.rsi/meta.json
> +}
newline at end of file

2024-11-27 23:05 UTC, IAmNotGray commented
Okay hopefully that's all I need to fix-

2024-11-30 19:39 UTC, IAmNotGray commented
Anything on this PR?

2024-12-07 00:47 UTC, Monotheonist commented
These look banger, and I think they're cool! And all tests have passed so all it needs is someone to look at it and say yes, pretty much.

2024-12-08 03:16 UTC, deltanedas requested changes

2024-12-08 03:16 UTC, deltanedas commented on Resources/Textures/DeltaV/Structures/Wallmounts/Posters/grayposters.rsi/meta.json
> +{
this file is still using tab indents instead of 4 spaces

2024-12-13 12:52 UTC, deltanedas approved these changes

2024-12-13 12:52 UTC, merged