make doorjack 2 tc
DeltaV-Station/Delta-v pull request #2305
Opened 2024-11-28 07:46 UTC by deltanedas

## About the PR
2tc and 1 on discount

## Why / Balance
jaws of life and susbox:
- arent controlled items
- have no charges
- make much less suspicious sounds
- are 2 tc

currently if you hear a door getting emagged you first think ninja because of how rare doorjack is from being outclassed, now it has a good chance of being seen again

at 2 tc doorjack is now competitive, do you want the sustainability of prying doors open or the quick burst of 3 doors in succession

## Technical details
no

## Media

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
no

**Changelog**
:cl:
- tweak: The doorjack now costs 2 TC instead of 6.

2024-11-28 08:05 UTC, therealDLondon commented
How would you feel about 4TC with 2TC at discount?

2024-11-28 08:15 UTC, deltanedas commented
still very little reason to do it when you can get:
- a radio
- 2 red soaps
- a susbox to complement jaws and vice versa
- pistol mags

its rare that you need a quick burst of 3 doors, still dont think people would use it when you can get both generally superior options for the same price

2024-11-28 08:22 UTC, JustTNE commented
I feel like the doorjack should be a little more expensive. It has the ability to keep doors permanently opened until manually fixed, which is an advantage the jaws don't have.

2024-11-28 08:25 UTC, deltanedas commented
with AI that wont matter since it can instantly unbolt them

2024-11-28 08:26 UTC, JustTNE commented
That won't fix the access on the door being problem, or has that behavior changed?

2024-11-28 08:33 UTC, JustTNE commented
Also, I do believe the doorjack is a smaller item than the jaws, which makes it easier to store in a storage implant. That is probably another reason it should be a little more expensive than 2 tc.

2024-11-28 08:34 UTC, deltanedas commented
no but ai can then bolt it closed or shock you because you didnt buy the insuls

2024-11-28 08:36 UTC, ThataKat commented
Also need to consider skill and speed. Susbox can effectively do the same, but a lot of players are bad at hacking, etc. Both susbox and jaws take significant time as well. AO is much quicker and easier to use. Price reduction isn't a bad idea but I think the 4tc suggestion is more reasonable.

2024-11-28 08:47 UTC, Kr8art commented
I think two TC is honestly fine. The doorjack has the advantage of speed, but is limited in charges, whereas the jaws take longer at unlimited charges. 

Personally I do not consider the doors staying open to be always advantageous. If the doorjack is for example used to quickly burst into the bridge to get a steal objective, it's very likely that the alert level gets raised once people discover the jacked doors.

2025-01-06 05:14 UTC, Lyndomen requested changes

2025-01-06 05:14 UTC, Lyndomen commented on Resources/Prototypes/_DV/Catalog/uplink_catalog.yml
> +    Telecrystal: 2
4

2025-01-06 05:14 UTC, Lyndomen commented on Resources/Prototypes/_DV/Catalog/uplink_catalog.yml
> +    Telecrystal: 1
2

2025-01-06 05:15 UTC, Lyndomen commented
then good to go

2025-01-06 05:35 UTC, merged