Add a foam sabre
DeltaV-Station/Delta-v pull request #2310
Opened 2024-11-28 17:57 UTC by Radezolid

## About the PR
Adds a foam sabre, it can spawn in maints and mimes can select to spawn with it.
Also adds a sharp foam sabre, only way to obtain is through the syndicate uplink.

## Why / Balance
Fun things for people to play + a stealth weapon, it's damage is equal to the cane blade, same attack rate too.

## Technical details
Added YAMLs, sprites and locales.

## Media

![image](https://github.com/user-attachments/assets/c063f3a0-1255-43c9-89ba-fb61f85ee969)
![image](https://github.com/user-attachments/assets/49095b07-31b6-4fc1-b229-0de7d6e748dd)
![image](https://github.com/user-attachments/assets/a0eb38b6-240f-4732-95c9-cd2133cb18dc)
![image](https://github.com/user-attachments/assets/65ed10fc-36b7-4893-b65a-00f7d3b75a74)

Evil version:
![image](https://github.com/user-attachments/assets/99ac6ca3-9d15-4342-853a-f2cce7473f84)
![image](https://github.com/user-attachments/assets/e428405f-369c-4156-aaf0-4c5f0d8db567)
![image](https://github.com/user-attachments/assets/851a839d-57d0-4861-a991-541f78684b05)

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None.

**Changelog**

:cl:
- add: Added foam sabres! They may appear in maintenance lockers and mimes can select to spawn with it in the loadout selection.
- add: Added a sharp version of the foam sabre toy, purchasable from the syndicate uplink at 6 TC with a possible discount to 4 TC.

2024-12-01 02:30 UTC, CybersunOperative commented
Hi. Hello. Val here. The other curators that weighed in on this said they liked it. I do have some minor nitpicks though.
I would highly recommend removing the "It looks sturdier than most." from the evil foam saber description, as that immediately gives it away as le evil valid toy. 
You also have an extra period after "A real foam sheathe to cosplay as the captain!" 
Otherwise, it seems good. I like the 1% chance for the toy to reflect. Generally a very cute addition to the foam weapon set.

2024-12-01 03:31 UTC, Radezolid commented
> I would highly recommend removing the "It looks sturdier than most." from the evil foam saber description, as that immediately gives it away as le evil valid toy.
That was kind of my intention, a foam weapon being able to do 14 slash kinda feels like it needs to be able to be noticed somehow, it isn't like a stealth pen that it actually hides how it works, the evil version is just a blade with the foam on top as disguise, but sure, I don't really mind changing that.

2024-12-01 08:13 UTC, deltanedas commented
description doesnt matter since it has a damage examine compared to foam sabre which doesnt

2024-12-01 11:07 UTC, Radezolid commented
Yup, it was flavor text to give a reason for the people to do the "this ones does damage, evil."

2024-12-01 12:17 UTC, deltanedas requested changes

2024-12-01 12:17 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Melee/foam_blade.yml
> +  description: Cosplay as a captain and command your group of friends!. It looks sturdier than usual.
!. -> !

2024-12-01 12:17 UTC, deltanedas commented on Resources/Textures/DeltaV/Clothing/Belt/foamsheath.rsi/meta.json
> +}
keep indent consistent at 4 spaces (the amazing fun time of not just using tabs like a sane project)

2024-12-01 13:41 UTC, Radezolid commented on Resources/Textures/DeltaV/Clothing/Belt/foamsheath.rsi/meta.json
> +}
Last time I copy paste a meta.json
Will fix once I'm able.

2024-12-01 14:40 UTC, deltanedas submitted a review, later dismissed

2024-12-06 05:21 UTC, Monotheonist commented
Make sure to add it to the sword mail in `mail.yml.` Otherwise no one's gonna get the foam sabre in the mail

2024-12-06 12:28 UTC, Radezolid commented
Hadn't thought about giving it on the mail, thanks for the idea

2024-12-06 19:16 UTC, deltanedas approved these changes

2024-12-06 19:33 UTC, merged