Discord reply system
DeltaV-Station/Delta-v pull request #2315
Opened 2024-11-29 02:03 UTC by sleepyyapril

## About the PR

This ports https://github.com/new-frontiers-14/frontier-station-14/pull/2283 which allows admins to respond to AHelps while on discord through threads.

## Why / Balance

Not needing to be in-game to handle ahelps is a benefit for all admins.

## Technical details

This PR requires:
1. Something that can handle the discord side, see original PR for details. You can also use my [RedBot cog](https://github.com/sleepyyapril/april-cogs), if Delta-v uses RedBot.
2. A set admin.api_token CVar value to use on the discord side.
3. CVar status.enabled being true

This PR changes the way the BwoinkSystem works to allow for custom URLs instead of just an id and a token for webhooks, as well as adding an admin API HTTP POST method under ``/admin/actions/send_bwoink``.

## Media

![image](https://github.com/user-attachments/assets/65edeb13-fe31-4e38-a151-0d1203f20f81)

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None

**Changelog**

cl:
ADMIN:
- add: Added the ability to reply to AHelps from discord.

2024-11-30 04:22 UTC, sleepyyapril commented
Proof of everything working added.

2024-11-30 04:22 UTC, sleepyyapril commented
Errors are unrelated, too.

2024-12-03 05:50 UTC, Colin-Tel commented
Looks awesome!

2024-12-04 14:03 UTC, deltanedas requested changes
theres more but overall theres a stupid amount of changes that it makes any upstream changes to this system a nightmare to manage, should be done upstream

2024-12-04 14:03 UTC, deltanedas commented on Content.Server/Administration/ServerApi.cs
> +using Content.Server.Administration.Managers;
comments on all changed upstream files lines

2024-12-04 14:03 UTC, deltanedas commented on Content.Server/Administration/ServerApi.cs
> +using Content.Shared.Administration;
.

2024-12-04 14:03 UTC, deltanedas commented on Content.Server/Administration/ServerApi.cs
> +
should be in a frontier or deltav file

2024-12-04 14:03 UTC, deltanedas commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +        [GeneratedRegex(@"^https://(?:(?:canary|ptb)\.)?discord\.com/api/webhooks/(\d+)/((?!.*/).*)$")]
comment

2024-12-04 14:03 UTC, deltanedas commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +        [Dependency] private readonly IServerPreferencesManager _preferencesManager = default!;
comment

2024-12-04 14:03 UTC, deltanedas commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +using Content.Server.Preferences.Managers;
comment

2024-12-04 14:03 UTC, deltanedas commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +using Pidgin.Configuration;
?????? what

2024-12-04 14:03 UTC, deltanedas commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +            _onCallData = await GetWebhookData(url);
comment

2024-12-05 08:16 UTC, sleepyyapril commented
> theres more but overall theres a stupid amount of changes that it makes any upstream changes to this system a nightmare to manage, should be done upstream

Incapable of doing upstream, it's AGPL from frontier.

2024-12-05 08:17 UTC, sleepyyapril commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +            _onCallData = await GetWebhookData(url);
What? Changes were made to allow a custom URL, not just discord.

2024-12-05 08:17 UTC, sleepyyapril commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +using Pidgin.Configuration;
No clue either.

2024-12-06 08:28 UTC, sleepyyapril commented
@deltanedas @MilonPL i fixed :D

2025-01-02 22:10 UTC, deltanedas requested changes

2025-01-02 22:10 UTC, deltanedas commented on Content.Shared/CCVar/CCVars.Admin.cs
move these to the deltav cvars file

2025-01-02 22:10 UTC, deltanedas commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +
should be in _NF

2025-01-02 22:10 UTC, deltanedas commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +            var config = IoCManager.Resolve<IConfigurationManager>();
frontier comment

2025-01-02 22:10 UTC, deltanedas commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +        private void OnBwoinkInternal(BwoinkParams bwoinkParams)
assign variables to the fields to avoid conflicts like `var message = bwoinkParams.Message;` etc

2025-01-02 22:10 UTC, deltanedas commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +                    payload = GeneratePayload(message.ToString(), existingEmbed.Username, userId, existingEmbed.CharacterName);
comment

2025-01-02 22:10 UTC, deltanedas commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +                    $"Webhook returned bad status code when trying to get webhook data (perhaps the webhook URL is invalid?): {response.StatusCode}\nResponse: {content}");
untouch this line

2025-01-02 22:10 UTC, deltanedas commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +        private async Task<WebhookData?> GetWebhookData(string url)
comment

2025-01-02 22:10 UTC, deltanedas commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +            var response = await _httpClient.GetAsync(url);
comment

2025-01-02 22:10 UTC, deltanedas commented on Content.Server/Administration/ServerApi.cs
> +
endregion here

2025-01-02 22:10 UTC, deltanedas commented on Content.Server/Administration/ServerApi.cs
> +using Content.Server._NF.Administration;
comment

2025-01-04 00:14 UTC, sleepyyapril commented on Content.Server/Administration/Systems/BwoinkSystem.cs
> +            var config = IoCManager.Resolve<IConfigurationManager>();
removed

2025-01-04 00:17 UTC, sleepyyapril commented on Content.Server/Administration/ServerApi.cs
> +
unable, indent failure

2025-01-04 00:28 UTC, deltanedas approved these changes

2025-01-04 00:31 UTC, merged