Un-Overtunes CHIMP (still overall buff)
DeltaV-Station/Delta-v pull request #2316
Opened 2024-11-29 09:00 UTC by BlitzTheSquishy

## About the PR

Reduced the Chimp down 6 points of damage

## Why / Balance

having the CHIMP be 30 damage with omega particles allows it to 2 shot diona, and nearly 3 shot moths, while 4 shotting everyone, with 24 it reduces to 5 instead, diona probably still easily 2 shot and moth a more clean 4.

Largely due to the TC cost of the experimental upgrade (which is rather cheap for its damage output) this should  bring it more in line with how other syndicate weapons are done

which is generally *slightly better* than weapons security can access.

## Technical details

## Media

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-11-29 21:05 UTC, sheepism1 commented
the CHIMP upgr chip is NOT a weapon on its own and PAINFULLY OBVIOUS

2024-11-29 21:37 UTC, deltanedas commented
iirc its cheaper to emag a protolathe and mass produce actual lasers, this should have a niche as a very hard hitting upgrade

2024-11-29 21:43 UTC, Avalon-Proto commented
> iirc its cheaper to emag a protolathe and mass produce actual lasers, this should have a niche as a very hard hitting upgrade

It's either cheaper or same price to Emag a protolathe yeah. But by emagging a protolathe you can now get a porta charger and a 2nd chimp. Now you have 2 chimps you swap in the charger all the time to keep the fight up

2024-11-30 02:08 UTC, sheepism1 commented
Simple easier strategy:

Weaponised laser manipulation (0tc)

Emag (like 4 or 6 idk)

2 lasers and a port recharger (bribe cargo)

Get silly with it

2024-11-30 04:31 UTC, Lyndomen commented
Imo diona being 2 shot is a diona problem too, not really a weapon problem. If anything I would have lived to see a ROF decrease over damage decrease

2024-12-06 00:01 UTC, BlitzTheSquishy commented
> > iirc its cheaper to emag a protolathe and mass produce actual lasers, this should have a niche as a very hard hitting upgrade
> 
> It's either cheaper or same price to Emag a protolathe yeah. But by emagging a protolathe you can now get a porta charger and a 2nd chimp. Now you have 2 chimps you swap in the charger all the time to keep the fight up

this is also generally cheaper than the other method

2024-12-08 20:37 UTC, Lyndomen commented
Direction taking this in for review, eta 3 days probably

2025-01-02 22:11 UTC, deltanedas commented
@Lyndomen true

2025-01-02 22:14 UTC, Avalon-Proto commented
I'll be honest even with the mega damage buff I've *rarely* seen this thing in use just because even if it is a syndie energy weapon. It's just. Not used. Due to the fact it's super niche

2025-01-05 05:45 UTC, Lyndomen commented
damn i had feedback and consensus but fell asleep

2025-01-05 06:17 UTC, Lyndomen requested changes
Damage is fine as is . Fairly mediocre ttk already at 2.66 secs or something. the bullet travel times are also miserably slow- hitting 4 shots is hard

2025-01-07 15:10 UTC, closed without merging