Modify clown and mime sexy masks and add them to the autodrobe
DeltaV-Station/Delta-v pull request #2346
Opened 2024-12-02 19:27 UTC by Radezolid

## About the PR
Someone requested this to be done and was simple enough.

## Why / Balance
More content + less EMAG locked clothing.

## Technical details

YAML changes.

## Media
![image](https://github.com/user-attachments/assets/0f9e5c5b-5783-4733-ab5b-821f96db1577)

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

Hopefully nothing.

**Changelog**

:cl:
- tweak: The blushing mime mask and the purple clown mask can now be obtained at an autodrobe.

2024-12-02 19:41 UTC, deltanedas requested changes

2024-12-02 19:41 UTC, deltanedas commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/theater.yml
> +# End of DeltaV modifications.
for these have the comments indent at the same level

2024-12-03 12:44 UTC, deltanedas approved these changes

2024-12-03 14:11 UTC, Avalon-Proto commented
I feel like I should mention the fact the samurai dogi is actually decent armor

2024-12-03 14:13 UTC, deltanedas commented
this pr doesnt touch dogi

2024-12-03 14:18 UTC, Avalon-Proto commented
... I'm stupid I didn't see the Emag by the 2nd machine

2024-12-12 15:39 UTC, Lyndomen approved these changes

2024-12-12 15:57 UTC, merged