Update "snipers" to require weilding
DeltaV-Station/Delta-v pull request #2353
Opened 2024-12-03 23:06 UTC by BlitzTheSquishy

## About the PR

gave items in the "sniper" category wielding requirements (except flintlock)

## Why / Balance

Try firing a bolt-action with one hand to the efficiency of a spess man, you cant. Also shotguns already require wielding. So the Hristov definitely should given a bullet generally has more powder than behind it than shot

## Technical details

## Media

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: You now have to hold a rifle with TWO hands to operate it.

2024-12-03 23:09 UTC, Lyndomen commented
s-s-should this be upstream :3

2024-12-03 23:11 UTC, BlitzTheSquishy commented
> s-s-should this be upstream :3

2 changes here are for us specifically so not *entirely*

2024-12-03 23:27 UTC, deltanedas requested changes
comments should use - not |

2024-12-03 23:27 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
> +
erroneous newline

2024-12-04 01:19 UTC, MilonPL submitted a review, later dismissed

2024-12-04 01:19 UTC, MilonPL commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
> +  - type: GunRequiresWield # Delta-V - Firing a bolt action is.. incredibly unweildy with one hand.
just `DeltaV`, consistency, see contribution guidelines

2024-12-04 01:19 UTC, MilonPL commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
> +  - type: GunRequiresWield # Delta-V - Firing an antimateriel rifle is.. incredibly unweildy with one hand.
above

2024-12-04 01:19 UTC, MilonPL commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
> +  - type: GunRequiresWield # Delta-V - Firing a muzzle loader is.. incredibly unweildy with one hand.
above

2024-12-04 12:50 UTC, deltanedas approved these changes

2024-12-04 12:51 UTC, merged