change up and add ninja objectives
DeltaV-Station/Delta-v pull request #2359
Opened 2024-12-04 13:57 UTC by deltanedas

## About the PR
instead of guaranteed hyper metagameable 3 sabotage objectives:
- fixed objectives are now just doorjack, bomb and staying alive
- you randomly get assigned 2 of 3 sabotage objectives
- you can get up to 2 killing gibbing or stealing objectives
  stealing is for sentimental things like lucky bill, ian photobook, caps cloak

## Why / Balance
less metagaming but also less friendly ninjas that dont do anything except "pls my sabotage isnt actually sabotage no arresti"
will be cool seeing ninjas kill a target then go invis and run around with their corpse for everyone to see :trollface:

## Technical details
yml gaming

moved TeachLessonCondition to BaseTeachLessonObjective because it didnt have it pro

## Media
some rolls:
![01:51:09](https://github.com/user-attachments/assets/bdc33382-f932-4272-8981-2125343794c7)

![01:15:37](https://github.com/user-attachments/assets/c2bbf338-ab79-4113-a792-a9a8c45b4c76)

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
no

**Changelog**
:cl:
- tweak: Ninja objectives are now more random and they can be asked to steal things or kill people!

2024-12-04 14:14 UTC, Avalon-Proto commented
Do the spider clan use cyborgs in other servers?

2024-12-04 14:36 UTC, Lyndomen commented
Why teach lesson? Teach lesson is for kill once free greentext, not gib.

2024-12-04 14:43 UTC, Lyndomen commented
> Do the spider clan use cyborgs in other servers?

No but cool flavor

2024-12-04 14:51 UTC, deltanedas commented
> Why teach lesson? Teach lesson is for kill once free greentext, not gib.

yes thats intentional
you can rarely be told to gib a head (Execute X, Job)

2024-12-04 14:54 UTC, Lyndomen commented
Ok I see, gib or teach lesson objs ty. Brought it up for discussion, I like the idea a lot, feedback pending

2024-12-04 14:54 UTC, deltanedas commented
> Do the spider clan use cyborgs in other servers?

on ss13 you can convert borgs to be assault/saboteur/evil medi borgs as an objective, upstream didnt want it so i never added it when borgs got added

2024-12-04 19:14 UTC, Lyndomen commented
Direction big 👍

2024-12-04 19:14 UTC, Lyndomen approved these changes
Actual approval ops

2024-12-08 09:03 UTC, MilonPL requested changes

2024-12-08 09:03 UTC, MilonPL commented on Resources/Locale/en-US/deltav/objectives/conditions/steal-target-groups.ftl
> +steal-target-groups-captains-cloak = captain's cloak
what's up with these random spaces

2024-12-08 09:03 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Objectives/ninja.yml
> +  parent: [BaseNinjaObjective, BaseTeachLessonObjective]
spaces in inline lists `[ Option1, Option2 ]`

2024-12-08 09:03 UTC, MilonPL commented on Resources/Prototypes/DeltaV/Objectives/ninja.yml
> +  parent: [BaseNinjaObjective, BaseKillObjective]
.

2024-12-08 15:03 UTC, MilonPL approved these changes

2024-12-08 15:11 UTC, merged