Add the psychologist's locker
DeltaV-Station/Delta-v pull request #2372
Opened 2024-12-05 20:39 UTC by Radezolid

## About the PR
Adding a psychologist locker.

## Why / Balance
Fixes #928 
Requested a long time ago so, here it is. Also it's good for mapping.

## Technical details
YAML changes.

## Media
![image](https://github.com/user-attachments/assets/3494ac40-5398-4df1-b538-881797ff771e)
Contents:
![image](https://github.com/user-attachments/assets/0d733f9d-1609-4b2f-85be-c28c77657159)

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None.

**Changelog**
No CL.

2024-12-05 20:41 UTC, dvir001 commented
Move textures under DeltaV

2024-12-05 20:42 UTC, Radezolid commented
> Move textures under DeltaV

Tried, it didn't load, dunno why.

2024-12-06 01:20 UTC, MilonPL commented
That file is hardcoded iirc

2024-12-06 15:22 UTC, dvir001 commented
> That file is hardcoded iirc

How? just add
```
  - type: Sprite
    sprite: DeltaV/Structures/Storage/closet.rsi
```

eg: https://github.com/new-frontiers-14/frontier-station-14/blob/36f60e012572c44259dcdbb68a8f73e1de8f2649/Resources/Prototypes/_NF/Entities/Structures/Storage/Closets/Lockers/lockers.yml#L4

2024-12-06 18:21 UTC, Radezolid commented
I'm big dum dum. Thanks dvir.

2024-12-06 18:22 UTC, Radezolid commented
I'll add a base DeltaV locker in another PR while also moving the justice lockers to DeltaV, untouching upstream files.

2024-12-06 19:15 UTC, dvir001 commented on Resources/Prototypes/DeltaV/Entities/Structures/Storage/Closets/Lockers/lockers.yml
> +  - type: Appearance
Appearance coming from base

2024-12-06 19:54 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Structures/Storage/Closets/Lockers/lockers.yml
> +  - type: Appearance
True, thanks.

2024-12-06 21:09 UTC, deltanedas requested changes

2024-12-06 21:09 UTC, deltanedas commented on Resources/Textures/DeltaV/Structures/Storage/closet.rsi/meta.json
4 space indent for json

2024-12-07 02:32 UTC, Monotheonist commented
Gonna take the opportunity to point out you have the space to add a hole to the P, and make it look similar to the Pilot locker from the other PR, that's my main sprite nitpick with this PR: 
![393260805-e850eb27-f657-497f-b562-39d4f9ae36e4](https://github.com/user-attachments/assets/e3528c7a-edbc-4404-ab2d-d7be00fa39e4)

2024-12-07 03:02 UTC, Radezolid commented
tbh, i kinda like this one more, also it's different from the pilot one so more difference rather than just a color change

2024-12-07 03:27 UTC, Monotheonist commented
Fair enough, I'm just being the nerd that points that out.

2024-12-17 04:58 UTC, Lyndomen approved these changes
Role parity and fleshing out good

2024-12-17 12:33 UTC, deltanedas approved these changes

2024-12-17 12:33 UTC, merged