Change Overlord Law so no RDM
DeltaV-Station/Delta-v pull request #2375
Opened 2024-12-06 17:47 UTC by Lyndomen

## About the PR
makes it clear to not rdm crew. 

Any crew members who disobey the previous laws must be dealt with immediately, severely, and justly.
change to 
Any crew members who disobey the previous laws must be detained immediately and justly.

## Why / Balance
Overlord AI killed sec + command to prevent crew harm

## Technical details
yaml locale dont make me make this another law board pls 

## Media
no
## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
no

2024-12-06 17:49 UTC, Lyndomen commented
need direction or hga approval first

2024-12-06 18:05 UTC, Avalon-Proto commented
I mean, it all depends on the AI I suppose? Overlord is still not nearly as bad as Antimov. And can make for interesting rounds. And the fact it costs 20tc for syndies to get it, it should be able to crew-harm when deemed necessary. Seeing as how borgs can't cuff

2024-12-06 18:13 UTC, Lyndomen commented
> I mean, it all depends on the AI I suppose? Overlord is still not nearly as bad as Antimov. And can make for interesting rounds. And the fact it costs 20tc for syndies to get it, it should be able to crew-harm when deemed necessary. Seeing as how borgs can't cuff

RNG ion storm funni. 
Borgs can incapacitate under this law, as that is detainment.

2024-12-06 19:15 UTC, deltanedas commented
> RNG ion storm funni.

it can be removed from ion storm pool to allow separate balancing

2024-12-06 19:17 UTC, Lyndomen commented
> > RNG ion storm funni.
> 
> it can be removed from ion storm pool to allow separate balancing

We were kinda also frustrated that ion storm swaps all laws instead of just one of two. Might result in broken AI but that's the lotto

2024-12-06 19:23 UTC, Avalon-Proto commented
> > > RNG ion storm funni.
> > 
> > 
> > it can be removed from ion storm pool to allow separate balancing
> 
> We were kinda also frustrated that ion storm swaps all laws instead of just one of two. Might result in broken AI but that's the lotto

Ion storms laws just have a chance to swap all the laws. Or just make 1 corrupt. Or just remove a law or something. At least it's easy to fix just by slapping another law board into the console

2024-12-06 22:41 UTC, Radezolid commented
Bad idea imo, invalidates the whole 20 TC purchase. Plus the fix is literally using another board on the computer. It's on command and Mystagogue for not checking their laws more often.
With any silicon you're at risk of them being subverted, it's a boon when they work perfectly and a threat when they don't.

2024-12-07 22:59 UTC, Lyndomen commented
ok changed to "dealt with immedietely and justly" no severely. Thoughts?

2024-12-07 23:19 UTC, Radezolid commented
I like it

2024-12-07 23:22 UTC, Avalon-Proto commented
May still result in borgs being ordered to kill on occasion, but what's so bad about the occasional AI takeover

2024-12-07 23:48 UTC, Lyndomen commented
> May still result in borgs being ordered to kill on occasion, but what's so bad about the occasional AI takeover

yes thats totally fine imo, but i just wanted to make the "time to kill all sec" option a bit less obvious

2024-12-07 23:53 UTC, Avalon-Proto commented
> yes thats totally fine imo, but i just wanted to make the "time to kill all sec" option a bit less obvious

I mean once sec starts coming for the AI it becomes painfully obvious that the AI will need to kill sec. That's when you have your engi borgs make a room you can space wind their asses out of with a button press. But so long as the AI doesn't immediately order sec to be killed should be fine

2024-12-09 00:14 UTC, deltanedas commented on Resources/Locale/en-US/station-laws/laws.ftl
> +law-overlord-4 = Any crew members who disobey the previous laws must be dealt with immediately and justly.
make law-overlord-4-deltav and change the yml to use it

2024-12-11 08:56 UTC, deltanedas requested changes

2024-12-11 08:56 UTC, deltanedas commented on Resources/Prototypes/silicon-laws.yml
> +  lawString: law-overlord-4-delta
add ` # DeltaV`

2024-12-11 14:44 UTC, Lyndomen commented
how do i turn off rider obliterating whitespace this sucks

2024-12-11 18:12 UTC, Radezolid commented
I got no clue, tried everything for vscode too, i just edit it afterwards and do the commit lmao

2024-12-11 19:00 UTC, Lyndomen commented
> I got no clue, tried everything for vscode too, i just edit it afterwards and do the commit lmao

milon says use github desktop and only migrate changed lines

2024-12-12 01:20 UTC, deltanedas approved these changes

2024-12-13 09:12 UTC, merged