Randomizes the appearance of LP and Fugitives
DeltaV-Station/Delta-v pull request #2383
Opened 2024-12-07 02:22 UTC by Monotheonist

## About the PR

Allowed Fugitives to not be your character, and LP too. 1984, no more Okelte Valid. It turned out it was a one line change for both.
## Why / Balance

Me and Lyndo were not fans of how Fugitives spawn as your character that you already picked. This fixes it by spawning you as a random character that is the morphotype that you were, which helps with continuity from a story standpoint of a round, because it's weird to have John Tider die permanently from dying to a dragon and then have a dude that looks exactly like him be an escaped fugitive or an LP operator with a different name.
## Technical details

Adds ` - type: RandomHumanoidAppearance
        randomizeName: false` to the fugitive and therefore causes them to spawn with a random appearance of the morphotype you were.
## Media

![image](https://github.com/user-attachments/assets/dfb15768-5104-4522-91ab-8746d4af09be)
Technically is part of this because the player character was a harpy.
## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

Not a breaking change in the sense of technicality, but it might be difficult for Vox Players, since the morphotype is inherited, to which I say:
- You get masks and oxygen tanks by default in the Listening Post, just go into the closet and then breathe through your voice mask.
- I think leaving Fugitive like it is helps add to the survival factor, for them.

**Changelog**

No CL, no fun. I don't know if this warrants one because it's such a minor antag bugfix.

2024-12-07 03:40 UTC, Lyndomen commented
Direction review pending

2024-12-07 03:42 UTC, Lyndomen commented
also CL might be nice so people know it is a thing

2024-12-07 03:50 UTC, Monotheonist commented
Alright, yes CL, yes fun.

2024-12-07 13:29 UTC, deltanedas approved these changes, later dismissed

2024-12-07 23:01 UTC, Lyndomen requested changes
Direction requesting update: LPO to stay the player character. Our preference is that this would be toggleable by character preference, but thats a big wyci it so whatever.

2024-12-08 10:12 UTC, Monotheonist commented
That's legit, because the LPO is barely seen in rounds if at all, and it is less weird.

2024-12-08 10:26 UTC, Monotheonist commented
Pretty much ready to go if the tests don't fail.

2024-12-09 01:02 UTC, deltanedas approved these changes

2024-12-09 01:02 UTC, merged