Blukie Suit Resprite
DeltaV-Station/Delta-v pull request #2393
Opened 2024-12-08 06:57 UTC by Stop-Signs

## About the PR
Resprited blukie suits

## Why / Balance
the old sprites look kinda goody, this makes them more on-brand with NT

## Technical details
RSI and some yml
## Media
https://cdn.discordapp.com/attachments/968983104662409244/1315209789621534821/image.png?ex=67569411&is=67554291&hm=b650785b5648a4f169b773db357fa9e34c91640326968b99a23c44459dd8c24a&

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-12-08 23:24 UTC, Unkn0wnGh0st333 commented
Could go upstream too tbh... actually idk if upstream even has blukie

2024-12-09 00:58 UTC, deltanedas commented
nyano thing from RE, doesnt exist upstream

2024-12-13 03:51 UTC, Lyndomen approved these changes, later dismissed

2024-12-21 07:22 UTC, deltanedas requested changes
delete the old textures too

2024-12-21 07:22 UTC, deltanedas commented on Resources/Prototypes/Nyanotrasen/Entities/Clothing/Head/hardsuit-helmets.yml
> +    color: aquamarine
dont need comments its not from upstream and will never get updated elsewhere

2024-12-21 07:22 UTC, deltanedas commented on Resources/Prototypes/Nyanotrasen/Entities/Clothing/Head/hardsuit-helmets.yml
> +    sprite: DeltaV/Clothing/Head/ReverseEngineering/juggernaut.rsi
.

2024-12-21 07:22 UTC, deltanedas commented on Resources/Prototypes/Nyanotrasen/Entities/Clothing/OuterClothing/hardsuits.yml
> +    sprite:  DeltaV/Clothing/OuterClothing/ReverseEngineering/syndicate.rsi
.

2024-12-21 07:22 UTC, deltanedas commented on Resources/Prototypes/Nyanotrasen/Entities/Clothing/OuterClothing/hardsuits.yml
> +    sprite:  DeltaV/Clothing/OuterClothing/ReverseEngineering/juggernaut.rsi
.

2024-12-21 07:22 UTC, deltanedas commented on Resources/Textures/DeltaV/Clothing/Head/ReverseEngineering/juggernaut.rsi/meta.json
> +}
4 space indent for meta.json not 2

2024-12-23 20:43 UTC, deltanedas requested changes

2024-12-23 20:43 UTC, deltanedas commented on Resources/Textures/DeltaV/Clothing/Head/ReverseEngineering/juggernaut.rsi/meta.json
> +  },
this line has 2 space indent not 4 like the others

2024-12-24 08:14 UTC, deltanedas approved these changes

2025-01-01 01:56 UTC, Stop-Signs commented
What is the status on this? is there a reason its not been merged?

2025-01-01 04:40 UTC, deltanedas commented
needs direction approval

2025-01-06 02:35 UTC, Lyndomen approved these changes

2025-01-06 02:45 UTC, merged