Reduce RE time
DeltaV-Station/Delta-v pull request #2394
Opened 2024-12-08 07:03 UTC by Stop-Signs

## About the PR
5 seconds per percent instead of 30, maybe now this machine will actually be useful
## Why / Balance
Reverse engineering machines, despite reworks, have always been kind of, well, bad. this should hopefully bring them to relevancy.

takes ~8 minutes to RE something, 5 seconds may be a bit over tuned, but im willing to adjust based on direction

## Technical details
1 line C#

## Media

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Reverse engineering machines now function much faster!

2024-12-08 15:34 UTC, Radezolid commented
This machine lets you get T3 almost for free and no glimmer, so at least it costs time. A toggle to allow faster research but at the cost of generating glimmer would be better.

2024-12-11 19:53 UTC, MilonPL requested changes

2024-12-11 19:53 UTC, MilonPL commented on Content.Shared/Nyanotrasen/ReverseEngineering/ReverseEngineeringMachineComponent.cs
> +    public TimeSpan AnalysisDuration = TimeSpan.FromSeconds(5);
make it 15

2024-12-13 09:11 UTC, MilonPL approved these changes

2024-12-13 09:11 UTC, merged