Frontier Port: Pretty Money
DeltaV-Station/Delta-v pull request #2398
Opened 2024-12-09 00:01 UTC by Unkn0wnGh0st333

## About the PR
Adds frontier's variant of Spesos that are honestly so much more nicer to look at

## Why / Balance
ANIMATED PRETTY MONEY!!

## Technical details
Changes stack coding slightly with frontier additions to make it functional. I don't think it'll cause THAT many issues haha...

## Media
![image](https://github.com/user-attachments/assets/abaf9abe-2d35-4235-9065-5eabee10a8d5)

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
Changes some C which I can't read so good luck

**Changelog**
🆑 

- Spesos now have a new pretty look transferred from the Frontier Station.

2024-12-09 00:18 UTC, whatston3 commented
For the love of god, fix the pink one, it's awful.

2024-12-09 00:21 UTC, Unkn0wnGh0st333 commented
> For the love of god, fix the pink one, it's awful.

Its animated in game and looks a lot better than the SS, I advise you test it to see for yourself

2024-12-09 00:24 UTC, whatston3 commented
> Its animated in game and looks a lot better than the SS, I advise you test it to see for yourself

https://github.com/new-frontiers-14/frontier-station-14/pull/1496
It was me, Austin.
It was me all along, Austin.
Truly though, it's been mildly chaffing me ever since I made the stupid thing.

2024-12-09 00:24 UTC, dvir001 commented
> > For the love of god, fix the pink one, it's awful.
> 
> Its animated in game and looks a lot better than the SS, I advise you test it to see for yourself

MFW He made the sprite

2024-12-17 04:58 UTC, Lyndomen approved these changes, later dismissed
Good spritework, good feature yes

2024-12-17 12:32 UTC, deltanedas requested changes
test fail real

2024-12-17 15:15 UTC, whatston3 commented on Resources/Prototypes/Entities/Objects/Misc/space_cash.yml
> +      Speso: 1
```suggestion
```

This is the only issue I can see - for what it's worth, if you aren't using a Currency, you could consider whitelisting the Cash component inside mail capsules.

Also, might want to take the recoloured 100k sprite.

2024-12-18 01:30 UTC, deltanedas approved these changes

2024-12-18 01:30 UTC, merged