fix "teach person a lesson"
DeltaV-Station/Delta-v pull request #2412
Opened 2024-12-10 07:42 UTC by MilonPL

## About the PR

now it just subscribes to the MobStateChangedEvent, then checks if the state change is to Dead, and if the mind of the entity that died matches the mind we have as the target
also sets it in the comp rather than the funny list in the system because we have the means to do ECS properly

## Why / Balance

no more noobtrap redtext because you didnt know to open your objectives after killing someone

## Breaking changes

**Changelog**

:cl:
- fix: The Teach Person a Lesson objective will now register properly when your target dies.

2024-12-10 16:56 UTC, deltanedas requested changes

2024-12-10 16:56 UTC, deltanedas commented on Content.Server/DeltaV/Objectives/Components/TeachLessonConditionComponent.cs
> +}
use CodeConditionComponent and set it to true when the target dies
then remove OnGetProgress

2024-12-10 17:53 UTC, deltanedas requested changes

2024-12-10 17:53 UTC, deltanedas commented on Content.Server/DeltaV/Objectives/Systems/TeachLessonConditionSystem.cs
> +        }
this will NRE, add it to the query

2024-12-10 17:56 UTC, MilonPL commented on Content.Server/DeltaV/Objectives/Systems/TeachLessonConditionSystem.cs
> +        }
the comp is nullable and it resolves it anyways, tested in debug and works fine?

2024-12-10 20:32 UTC, deltanedas commented on Content.Server/DeltaV/Objectives/Systems/TeachLessonConditionSystem.cs
> +        }
then just pass uid if it resolves

2024-12-10 20:40 UTC, MilonPL commented on Content.Server/DeltaV/Objectives/Systems/TeachLessonConditionSystem.cs
> +        }
real

2024-12-12 00:18 UTC, deltanedas approved these changes

2024-12-12 00:18 UTC, merged