Meat Decor
DeltaV-Station/Delta-v pull request #2427
Opened 2024-12-12 09:13 UTC by rosieposieeee

## About the PR

Added some meaty decor to spice up meat areas. The teeth are basically just resprited stalagmites; they don't deal damage, but you can't walk over them.

Spookily lit:
![Content Client_dfuQDTfld6](https://github.com/user-attachments/assets/2a8a8c3b-ca8c-4de0-91e4-ab8f1ca7b0c4)

Fully lit:
![Content Client_MKSe8f0pKs](https://github.com/user-attachments/assets/044461ae-e4d1-42cd-b75b-6679635442eb)

Breaking them gives meat.
![Content Client_xKCWUIquOu](https://github.com/user-attachments/assets/b8f59d0b-e274-4153-80f6-8c61803b00ce)

The mouth can also go on the ground just fine, but is intended to be a poster-type thing.
![Content Client_fnGjJdy7w0](https://github.com/user-attachments/assets/991d01a7-e3da-481b-aeb8-79e8173e1a9f)

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

**Changelog**
:cl:
- add: Added some meat decorations.

2024-12-12 09:22 UTC, Bonktrauma commented
Rose, for the love of all things, do not make teeth drop meat, have them drop bones or something

2024-12-12 11:17 UTC, deltanedas commented
carp/shark teeth even

2024-12-12 15:13 UTC, Lyndomen approved these changes, later dismissed
Absolutely fantastic vibes. I would hope that we can reuse these in the future for an upcoming fun project.

2024-12-12 15:24 UTC, rosieposieeee commented
> Absolutely fantastic vibes. I would hope that we can reuse these in the future for an upcoming fun project.

sorry new license just got added to this PR called CC-BY-Telling-me-what-it-is >:)

2024-12-12 15:34 UTC, rosieposieeee commented
made them drop meat AND/OR bones, as i think they all contain both (the teeth have gums!)

carp or sharkminnow teeth felt a little silly and i didnt want to make a new useless tooth item (not that bones are at all useful)

2024-12-12 15:47 UTC, rosieposieeee commented
LMAO it failed because bones are worth too much. im just gonna revert it sorry to all the boners out there

2024-12-12 16:07 UTC, deltanedas requested changes

2024-12-12 16:07 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Objects/Decoration/meat.yml
> +  name: flesh teeth
name and description after id

2024-12-12 16:07 UTC, deltanedas commented on Resources/Textures/DeltaV/Objects/Decoration/Flesh/bigmeat.rsi/meta.json
> +}
missing newline at end of file

2024-12-12 16:24 UTC, Stop-Signs commented
Grotesque, i love it

2024-12-12 16:41 UTC, rosieposieeee commented on Resources/Prototypes/DeltaV/Entities/Objects/Decoration/meat.yml
> +  name: flesh teeth
do we have like an ss14 linter i can install or something to save you the trouble

2024-12-12 16:42 UTC, rosieposieeee commented on Resources/Textures/DeltaV/Objects/Decoration/Flesh/bigmeat.rsi/meta.json
> +}
😨

2024-12-12 16:49 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Objects/Decoration/meat.yml
> +  name: flesh teeth
there is a vscode robust yml extension but i have no idea if it does this for you

2024-12-12 17:02 UTC, rosieposieeee commented on Resources/Prototypes/DeltaV/Entities/Objects/Decoration/meat.yml
> +  name: flesh teeth
oh shit ill look into that

2024-12-13 00:25 UTC, rosieposieeee commented
setting this as a draft because apparently frontier has some better meat sprites that i want to 'rebase' all my art to, and replace the old shitty meat floorsnwalls with

2025-01-02 22:31 UTC, deltanedas commented
are you still going to do that @rosieposieeee

2025-01-03 00:31 UTC, rosieposieeee commented
> are you still going to do that @rosieposieeee

no, it turned out frontiers was just a set of sprites and zero yaml work done which i got like 25% into then decided was too much of a pita. this pr can just be added as-is

2025-01-28 11:34 UTC, deltanedas approved these changes

2025-01-28 12:32 UTC, merged