Drink flavors
DeltaV-Station/Delta-v pull request #2462
Opened 2024-12-17 22:50 UTC by Aikakakah

## About the PR
Added drink flavors. No more "tastes like alcohol."

## Why / Balance
Why? For spite. No longer shall we be fooled about the contents of a bottle when it all tastes the same. We needed variety and so I give you _flavor._

## Technical details
Added the flavor profiles into the Delta-V namespace, and commented the changes I had to make on the upstream drink files.

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

- add: Added some flavor to the drinks.

2024-12-18 01:22 UTC, deltanedas requested changes

2024-12-18 01:22 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Reagents/Consumable/Drink/drinks.yml
> +  flavor: kvass                     #Delta-V Flavor additions
holy spaces batman
for all these just 1 space before the #

2024-12-18 17:52 UTC, deltanedas submitted a review, later dismissed

2024-12-18 17:53 UTC, deltanedas commented
remove xeno basher as its failing the linter, also awaiting direction input

2024-12-18 19:33 UTC, Lyndomen commented
ETA 24 hours on Direction review

2024-12-19 20:47 UTC, Lyndomen submitted a review, later dismissed
Approved broadly, there are some ruminations about descriptions being a bit too indescript, but frankly descriptions everywhere are a mess. So this is good for now, and will likely get iterated upon.

2024-12-20 05:37 UTC, deltanedas commented
tests still fail

2024-12-20 18:00 UTC, deltanedas approved these changes

2024-12-20 18:00 UTC, merged