Lemon Lime Bitters
DeltaV-Station/Delta-v pull request #2464
Opened 2024-12-18 00:18 UTC by BlitzTheSquishy

## About the PR

Added lemon lime bitters

## Why / Balance

It's a crime against Australians to not have already had this in DV let alone SS14. 

## Technical details

## Media

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Lemon lime bitters! Australians Rejoice!

2024-12-18 00:18 UTC, BlitzTheSquishy commented
still WIP

2024-12-18 00:27 UTC, IamVelcroboy commented
> still WIP

you can set as draft to signal it's WIP to maintainers. Top right side of page
![image](https://github.com/user-attachments/assets/6cea47ee-92d8-46b2-9bda-b246f980e169)

2024-12-18 00:47 UTC, BlitzTheSquishy commented
> > still WIP
> 
> you can set as draft to signal it's WIP to maintainers. Top right side of page ![image](https://private-user-images.githubusercontent.com/107660393/396708028-6cea47ee-92d8-46b2-9bda-b246f980e169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0ODMxNTUsIm5iZiI6MTczNDQ4Mjg1NSwicGF0aCI6Ii8xMDc2NjAzOTMvMzk2NzA4MDI4LTZjZWE0N2VlLTkyZDgtNDZiMi05YmRhLWIyNDZmOTgwZTE2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwMDQ3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTcwNTA0OTY3MjQwNDQyNjUzMTEzMDdlNGJlYzk0OWY3YTBlMmQyNWFlZmVkZWQ2N2UwNjBhOTQyMjUyYTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kEkD3o8PD9Woz-avctrBs8QQYgDevQfB9HrrqBByF2A)

yeah.. but im laaazy

2024-12-18 07:54 UTC, BlitzTheSquishy commented
Conflicts from my own pr lmao

2024-12-18 21:14 UTC, Lyndomen commented
Direction review pending, 24 hours!

2024-12-18 21:20 UTC, IamVelcroboy submitted a review, later dismissed
Add to the random drink spawner

2024-12-18 21:57 UTC, Lyndomen commented
![image](https://github.com/user-attachments/assets/4f7bab3f-dbb4-47c8-983f-dee751f638d8)

2024-12-19 01:11 UTC, BlitzTheSquishy commented
> Add to the random drink spawner

I- havnt even MADE THE PROTOTYPE FOR THE BOTTLE YET GRRRRRRRRR

2024-12-19 01:28 UTC, Lyndomen commented
> > Add to the random drink spawner
> 
> I- havnt even MADE THE PROTOTYPE FOR THE BOTTLE YET GRRRRRRRRR

You asked for review!!! 😭😭😭

2025-01-02 03:31 UTC, BlitzTheSquishy commented
> > > Add to the random drink spawner
> > 
> > 
> > I- havnt even MADE THE PROTOTYPE FOR THE BOTTLE YET GRRRRRRRRR
> 
> You asked for review!!! 😭😭😭

Nuh UH

2025-02-13 01:47 UTC, deltanedas requested changes

2025-02-13 01:47 UTC, deltanedas commented on Resources/Prototypes/_DV/Flavors/flavors.yml
> +  description: flavor-complex-lemon-lime-bitters
this isnt defined

2025-02-13 01:48 UTC, deltanedas commented
steal sprites from someone

2025-02-13 01:52 UTC, BlitzTheSquishy commented
> steal sprites from someone

I am literally doing this right now-

2025-02-13 01:55 UTC, BlitzTheSquishy commented on Resources/Prototypes/_DV/Flavors/flavors.yml
> +  description: flavor-complex-lemon-lime-bitters
Elaborate?

2025-02-13 02:20 UTC, BlitzTheSquishy commented on Resources/Prototypes/_DV/Flavors/flavors.yml
> +  description: flavor-complex-lemon-lime-bitters
Not sure what you mean here cause this is perfectly functional

2025-02-17 03:08 UTC, BlitzTheSquishy commented
"changes" i just made them god damn it

2025-02-17 04:38 UTC, ewokswagger commented
Is this still draft?

2025-02-17 04:38 UTC, ThataKat commented
Ok direction is reviewing 24 hours for real this time

2025-02-17 04:44 UTC, BlitzTheSquishy commented
> Is this still draft?

Nope, i set it to normal PR

2025-02-17 23:12 UTC, deltanedas requested changes

2025-02-17 23:12 UTC, deltanedas commented on Resources/Locale/en-US/_DV/flavors/flavor-profiles.ftl
> +flavor-complex-lemon-lime-bitters = like an Aussie dessert
is this intentionally dessert (food) instead of desert (sand)

2025-02-17 23:12 UTC, deltanedas commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/boozeomat.yml
> +    DrinkAngobittersBottleFull: 3 # Delta-V - Angostura Bitters Bottle
DeltaV not Delta-V

2025-02-17 23:12 UTC, deltanedas commented on Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/drinks_bottles.yml
> +      - DrinkAngobittersBottleFull # Delta-V
.

2025-02-17 23:12 UTC, deltanedas commented on Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/drinks_glass.yml
> +      - LemonLimeBittersGlass # Delta-V
.

2025-02-17 23:12 UTC, deltanedas commented on Resources/Prototypes/_DV/Flavors/flavors.yml
> +
move them back to where it was, this part of the file is for flavors added to upstream drinks

2025-02-17 23:12 UTC, deltanedas commented on Resources/Textures/_DV/Objects/Consumable/Drinks/angobitters.rsi/meta.json
> +    },
move size below copyright

2025-02-17 23:12 UTC, deltanedas commented on Resources/Textures/_DV/Objects/Consumable/Drinks/lemonlimebitters.rsi/meta.json
> +    },
.

2025-02-17 23:44 UTC, BlitzTheSquishy commented on Resources/Locale/en-US/_DV/flavors/flavor-profiles.ftl
> +flavor-complex-lemon-lime-bitters = like an Aussie dessert
Yes, it's a dessert drink.

2025-02-18 04:06 UTC, ThataKat commented
Direction approved, drink responsibly

2025-02-18 09:05 UTC, deltanedas approved these changes

2025-02-18 09:06 UTC, merged

2025-02-18 11:23 UTC, Eagle0600 commented
It's only 1/6th bitters but as alcoholic as bitters? The real drink is effectively treated as nonalcoholic (you can definitely add vodka to make it alcoholic).

2025-02-18 17:08 UTC, deltanedas commented
the power of WA

2025-02-18 22:10 UTC, BlitzTheSquishy commented
> It's only 1/6th bitters but as alcoholic as bitters? The real drink is effectively treated as nonalcoholic (you can definitely add vodka to make it alcoholic).

wait did i fuck up its alcohol value? I swear I had it as zero ethanol added?

2025-02-18 22:22 UTC, BlitzTheSquishy commented
> > It's only 1/6th bitters but as alcoholic as bitters? The real drink is effectively treated as nonalcoholic (you can definitely add vodka to make it alcoholic).
> 
> wait did i fuck up its alcohol value? I swear I had it as zero ethanol added?

oops