DetDrobe-Update
DeltaV-Station/Delta-v pull request #2499
Opened 2024-12-21 15:49 UTC by foxcurl

## About the PR

Added the detective coat and beret to the DetDrobe, added detective uniform, coat, and beret to the uniform printer, and replaced outdated security coats in the uniform printer with the station security coats.
## Why / Balance

Detective coat and beret are available in loadout but not anywhere in-game. The security coats seemed to have been replaced for wardobes and the SecDrobe, but the uniform printer still made the old versions.
## Technical details

Changed YAML files accordingly. Not sure if the CL is needed.
## Media

![printedSecCoatsComparison](https://github.com/user-attachments/assets/a663dce3-74f2-442a-91dd-55362508c791)

## Requirements

- [x] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

I don't think there's any.
**Changelog**

:cl:
- tweak: Detective coat and beret are now in the DetDrobe and uniform printer.

2025-01-31 01:51 UTC, Radezolid requested changes

2025-01-31 01:51 UTC, Radezolid commented on Resources/Prototypes/Recipes/Lathes/clothing.yml
Move the new ones to the `_DV` namespace leaving the old ones commented out.

2025-02-01 03:39 UTC, Lyndomen approved these changes, later dismissed

2025-02-01 04:43 UTC, foxcurl commented on Resources/Prototypes/Recipes/Lathes/clothing.yml
done (or at least i think so), with categories based on the upstream ones they fell under.

2025-02-02 22:04 UTC, foxcurl commented
ok that did something bad im closing this

2025-02-02 22:04 UTC, closed without merging