Flour ops
DeltaV-Station/Delta-v pull request #2502
Opened 2024-12-21 22:04 UTC by Stop-Signs

## About the PR
flour, sugar, cornmeal, and rice bags now all contain 100u instead of 50

## Why / Balance
so that chefs can actually make an acceptable amount of food. people who eat all 4 loafs of bread i just cut in shambles cause i have 4 more.
## Technical details

## Media

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-12-21 22:19 UTC, dvir001 commented
Feel free to port the salt and pepper from frontier also.

2024-12-21 22:19 UTC, Stop-Signs commented
> Feel free to port the salt and pepper from frontier also.

YOUR SO RIGHT I ALMOST FORGOT

2024-12-22 05:46 UTC, deltanedas requested changes

2024-12-22 05:46 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Consumable/Food/ingredients.yml
> +          Quantity: 3
untouch

2024-12-22 15:36 UTC, deltanedas approved these changes

2024-12-22 15:36 UTC, merged