Port ingredient containers from frontier
DeltaV-Station/Delta-v pull request #2504
Opened 2024-12-21 22:47 UTC by Stop-Signs

## About the PR
Ported salt, pepper, and cocoa containers from frontier (with permission from dvir)
added them to chefvend

## Why / Balance
they are cool and a lot of recipes require salt pepper and cocoa so it makes sense!

## Technical details

## Media

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added salt, pepper, and cocoa containers to the chefvend

2024-12-22 17:22 UTC, IamVelcroboy requested changes
Add to the spawner `Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/food_ingredients.yml`

2024-12-22 18:07 UTC, Lyndomen submitted a review, later dismissed
frontier is a gold mine, approved

2024-12-23 18:00 UTC, Stop-Signs commented
> Add to the spawner `Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/food_ingredients.yml`

id personally not like this in that specific spawner, just because salt, pepper, and cocoa are moreso things that are normally near impossible to get more of, which putting them in the vend spawns. i think it would be better for chefs to get the items that are already in that spawner, which can all be mixed with water to get a ton of food, rather than these items.

2024-12-23 18:03 UTC, IamVelcroboy commented
> > Add to the spawner `Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/food_ingredients.yml`
> 
> id personally not like this in that specific spawner, just because salt, pepper, and cocoa are moreso things that are normally near impossible to get more of, which is an issue that putting them in the vend fixes. i think it would be better for chefs to get the items that are already in that spawner, which can all be mixed with water to get a ton of food, rather than these items.

I'm saying in addition to the vendor, they should be in the rng spawner as well

2024-12-23 18:06 UTC, IamVelcroboy commented
Bags of salt/pepper could replace the shakers. Cocoa should be added to the other bags of dry stuff, like flour/rice/sugar/etc. You can give it a lower probability if you want. But it should be in there

2025-01-02 03:58 UTC, IamVelcroboy submitted a review, later dismissed

2025-01-02 18:36 UTC, deltanedas requested changes

2025-01-02 18:36 UTC, deltanedas commented on Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/food_ingredients.yml
> +      - id: ReagentContainerPepper
add ` # DeltaV` to this line too

2025-01-03 19:06 UTC, deltanedas approved these changes

2025-01-03 19:18 UTC, merged