Research digiboard
DeltaV-Station/Delta-v pull request #2508
Opened 2024-12-22 06:06 UTC by SirSmith148

## About the PR

Added New Mystagogue item, the Research Digi-Board, this work similarly to the Logistics Digi-Board, allowing remote use of the research console. (Link to Pull request of original Digi-board: https://github.com/DeltaV-Station/Delta-v/commit/abaa2feba5b17bde4014c8b7d2525d9f3254671c#diff-6e493dfa3320562d461bc23a070f671cfd6e2f55574c8de3a5c9ea6ed6799bffR557)

## Why / Balance

The Logistics Officer and the Mystagogue have the unique gameplay loop of needing to take requests from the crew for certain items/research, and then using a console to order or approve. Giving the Mysta the ability for it will allow them to fulfill these requests when otherwise busy handling anoms or deep inside the research labs of epi, and when understaffed. 

## Technical details

-Added code for opening the research menu with the Digi-Board
-Added new Digi-Board to antag steal objective lists
-Added new Digi-Board to Mysta Locker list

## Media

Just a recolor of the original Digi-Board Sprite
https://imgur.com/a/uJcu75F

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

N/A

**Changelog**

:cl:
- add: Research Digi-Board
- tweak: Added Research Digi-Board to Steal Objectives

2024-12-22 08:33 UTC, deltanedas requested changes
all of these need to go in deltav folders

2024-12-22 08:35 UTC, SirSmith148 commented
> all of these need to go in deltav folders

2024-12-22 08:36 UTC, deltanedas commented
you dont have to close it or anything just push commits to the same branch

2024-12-22 08:37 UTC, SirSmith148 commented
> you dont have to close it or anything just push commits to the same branch

It was a mis click sorry haha, I only really edited existing files, do I need to migrate the whole files I edited to the DeltaV folder?

2024-12-22 08:43 UTC, deltanedas commented
yes

2024-12-22 10:00 UTC, SirSmith148 commented
> yes

Updated was able to move everything to Delta V except the ObjectiveGroups as I saw all the other DeltaV ones were in the original file

2024-12-22 10:11 UTC, deltanedas requested changes

2024-12-22 10:11 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Objects/Misc/paper.yml
> +    sprite: /Textures/DeltaV/Objects/Misc/rd_clipboard.rsi
dont need /Textures/ prefix

2024-12-22 10:11 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Objects/Misc/paper.yml
> +
remove one of the extra lines

2024-12-22 10:11 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Misc/paper.yml
> +
untouch

2024-12-22 10:11 UTC, deltanedas commented on Resources/Prototypes/Objectives/objectiveGroups.yml
> +    RdClipboardStealObjective: 1 #DeltaV - Mysta steal Objective see Resources/Prototypes/DeltaV/Objectives/traitor.yml
add a space after the #

2024-12-22 10:11 UTC, deltanedas commented on Resources/Textures/DeltaV/Objects/Misc/rd_clipboard.rsi/meta.json
4 space indent not 2

2024-12-22 11:19 UTC, deltanedas requested changes
other than that, just waiting on direction approval

2024-12-22 11:19 UTC, deltanedas commented on Resources/Textures/DeltaV/Objects/Misc/rd_clipboard.rsi/meta.json
replace tabs with spaces

2024-12-22 18:12 UTC, Lyndomen commented
Hello! Direction review, 24 hours.

2024-12-22 18:12 UTC, SirSmith148 commented
> Hello! Direction review, 24 hours.

Thank you!

2024-12-23 08:47 UTC, deltanedas submitted a review, later dismissed

2024-12-23 22:15 UTC, Lyndomen requested changes
Requesting an update to move this down to about 7 or 8 blunt, not 10. Once that is all set, approved!

2024-12-23 22:16 UTC, SirSmith148 commented
> Requesting an update to move this down to about 7 or 8 blunt, not 10. Once that is all set, approved!

Its the same amount of blunt as the logistics version not that it really matters to me lol

2024-12-26 12:37 UTC, Lyndomen approved these changes

2024-12-26 16:19 UTC, merged