mining voucher
DeltaV-Station/Delta-v pull request #2512
Opened 2024-12-22 14:32 UTC by deltanedas

## About the PR
half-ports mining voucher from tg
currently it has 3 of 6 kits:
- crusher kit, self explanatory
- extraction kit, fulton beacon and 20 fultons
- conscription kit

Requires #2510 (conscription kit)

## Why / Balance
lets miners pick different classes at the start of the shift, like a crusher for faster mining or fultons for roundstart debris farming

## Technical details
not using thief toolbox code soon

## Media
![02:29:09](https://github.com/user-attachments/assets/42f214b6-bc2c-43f4-ac3a-03bcdfa95263)

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
no

**Changelog**
:cl:
- add: Added mining vouchers for salvage to get a loadout that can be redeemed at the salvage vendor.

2024-12-28 05:31 UTC, Lyndomen commented
Shit I forgor to review

2024-12-28 05:33 UTC, Lyndomen commented
I'm happy to ask dumb questions, why not use loadouts

2024-12-28 05:34 UTC, deltanedas commented
you cant talk to eachother in the locker room and discuss what gear to use vs loadouts everyone took conscription billions must mine

2024-12-28 23:33 UTC, deltanedas commented
> 12 hours

> 18 hours ago

erm what the gleep

2024-12-29 01:18 UTC, Lyndomen commented
> > 12 hours
> 
> > 18 hours ago
> 
> erm what the gleep

erm i was uhhhh not doing ss14 stuff

2024-12-29 01:19 UTC, Lyndomen requested changes

2024-12-29 01:19 UTC, Lyndomen commented on Resources/Locale/en-US/deltav/salvage/mining-voucher.ftl
> +    a proto-kinetic accelerator, mineral scanner, ID card and other useful gear.
no id pls  (ask LO to do their job)

2024-12-29 01:19 UTC, Lyndomen commented on Resources/Locale/en-US/deltav/salvage/mining-voucher.ftl
> +    a proto-kinetic accelerator, mineral scanner, ID card and other useful gear.
damn that kit isnt in this pr

2024-12-29 03:23 UTC, deltanedas commented on Resources/Locale/en-US/deltav/salvage/mining-voucher.ftl
> +    a proto-kinetic accelerator, mineral scanner, ID card and other useful gear.
ok real ill remove it

2024-12-29 03:26 UTC, Lyndomen approved these changes
nice

2024-12-29 03:38 UTC, merged