shitmed real
DeltaV-Station/Delta-v pull request #2542
Opened 2024-12-27 18:36 UTC by deltanedas

## About the PR
ports shitmed including autodoc and illegal carp surgery etc
as prerequisite also ported crawling from white dream (default key is r to lie down/stand up)
self surgery is disabled

i really want space law to have medical malpractice be a crime so tider surgery in dorms is actually illegal

## Why / Balance
mrp roboticists explaining how a toolbox is a surgical implement no longer

## Technical details
:trollface:

mothroach inventory got skipped somehow so cherry picked to not have ultra conflicts

## Media
![05:59:01](https://github.com/user-attachments/assets/9edd25ac-23eb-4e21-87f7-1acb9fea08ca)

## Requirements
- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
none since newmed is kill :trollface:

**Changelog**
:cl:
- add: It is next week. Surgery is here.

2024-12-27 18:39 UTC, Lyndomen commented
fastest port in the west wtf

2024-12-27 18:40 UTC, Lyndomen commented
direction review, gonna have questions, and gonna have to play goob i guess. 1 week because no fun allowed :trollface:

2024-12-27 19:10 UTC, Avalon-Proto commented
Limb damage here too then? Can I aim a shotgun at someone and blow their dome off?

2024-12-27 19:19 UTC, deltanedas commented
yes targeting exists too but i dont know if guns use it, at least melee does

2024-12-27 19:56 UTC, Radezolid commented
> direction review, gonna have questions, and gonna have to play goob i guess. 1 week because no fun allowed :trollface:

the "next week" meme continues

2024-12-27 20:17 UTC, deltanedas commented
last time on one piece

2024-12-27 22:22 UTC, gluesniffler commented
shitmed was a mistake

2024-12-29 20:36 UTC, Tryded commented
Finally shit med

2024-12-30 17:58 UTC, dvir001 commented
I will be honest calling it shitmed even in code comments not giving me the responsible code merge vibe I was looking for :trollface:

2024-12-30 19:25 UTC, alterae commented
since prosthetic limbs are real now i think it's important that it be possible for a character to have prosthetic limbs at round-start (we have cosmetics rn but those aren't the same rp-wise)

2024-12-30 19:41 UTC, alterae commented
also mousetraps should specifically damage the feet, and land mines should specifically damage the feet and legs

2024-12-31 08:17 UTC, deltanedas commented
all very easy to do, 2 line change to damage specific limbs

for prosthetics it would need bodypart loadouts which would be a huge undertaking

2025-01-03 11:17 UTC, BarryNorfolk commented
![image](https://github.com/user-attachments/assets/1f646f41-b5d4-4566-9c70-b75d5b6a627d)
Russian translations on the autodoc.

2025-01-03 15:53 UTC, Solaris7518 commented
Surgery! No longer a week away!

2025-01-03 17:32 UTC, deltanedas commented
autodoc nay be chinese soon even

2025-01-04 04:19 UTC, Lyndomen approved these changes, later dismissed
Approving, but also requesting changes eventually. Requesting bits of yaml slash damage added to various surgical steps, as it shouldnt be yolo free to do this shit. 


We would also like it so that surgical steps performed on a conscious patient cause way more damage than they do if that guy is unconscious- they are thrashing around and shit. 

During the playtest i ran into a bug as a ghost where everyone was laying down instead of standing up, and when they would lay down - on my screen they stood up.

2025-01-04 04:19 UTC, Lyndomen commented on Resources/Prototypes/Catalog/Cargo/cargo_livestock.yml
> +    sprite: Mobs/Animals/mothroach/mothroach.rsi
comment?

2025-01-04 04:19 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +        Bloodloss: 10
add a bit of slash

2025-01-04 04:19 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    sprite: _Shitmed/Objects/Specific/Medical/Surgery/retractor.rsi
add a bit of slash

2025-01-04 04:19 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    sprite: _Shitmed/Objects/Specific/Medical/Surgery/retractor.rsi
add blunt damage

2025-01-04 04:19 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +  - type: Sprite
add slash damage

2025-01-04 04:19 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +        Heat: -5
remove, why does sealing wounds heal a burn- it should DO burn?

2025-01-04 04:19 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +        Heat: -5
same as before, why does cauterizing heal

2025-01-04 04:19 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    state: hemostat
add bit of slash damage

2025-01-04 04:19 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    sprite: _Shitmed/Objects/Specific/Medical/Surgery/manipulation.rsi
add bit of slash damage

2025-01-04 04:19 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +        Heat: -5
same as before, why does cauterizing heal

2025-01-04 04:19 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    sprite: _Shitmed/Objects/Specific/Medical/Surgery/scalpel.rsi
tiny slash damage

2025-01-04 04:19 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    duration: 8
slash damage

2025-01-04 04:19 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    sprite: _Shitmed/Objects/Specific/Medical/Surgery/circular-saw.rsi
blunt damage or slash idfk

2025-01-04 04:50 UTC, deltanedas commented
funny thing it already halves damage when the patient is asleep so it just needs adding damage to everything :trollface:

2025-01-04 04:53 UTC, deltanedas commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    sprite: _Shitmed/Objects/Specific/Medical/Surgery/manipulation.rsi
brute even because of compressing tissues

2025-01-04 04:56 UTC, deltanedas commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +        Heat: -5
made it heal slash instead because that actually makes sense, its meant to close an incision

2025-01-04 05:40 UTC, deltanedas commented
amputating urists arm without vs with sedation:
![05:37:18](https://github.com/user-attachments/assets/d1436449-6659-43a6-b0df-a8d2892b2a65)
![05:39:16](https://github.com/user-attachments/assets/e891149c-4234-492a-b084-d21138acb2b1)

2025-01-04 05:47 UTC, deltanedas commented on Resources/Prototypes/Catalog/Cargo/cargo_livestock.yml
> +    sprite: Mobs/Animals/mothroach/mothroach.rsi
thats how this is upstream

2025-01-05 11:39 UTC, dvir001 commented
This need to be moved to Diona legs
https://github.com/DeltaV-Station/Delta-v/pull/2543

2025-01-05 14:54 UTC, deltanedas commented
true

2025-01-05 19:18 UTC, Avalon-Proto commented
Surgery real soon. As well as horrible horrible torture :3

2025-01-05 21:35 UTC, Lyndomen commented
Apparently people turn into gibbed torsos after 58 seconds in space. That's not good

2025-01-05 23:42 UTC, alterae commented
if a character has decals those decals seem to stick to body parts weirdly. to reproduce, try making a character with the prosthetic leg cosmetics and then amputating a foot or leg

also harpy arms seem to be invisible for some reason? at least when spawned in. and removing one of a harpy's hands causes both wings to disappear visually

the slash damage from surgery works great tho !! (tho i do think those "clamp bleeders" steps should, like, actually clamp blood loss. but currently even with a conscious patient one stack of gauze is more than enough for most surgeries)

integration with the pain system would be neat, but i imagine that's non-trivial

very happy with how this is progressing overall !

2025-01-06 00:48 UTC, Lyndomen commented
> integration with the pain system would be neat, but i imagine that's non-trivial

what would this look like in your mind?

2025-01-06 00:53 UTC, alterae commented
> what would this look like in your mind?

i mean i'm not at all familiar with the internal workings of the pain system, only its external effects, but\
surgery on conscious/non-anesthesized patients would cause pain for some duration. the more nasty the surgery (i.e. the more slash damage it deals) the more severe/longer the pain would last

maybe lower-efficiency surgical implements would cause more pain? (side-note: lower-efficiency surgical implements should ABSOLUTELY cause more damage. using a kitchen knife as a scalpel is going to cause collateral damage)

i don't think surgeries should be able to, like, _permanently_ cause chronic pain? that would kinda suck.

2025-01-06 01:05 UTC, alterae commented
> In my mind, it could be neat to add the chronic pain condition if one undergoes a major surgery in general.

tho this would definitely be simpler to implement i imagine? and would probably work fine tbh. i'm being kinda extra rn

2025-01-06 01:30 UTC, deltanedas commented
> decals seem to stick to body parts weirdly

known issue with gauze markings and stuff. prosthetics should be replaced with body part loadouts Eventually

> harpy arms seem to be invisible

shouldve been fixed by one of the updates ill see whats missing

2025-01-06 14:08 UTC, Avalon-Proto commented
God I need this to be real already. Also a quick question on limb severance modifiers, are they based off stuff like slash damage or?

2025-01-06 16:59 UTC, deltanedas commented
limbs take more slash damage than pierce or brute, and they get gibbed entirely at high enough brute/slash/heat damage

by pure damage modifiers weapons doing slash instead of brute will sever limbs much faster

2025-01-06 22:56 UTC, alterae commented
another observation on Harpy arms/hands: the wing visuals (left and right) seem to be entirely attached to one hand (forget which side)

moth wings don't appear to have that problem

2025-01-07 09:48 UTC, deltanedas commented
harpy limb sprites are also very bad (both sides in each item, same sprite for arm and hand)

2025-01-07 10:42 UTC, gluesniffler commented
> harpy limb sprites are also very bad (both sides in each item, same sprite for arm and hand)

they dont even have hand sprites lmao, i've been putting off fixing harpy sprites and layers in solidus's stead for way too long, and i dont think ill get to it soon

2025-01-07 15:56 UTC, Lyndomen requested changes
yaml nitpicks

2025-01-07 15:56 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    sleepModifier: 2
if my math is right, this then does damage- like 20 bloodloss if awake? (good)

2025-01-07 15:56 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +        Slash: -5
nitpick, +3 heat

2025-01-07 15:56 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +        Slash: -5 # DeltaV: Cauterizing closes incisions, not grafting skin
nitpick, +3 heat

2025-01-07 15:56 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +        Slash: -5 # DeltaV: Cauterizing closes incisions, not grafting skin
nitpick, +3 heat

2025-01-07 15:56 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +        Bloodloss: -5
ideally this stops bleed, not heal bloodloss. doesnt matter too much either way

2025-01-07 15:56 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    duration: 1
duration 3

2025-01-07 15:56 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    duration: 1
3

2025-01-07 15:56 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +        Slash: -1 # DeltaV: Cauterizing closes incisions, not grafting skin
+1 heat :trollface:

2025-01-07 15:56 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    duration: 2
3, so its harder to driveby incision slipped people

2025-01-07 15:56 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    duration: 2
4

2025-01-07 15:56 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    duration: 2
4

2025-01-07 15:57 UTC, Lyndomen commented
maints surgery 
![image](https://github.com/user-attachments/assets/42db88ba-fdca-4665-a616-bc56010573e4)

2025-01-07 15:59 UTC, deltanedas commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    sleepModifier: 2
no when awake it heals 5, when asleep it heals 10
the default is 0.5 since its usually damage not healing

2025-01-07 16:00 UTC, deltanedas commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +        Slash: -5
then it would both heal and damage more when asleep which is weird

2025-01-07 16:01 UTC, deltanedas commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +        Bloodloss: -5
bleeding isnt modified by anything yet (decapitating does 100 bloodloss instead of arterial bleeding), itll be changed at some point

2025-01-07 16:02 UTC, deltanedas commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    duration: 2
youd have to slip someone, switch to a scalpel then right click, wait for ping, click start surgery, go to the part, open incision then finally click the funny button

or you can just stab someone instantly

2025-01-07 16:37 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    sleepModifier: 2
oh ok thats good nuff

2025-01-07 16:38 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +        Slash: -5
that is weird real, ok nvm

2025-01-07 16:38 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +        Bloodloss: -5
copy, good enough

2025-01-07 17:01 UTC, Lyndomen commented on Resources/Prototypes/_Shitmed/Entities/Surgery/surgery_steps.yml
> +    duration: 2
fair enough cant expect perfection

2025-01-07 17:13 UTC, Lyndomen approved these changes
good to go

2025-01-07 17:15 UTC, merged

2025-01-07 17:29 UTC, Avalon-Proto commented
Damn, should have waited 5 more minutes to rerun publish to get this out there. Maybe run it again even

2025-01-07 17:42 UTC, deltanedas commented
theres more stuff i want to do with harpy sprites among others hopefully itll get in before next publish :trollface:

2025-01-07 18:08 UTC, Spielern commented
i'm only a player so i doubt my words mean much, but this is super impressive. fantastic job, the work you put in is always extremely valued!

2025-01-08 00:24 UTC, Bonktrauma commented
Now we need to give diona the ability to regrow limbs