Add hostage ops (Nuke ops alternative objective)
DeltaV-Station/Delta-v pull request #2545
Opened 2024-12-28 03:11 UTC by beck-thompson

## About the PR

Added hostage ops to nukies. Specifically:
When nukies start there is a 50/50 chance of them either going hostage ops or standard nuke the station.
To succeed in hostage op you need to:
1.) Kidnap 3 heads (Handcuff them)
2.) Steal the nuke disk

To help, hostage implants have also been added which pacify anyone implanted while also making them immune from syndicate turrets.

## Why / Balance

Nukies are kind of boring and this will hopefully spice it up while also being more RP focus!

**DISCLAIMER**:
A lot of the stuff here was put together very quickly and isn't fully complete. Its more of a proof of concept to see if people actually like playing the objective. If direction ends up liking it then I'll come back and smooth over the edges!

## Technical details

A lot of this stuff isn't the best but it works. Specifically:
1.) The nuke paper override is all suspect and should be done better. It does work well enough and for a real fix there needs to be a re-mapping of the shuttle which is going to suck.
2.) The `NukieOperationSystem`s way of working is weird and it should probably listen for another event instead of just adding it when the first event hits.
3.) Probably more but I'm tired 😢

## Media

![Screenshot 2024-12-27 190110](https://github.com/user-attachments/assets/7cee6238-c92f-470e-b1fd-5e071a632a1e)
![Screenshot 2024-12-27 190135](https://github.com/user-attachments/assets/0cb01343-7d95-416b-96ba-d7118dadcdd4)
![Screenshot 2024-12-27 190222](https://github.com/user-attachments/assets/728fd5e5-1d46-4524-b17e-2eafd99bdbb4)

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

**Changelog**

:cl:
- add: Hostage ops. This is an alternative to nuclear operatives where you must kidnap the heads of the station!
- add: Hostage implants. These implants pacify anyone implanted and make them immune from syndicate turrets.

2024-12-28 03:12 UTC, beck-thompson commented
As I was making the PR I also realized that hostage ops will always end in crew victory... I'll figure that out later 😆

2024-12-28 04:51 UTC, deltanedas requested changes

2024-12-28 04:51 UTC, deltanedas commented on Content.Server/DeltaV/Antag/NukieOperationSystem.cs
> +    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
rename to _proto

2024-12-28 04:51 UTC, deltanedas commented on Content.Server/DeltaV/Objectives/Components/KidnapHeadsConditionComponent.cs
> +    public uint NumberOfHeadsToKidnap;
use NumberObjective thing instead of this

2024-12-28 04:51 UTC, deltanedas commented on Content.Server/DeltaV/Objectives/Systems/KidnapHeadsConditionSystem.cs
> +        else if (totalHeads < condition.Comp.NumberOfHeadsToKidnap)
use Math.Min(totalHeads, _number.GetNumberOrWhateverItsCalled(uid))

2024-12-28 04:51 UTC, deltanedas commented on Content.Server/DeltaV/Objectives/Systems/NukeStationConditionSystem.cs
> +    private void OnGetProgress(Entity<NukeStationConditionComponent> condition, ref ObjectiveGetProgressEvent args)
add CodeConditionComponent to the objective then when nuke explodes check if the map its on is correct and then greentext all nuke objectives (should probably store the station on the objective to check it on nuke event)

2024-12-28 04:51 UTC, deltanedas commented on Content.Server/Nuke/NukeCodePaperSystem.cs
> +            RaiseLocalEvent(evnt);
raise it by ref

2024-12-28 04:51 UTC, deltanedas commented on Content.Server/DeltaV/Antag/NukieOperationComponent.cs
> +public sealed class GetNukeCodePaperWriting : EntityEventArgs
make it a ByRefEvent record struct

2024-12-28 04:51 UTC, deltanedas commented on Content.Shared/DeltaV/Antag/NukieOperationPrototype.cs
> +    public List<EntProtoId> OperationObjectives = default!;
= new()

2024-12-28 04:51 UTC, deltanedas commented on Content.Shared/DeltaV/Antag/NukieOperationPrototype.cs
> +    public string? NukeCodePaperOverride;
locid and Loc.GetString it

2024-12-28 04:51 UTC, deltanedas commented on Content.Shared/DeltaV/Implants/AddFactions/AddFactionsImplantSystem.cs
> +        if (args.Implanted == null)
`if (args.Implanted is not {} target)`

then use target instead of args.Implanted.Value

2024-12-28 04:51 UTC, deltanedas commented on Content.Shared/DeltaV/Implants/AddFactions/AddFactionsImplantSystem.cs
> +    // TODO: Update this function to actually remove the factions correctly when removal of the implant is supported.
its 1 line to do this

2024-12-28 04:51 UTC, deltanedas commented on Content.Shared/DeltaV/Implants/Pacifism/PacifismImplantSystem.cs
> +        if (args.Implanted == null)
same

2024-12-28 04:51 UTC, deltanedas commented on Content.Shared/DeltaV/Implants/Pacifism/PacifismImplantSystem.cs
> +    private void OnRemove(Entity<PacifismImplantComponent> ent, ref EntGotRemovedFromContainerMessage args)
remove Pacified if it didnt exist before adding above, store it on the implant

2024-12-28 04:51 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Objectives/nukies.yml
> +  nukeCodePaperOverride: "Hostage op. Look at your objectives for more information. It is recommended to buy hostage implants from your uplink."
move to loc

2024-12-28 04:51 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Objectives/nukies.yml
> +  name: Steal the disk. # Gets overriden for now
dont need these

2024-12-28 04:51 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Misc/subdermal_implants.yml
> +
remove this evil line

2024-12-28 04:51 UTC, deltanedas commented on Resources/Prototypes/ai_factions.yml
> +  - Hostage # DeltaV Nukie hostage ops
comment goes on friendly

2024-12-28 05:22 UTC, Lyndomen commented
This is hopefully part one of a nukie refresh, we will see. Direction 👍

2024-12-28 06:36 UTC, beck-thompson commented on Resources/Prototypes/DeltaV/Objectives/nukies.yml
> +  name: Steal the disk. # Gets overriden for now
I forgor 😔

2024-12-28 10:43 UTC, Smugman commented
I think more diverse objectives for nukies are a good idea, i myself had been idly toying with a "Syndicate Mission board" idea, allowing them to select from different kinds of operations, though i never figured out how to give people a reason to pick anything but Nukeops.

However, i think as a 50/50 chance, players might be dissapointed to see that they rolled nukies, only to not be nuking the station.
I also do not think hostage-ops is sufficient to carry the entire round, and might feel a bit underwhelming to both sides in terms of shaping the round.

However, I think tuned down non-nuking syndicate special ops teams would allows for nukies to be viable outside of them being the main gamemode, for example: Hostage ops as a Midround antag that doesnt want to destroy the station.

I think as it is, Hostage ops would not be as interesting for the nukies nor the Crew as plain Nukeops, and people would be unhappy to see that they "lost the coin toss".

2024-12-28 11:07 UTC, Kr8art commented
I personally really like the idea, and I think Nukies having alternative objectives really helps to shake up the meta. People won't immediately know their objectives as soon as bloodreds are spotted.

Maybe the number of hostages they need to take should be higher or scale dynamically with players.
Could have it pick from all crew at random with a higher weight towards heads. That way you also avoid edge cases where there's no or less than three heads present in a round.

Not sure what a good number of hostages would be. Maybe 10% of the station or perhaps equal to the number of nukies (or maybe even nukies+n to have it always be a few more hostages than nukies). 

I think having a high number of hostages would help to make this mode feel more impactful. It prevents a quick smash and grab as nukies would likely have to make multiple trips to get everyone, and more departments would be affected. It also adds some logistically challenge for the Nukies, as they need to dedicate some manpower to keep already taken hostages secure from potential rescue attempts by the crew.

2024-12-28 18:07 UTC, beck-thompson commented
> Maybe the number of hostages they need to take should be higher or scale dynamically with players.
Could have it pick from all crew at random with a higher weight towards heads. That way you also avoid edge cases where there's no or less than three heads present in a round.

Unfortunately due to technical limitations that is easier said than done 😔. Its definitely possible, but with how the objectives are done its going to require more work! The reason its only heads right now and not random people on the station is because it would be very difficult to grab just a random passenger, if your going after heads it should be much easier to actually find them!

If this goes well, my plan is to have a pinpointer sort of object that allow you to track targets so you can actually find them easier!

2024-12-28 18:09 UTC, beck-thompson commented
> I think as it is, Hostage ops would not be as interesting for the nukies nor the Crew as plain Nukeops, and people would be unhappy to see that they "lost the coin toss".

Honestly I just disagree, I would be much more excited to do something rather than just nuke the station. Hostage ops will hopefully allow for a lot more RP if the nukies want it (But isn't required). Really though, I think we just need to see how it turns out in actual matches to see if its fun or not. Knowing beforehand is really hard 😆

2024-12-28 23:13 UTC, beck-thompson commented
The changes to `NukeopsRuleSystem.cs` are incomplete. I'm trying to figure out a way of triggering the win condition but I think the maps are not what I was hoping they were (pretty sure its ftling to the area around the outpost and not the outpost itself). If anyone has ideas on how to approach this I'm all ears

2024-12-28 23:29 UTC, deltanedas requested changes

2024-12-28 23:29 UTC, deltanedas commented on Content.Server/DeltaV/Objectives/Systems/KidnapHeadsConditionSystem.cs
> +    [Dependency] private readonly NumberObjectiveSystem _numberObjectiveSystem = default!;
rename it to _number

2024-12-28 23:29 UTC, deltanedas commented on Content.Server/DeltaV/Objectives/Systems/KidnapHeadsConditionSystem.cs
> +        foreach (var human in allHumans)
this is a mind so dont have the variable name be misleading, `var mind`

2024-12-28 23:29 UTC, deltanedas commented on Content.Server/DeltaV/Objectives/Systems/KidnapHeadsConditionSystem.cs
> +            if (!HasComp<CommandStaffComponent>(human.Comp.OwnedEntity))
`if (mind.Comp.OwnedEntity is not {} mob)` then use mob here and below

2024-12-28 23:29 UTC, deltanedas commented on Content.Server/DeltaV/Objectives/Systems/KidnapHeadsConditionSystem.cs
> +            if (!(TryComp<CuffableComponent>(human.Comp.OwnedEntity, out var cuffableComp) && cuffableComp.CuffedHandCount > 0))
add SharedCuffableSystem and use `_cuffable.IsCuffed((mob, cuffable))` it will be more futureproof

2024-12-28 23:29 UTC, deltanedas commented on Content.Server/DeltaV/Objectives/Systems/NukeStationConditionSystem.cs
> +            if (!TryComp(nukeopsRule.TargetStation, out StationDataComponent? data))
`TryComp<StationDataComponent>(nukeopsRule.TargetStation, out var data)`

2024-12-28 23:29 UTC, deltanedas commented on Content.Server/DeltaV/Objectives/Systems/NukeStationConditionSystem.cs
> +                    _codeCondition.SetCompleted(entityUid);
rename entityUid to uid

2024-12-28 23:29 UTC, deltanedas commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +using Content.Shared.Objectives.Components;
deltav comments

2024-12-28 23:29 UTC, deltanedas commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +            if (outpost != null && int.Parse(args.MapUid.ToString())-1 == int.Parse(outpost.Value.ToString()))
evil

2024-12-28 23:29 UTC, deltanedas commented on Content.Server/Nuke/NukeCodePaperSystem.cs
> +            }
add end comment after this

2024-12-28 23:29 UTC, deltanedas commented on Content.Shared/CombatMode/Pacification/PacifiedComponent.cs
> +[Access(typeof(PacificationSystem), typeof(PacifismImplantSystem))] // DeltaV add friend PacifismImplantSystem
remove

2024-12-28 23:29 UTC, deltanedas commented on Content.Shared/CombatMode/Pacification/PacifiedComponent.cs
> +using Content.Shared.DeltaV.Implants.Pacifism;
remove

2024-12-28 23:29 UTC, deltanedas commented on Content.Shared/DeltaV/Implants/Pacifism/PacifismImplantComponent.cs
refactor this so it has a ComponentRegistry and tracks which components already existed, then call it `AddComponentsImplantComponent` (funny name :trollface:)
before adding the components check HasComp for each type (use IComponentFactory to get Type from string) so when removing it you can selectively remove components based on if they didn't exist already

i dont think theres much value in per-field reverting (and that would really need engine code to not be horrible), the main issue here would be pacifist command (free AA) no longer being pacified. if they can't disarm anymore its not the end of the world and having it use componentregistry means implants can do very cool stuff in the future

2024-12-28 23:29 UTC, deltanedas commented on Resources/Prototypes/Entities/Objects/Misc/subdermal_implants.yml
> +    disallowAllCombat: true
replace this with
```yml
- type: AddComponentsImplant
  components:
  - type: Pacified
    disallowDisarm: true
    disallowAllCombat: true
```

2024-12-29 02:04 UTC, beck-thompson commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +            if (outpost != null && int.Parse(args.MapUid.ToString())-1 == int.Parse(outpost.Value.ToString()))
evil has been vanquished 🫡

2024-12-29 04:21 UTC, Smugman commented
> Honestly I just disagree, I would be much more excited to do something rather than just nuke the station. Hostage ops will hopefully allow for a lot more RP if the nukies want it (But isn't required). Really though, I think we just need to see how it turns out in actual matches to see if its fun or not. Knowing beforehand is really hard 😆

Yeah! I just think that nukies with reduced impact on the round wouldnt be recieved well, in Nukie rounds they are the ONLY antagonist (discounting the odds of sleeper agents spawning) which can feel underwhelming.
 
> Oh also, your idea of letting the nukies choose their objective is a good (Although it will be difficult!). You could really do fun things like give more TC and or equipment if they do hostage ops vs nuke ops.
Yeah, Choice would also 100% prevent dissapointment on the Nukie side, since they chose what ops to do.
I have a vague idea of how to do choice like that code wise and might finish my mockup in a bit.

More ops with gear and TC rewards have a lot of potential, Rare chance to get Centcom clothes to do CentOps, S.E.L.F Ops with a special law board and a free killborgs etc.

2024-12-29 05:04 UTC, Lyndomen commented
i personally am game to move nukies to the survival scheduler if its shit

2024-12-29 11:33 UTC, Kr8art commented
> Unfortunately due to technical limitations that is easier said than done 😔. Its definitely possible, but with how the objectives are done its going to require more work!

If I'd try this myself I'd probably attempt to just take the traitor target selection stuff and change the objectives from kill to cuff, but it's probably a lot more complicated than that.

Though personally I think the numbers of hostages needs to be higher to bring it closer to the threat level of 'station is getting nuked'. As people already pointed out, nukies are often the only threat on nukie rounds. Right now, the objective boils down to kill three heads and steal the nuke disk, which doesn't seem super difficult for a team of traitors with 40TC each.

That being said, it might be a good idea to just release it as it is currently once it's ready. Get feedback on it for a while. Because as you said it's really hard to predict how players will interact with this. Nukies could do the sickest RP, or they could just gun down three heads wordlessly and have the agent revive them in cuffs on the their shuttle. 

I'd even go as far as to have this replace regular nukeops for a week to get people's opinions. It's a playtest after all.

2024-12-29 16:29 UTC, beck-thompson commented
> If I'd try this myself I'd probably attempt to just take the traitor target selection stuff and change the objectives from kill to cuff, but it's probably a lot more complicated than that.

Main issue is actually making sure the nukies all have the same number of people to kidnap! Right now objectives are only made for one person, not groups! I can probably figure it out, but like you said, I think we need to see this in game to see what people actually think! What number of hostages do you think would be good?

2024-12-29 17:40 UTC, deltanedas commented
funny thing you dont even need hostages, just kill then cuff and steal :trollface:

2024-12-29 17:42 UTC, dvir001 commented
> hostages

Add an automated ERT call if all hostages are dead :trollface:

2024-12-29 17:48 UTC, Avalon-Proto commented
> > hostages
> 
> Add an automated ERT call if all hostages are dead :trollface:

Only once this PR is done
https://github.com/DeltaV-Station/Delta-v/pull/2552

2024-12-30 04:51 UTC, beck-thompson commented
Let me know what else needs to be done (Maybe the code is perfect?)! Also, I would prefer if #2561 was merged first so I could add a popup for the nukie players to inform them what's going on. Not a big deal either way! 🫡

2025-01-04 01:47 UTC, beck-thompson commented
Probably need feedback on the popups themselves... I'm not the best at writing that kind of stuff 😆

2025-01-09 06:58 UTC, beck-thompson commented
me when I cause my own merge conflicts

2025-01-09 10:03 UTC, deltanedas requested changes

2025-01-09 10:03 UTC, deltanedas commented on Resources/Locale/en-US/_DV/feedbackpopup/popups/nukeHostagepopup.ftl
> +feedbackpopup-hostage-nukie-end-description-1 = Suggestions will be relayed to the DISCORD-CHANNEL-NAME-HERE channel.
so true

2025-01-13 16:43 UTC, beck-thompson commented on Resources/Locale/en-US/_DV/feedbackpopup/popups/nukeHostagepopup.ftl
> +feedbackpopup-hostage-nukie-end-description-1 = Suggestions will be relayed to the DISCORD-CHANNEL-NAME-HERE channel.
Fixed!

2025-01-25 01:29 UTC, deltanedas approved these changes

2025-01-25 01:29 UTC, merged