Speedboot text change and drain nerc
DeltaV-Station/Delta-v pull request #2550
Opened 2024-12-28 05:01 UTC by Lyndomen

## About the PR
 made speedboot controlled via bluespace. Also made it so they drain 15 power instead of 10, microreactot only gives 12. Turn it on for a speed boost and let it charge up. 

## Why / Balance
 speed is good

## Technical details
 yaml

## Media

## Requirements

- [x] I have tested all added content and changes.
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Speedboots consume more energy, and are now powered by bluespace

2024-12-28 05:13 UTC, Lyndomen commented
direction should review this I guess

2024-12-28 05:33 UTC, deltanedas requested changes

2024-12-28 05:33 UTC, deltanedas commented on Resources/Prototypes/Entities/Clothing/Shoes/misc.yml
> +    drawRate: 30 # DeltaV 10>30, you have to turn off micro reactor at somepoint
was 4 not 10

2024-12-28 05:34 UTC, Lyndomen commented on Resources/Prototypes/Entities/Clothing/Shoes/misc.yml
> +    drawRate: 30 # DeltaV 10>30, you have to turn off micro reactor at somepoint
Forgot how to count

2024-12-28 06:30 UTC, deltanedas approved these changes

2024-12-29 05:25 UTC, Lyndomen commented
direction approved :trollface:

2024-12-29 07:31 UTC, merged