Ert Overhaul 4.0
DeltaV-Station/Delta-v pull request #2552
Opened 2024-12-28 18:30 UTC by Tryded

## About the PR

Port Paradise Station ERT, Correctly this time. https://www.paradisestation.org/wiki/index.php/Emergency_Response_Team
## Why / Balance

Makes it quicker to spawn ERT via the use of gamerules
Centers the ERT's arsenal around Energy Weaponry
Removes Pulse Rifles from main ERT's arsenal
Creates tiers of ERTs for different levels of threats.
## Technical details

YAML gaming
## Media

## Requirements

- [ ] I have tested all added content and changes.
- [ ] I have added media to this PR or it does not require an ingame showcase.

To do:
Guns
- [ ] IK-30 (For the Crew)
- [ ] PDW-9 Rework
- [ ] Advanced Energy Gun
- [ ] Multi Lens Immolater Cannon
- [ ] IK-60 Rework (ERT only)
Clothing
- [ ] ERT hardsuit rebalance
- [ ] Elite ERT hardsuits
Equipment
- [ ] Combat RCD
- [ ] Advanced Compact Defibrillator
- [ ] Universal Pinpointers targeting the Team Leader
- [ ] Holostretcher
- [ ] Medkits of Medical Chemicals
- [ ] Boxes of Mindshields
- [ ] Boxes of C4s
- [ ] Trash bags of holding
Spawning
- [ ] Gamerule for spawning ERT Pods
- [ ] Map of the actual pods for the ERT
- [ ] ERT Ghostroles

## Breaking changes

**Changelog**

:cl: Tryded
- add: Added the advanced energy gun which self-recharges and has two settings: Disable and Kill. This is researchable by science.
- tweak: There was a recent reorganization of the Emergency Response Teams by Nanotrasen.
DELTAVADMIN:
- add: Added new gamerules for spawning Emergency Response Teams. ERTs are now is different tiers which increases in this order: Amber, Red, Gamma.

2024-12-28 18:35 UTC, Avalon-Proto commented
I am already liking the sound of this

2024-12-28 19:04 UTC, Lyndomen commented
This is dope, let me meetwith the team to find out what types of ERT would be good to have prebaked

2024-12-28 19:44 UTC, Radezolid commented
While you're at it, make the ERT Engineer hardsuit fireproof please.

2024-12-28 21:39 UTC, Unkn0wnGh0st333 commented
If you need help mapping a ERT shuttle let me know

2024-12-30 21:59 UTC, Tryded commented
I have no idea why is it failing

2025-01-05 21:27 UTC, Lyndomen reviewed
Meowdy, taking this under direction review. From a technical perspective, it might be best to split this into 3 separate PRs- one adding advanced Defib, one overhauling guns, and the other adding ERT.

2025-01-29 19:10 UTC, Stop-Signs commented
Hi there! Direction update here, this PR is really cool and we are putting it on our priority list, we should have a decision on this within a few days, at most one week.

2025-01-31 23:27 UTC, Stop-Signs commented
Hey again, here with direction feedback! First of all we love this PR and think its fantastic, we have some slight concerns mainly about the weapons being changed/added.

Specifically, the IK carbine. We would like the IK carbine to be researchable, not orderable by cargo, and along with that we dont really see a reason to split it between the IK-30 and IK-60. Basically toss the IK-30 and put the IK-60 in its own research along with the ammo and magazines for it. Furthermore since its already full auto in its current iteration we would like it to have a full and semi auto fire mode. Other than that everything looks good.

Oh and in the description of these new guns you may consider not including the word "laser" for energy projectiles.

2025-01-31 23:43 UTC, Tryded commented
> Hey again, here with direction feedback! First of all we love this PR and think its fantastic, we have some slight concerns mainly about the weapons being changed/added.
> 
> Specifically, the IK carbine. We would like the IK carbine to be researchable, not orderable by cargo, and along with that we dont really see a reason to split it between the IK-30 and IK-60. Basically toss the IK-30 and put the IK-60 in its own research along with the ammo and magazines for it. Furthermore since its already full auto in its current iteration we would like it to have a full and semi auto fire mode. Other than that everything looks good.
> 
The main difference between IK-30 and IK-60 is that Ik-60 is ERT exclusive and better compared to Ik-30 as it has a 2 shot burst fire mode that acts a bit like the hyper fire mode of the AN-94. I might just make IK-30 researchable with full auto but give the special hyperburst to the IK-60

2025-01-31 23:48 UTC, Stop-Signs commented
That would be fine, we would like the ik-30 to remain similar to the current ik60

2025-02-01 03:30 UTC, Radezolid requested changes
Couple of notes for whenever you move to the `_DV` namespace:
- Comment out the ERT upstream backpacks to avoid repetition on the spawn menu.
- Remove the defibrillator PR from this one until it gets approved, meanwhile you can give them the `DefibrillatorCompact`.
- JSON needs four space indentation and perma links to commits where you took them from cited at the copyright.
- The ERT elite helmet icons are too small for our format, they look weird on the action bar.
- Fix the order of the id, parent and name. The correct order is: type` > `abstract` > `parent` > `id` > `name` > `description` > `components`.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Boxes/medical.yml
Add a end of file newline.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Boxes/medical.yml
> +  name: basic medicine bottle box
`name` should come after the ID.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Boxes/medical.yml
> +        amount: 2
Remove two spaces from the indentation.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Boxes/medical.yml
> +      - state: bottle
Same here, remove two spaces from the indentation.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Boxes/medical.yml
> +  parent: BoxCardboard
Inherit from the basic medicine box you made earlier to reduce repeated stuff like the description and sprite definition.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Boxes/security.yml
> +        amount: 4
Reduce the indentation by two spaces.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Cargo/cargo_armory.yml
Add an end of file newline

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Boxes/security.yml
> +      - id: C4
Reduce the indentation by two spaces along with the amount.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Boxes/security.yml
Add an end of file newline.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Boxes/security.yml
> +  id: BoxMindshield
Fix the order of these please.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Boxes/security.yml
> +  id: BoxC4
Fix the order.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/armory.yml
> +  parent: CrateWeaponSecure
Fix the order of these please.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/armory.yml
> +        amount: 4
Reduce the indentation by two spaces.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/armory.yml
> +  id: CrateArmoryLaserCarbine
`WeaponLaserCarbine` is the ID of the regular laser rifle, i recommend changing this to `CrateArmoryIK30`

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/armory.yml
Add a end of file newline.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Lockers/heads.yml
> +    - id: DefibrillatorCompactAdvanced # New Steal Objective
Untouch.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Locale/en-US/deltav/objectives/conditions/steal-target-groups.ftl
> +steal-target-groups-defibrillator-compact-advanced = advanced compact defibrillator
Untouch

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Catalog/Fills/Crates/armory.yml
> +  components:
This crate needs a name.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Clothing/Back/backpacks.yml
> +      - 0,0,7,6
Death squad is not used on DeltaV, so this is not needed.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Clothing/Head/hardsuit-helmets.yml
Create a base helmet and make them all inherit from it then per helmet edit their `sprite`, `clothing` and `PointLight` components.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Clothing/OuterClothing/hardsuits.yml
The non-elite hardsuits are not visually distict from their regular counterparts, either make them visually distinct or remove them.

On the elite ones: Make a base hardsuit then parent off them. All the descriptions are the same so they should be deleted as they are inherited already.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Mobs/Player/humanoid.yml
Fix the order of the proto fields and inherit from the upstream ones and do the modifications, too many repeated fields.
Also remove two spaces from the indentation under the `components:`.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Devices/door_remote.yml
> +    - AllAccess
Super door remote already exists, please remove this.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Specific/Medical/defib.yml
Delete this and any references towards it, add it back if it's PR gets accepted.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Specific/chemistry-bottles.yml
What's the purpose of these?
Also remove two indentation spaces from under `components:` and from the `tags:` one.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Tools/tools.yml
> +  name: Combat RCD #ERT
Fix the order of these.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/laser.yml
> +      - CartridgeLaser
Unident by two spaces.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/laser.yml
> +  parent: BaseCartridge
Fix the order of these.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/laser.yml
> +        map: [ "enum.AmmoVisualLayers.Base" ]
Unindent by two spaces.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Ammunition/Magazines/laser.yml
> +  parent: BaseItem
Fix the order of these.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Ammunition/Magazines/laser.yml
> +      - MagazineLaser
Remove two indentation spaces.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Ammunition/Magazines/laser.yml
> +        - CartridgeLaser
Remove two indentation spaces.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Ammunition/Magazines/laser.yml
> +    size: Small
Remove, this is already inherited from `BaseItem`.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +    - Belt
We lack sprites for these. And it makes no sense to store a energy gun in your belt.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  id: WeaponEnergyGunAdvanced
Fix the order of these

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +        shader: unshaded
Remove two indentation spaces.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  id: WeaponImmolator
Fix the order of these.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +        shader: unshaded
Remove two indentation spaces.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  id: WeaponImmolatorMulti
Fix the order of these, inherit from the `WeaponImmolator` and delete any repeated lines.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
Names should be in lowercase.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
> +  id: WeaponRifleLaser
Fix the order of these.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
> +        shader: unshaded
Remove two indentation spaces.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
> +            - CartridgeLaser
Remove two indentation spaces.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
> +  name: Ik-60
The K is in lowercase, should be uppercase.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
> +  id: WeaponRifleLaserERT
Fix the order of these.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Structures/Furniture/rollerbeds.yml
> +  name: holographic rollerbed
Fix the order of these.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Structures/Furniture/rollerbeds.yml
> +      size: Small
Inherited from `BaseItem`.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Structures/Furniture/rollerbeds.yml
> +    - type: Physics
Inherited from `BaseItem`.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Structures/Furniture/rollerbeds.yml
> +    - type: Pullable
Inherited from `BaseItem`.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Structures/Furniture/rollerbeds.yml
> +      price: 200
Remove two indentation spaces.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Structures/Furniture/rollerbeds.yml
> +
Prototypes should be separated by only one newline.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Objectives/stealTargetGroups.yml
Untouch

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Objectives/traitor.yml
Untouch

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/Research/arsenal.yml
> +
Remove these two spaces

2025-02-01 03:30 UTC, Radezolid commented on Resources/Textures/DeltaV/Objects/Weapons/Guns/Ammunition/Casings/laser_casing.rsi/meta.json
> +    "copyright": "Taken from https://github.com/ParadiseSS13/Paradise/pull/20602/commits/23f3d526c53a3733eba58328a0b4de7b824d7738, modified by Tryded",
Order should be `version` > `license` > `copyright`.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Textures/DeltaV/Objects/Weapons/Guns/Ammunition/Magazine/Energy/laser_mag.rsi/meta.json
> +    "copyright": "https://github.com/ParadiseSS13/Paradise/pull/20602/commits/23f3d526c53a3733eba58328a0b4de7b824d7738",
Order should be `version` > `license` > `copyright`.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
> +            - MagazineLaser
Remove two indentation spaces.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
> +        shader: unshaded
Remove this as it's mapping an unintended extra magazine.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
> +        map: ["enum.GunVisualLayers.Mag"]
Change this line to use the `["enum.GunVisualLayers.MagUnshaded"]` map so the magazine aligns properly.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
> +        shader: unshaded
Unindent by two spaces.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
> +        map: ["enum.GunVisualLayers.Mag"]
Remove this to fix the double magazine.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  - type: GunRequiresWield
You are missing the clothing component for it to show at the back.

2025-02-01 03:30 UTC, Radezolid commented on Resources/Prototypes/DeltaV/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +        collection: MeatLaserImpact
These need `[ HideSpawnMenu ]`.

2025-03-15 16:05 UTC, Avalon-Proto commented
@deltanedas and @ThataKat how's this looking

2025-03-15 16:19 UTC, ThataKat commented
Bwah, I was not in charge of this one but I will poke into the review post and see if what's happening

2025-03-15 16:40 UTC, Stop-Signs approved these changes
This looks like what we requested, direction is approving. @deltanedas please review.

2025-03-15 16:40 UTC, Stop-Signs commented on Resources/Prototypes/DeltaV/Research/arsenal.yml
> +  cost: 7500
Since this is a one-gun research in t2 id recommend making it only cost 5000.

2025-03-15 16:40 UTC, Stop-Signs commented on Resources/Prototypes/DeltaV/Entities/Clothing/OuterClothing/hardsuits.yml
> +      coefficients:
raise these resistances to 0.4 (60%) across the board, these guys are coming in on gamma so they should have good gear

2025-03-15 22:46 UTC, deltanedas commented
branch is fucked big time

2025-06-12 03:31 UTC, closed without merging