Chief Justice Clothes 2: The Second Coming of Drip
DeltaV-Station/Delta-v pull request #2558
Opened 2024-12-29 17:35 UTC by leonardo-dabepis

## About the PR

Makes it so the rest of the CJ clothes I sprited ages ago are now able to be used in the game.

## Why / Balance

I guess some time ago either I or someone else had forgotten to add code for the CJ mantle and robes- BUT I SHALL BARE THE CROSS as I do- I have added code for them and they are now accessible in loadouts and in the locker.

Also let me know if there's anything I need to do to have the mantle show up in whatever device prints mantles. I couldn't figure it out and I'm too tired to figure it out right now.

## Technical details

nah

## Media

![youre welcome for me existing](https://github.com/user-attachments/assets/ee637a16-6cb5-403f-b742-5afc0fb92fe5)

## Requirements

- [X] I have tested all added content and changes.
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- fix: made the rest of the CJ clothes usable/visible in game (this means more CJ drip)

2024-12-29 18:07 UTC, deltanedas requested changes
should have recipes in the uniform printer

2024-12-29 18:07 UTC, deltanedas commented on Resources/Prototypes/DeltaV/Entities/Clothing/Neck/mantles.yml
> +    sprite: DeltaV/Clothing/Neck/mantles/cjmantle.rsi
file missing newline at the end

2024-12-29 18:25 UTC, leonardo-dabepis commented
> should have recipes in the uniform printer

I looked and I didn't see any mantle recipes period so I think I had some sort of hallucination that mantles could be printed

2024-12-31 07:16 UTC, deltanedas approved these changes

2024-12-31 07:19 UTC, merged