The MultiPhase Energy Gun
DeltaV-Station/Delta-v pull request #385
Opened 2023-11-02 20:02 UTC by FluffiestFloof

## About the PR

The Head of Security special energy gun from TG.
If we want to, could recreate the other energy gun for other uses.

## Why / Balance

The Head of Security deserves funny toys and this one has _two_ firemode, using the same amount of shots as the TG version.
It can shoot disabler bolts and funny projectile lasers specifically made for it because hitscan lasers is sad.

Additionally, it is a steal objective similarly to TG. Good luck for that one.

## Technical details

For some unknown magical reason, I couldn't place my new projectiles into the DeltaV folders, it would just always error out and only work if I placed them directly in the base game files.
Why? _shrug_

The other big note is that while we have firemodes (provided by the CHIMP gun out of all places) it doesn't really change the sprite so it gets to stay red. The rest of the sprites are still there, if they ever get used, but at that point it should just get added to upstream properly alongside the energy guns.

## Media
https://github.com/DeltaV-Station/Delta-v/assets/9823203/537e7387-d45e-4747-bd47-bea59f7b6db0

## Breaking changes

**Changelog**

:cl:
- add: Added the X-01 MultiPhase Energy Gun for the HoS.

2023-11-02 21:03 UTC, Carolyn3114 commented
this is awesome, I love how it's the first projectile laser gun

2023-11-02 22:13 UTC, ps3moira commented
Finally! HoS has their own gun now :)

2023-11-02 23:16 UTC, Adrian16199 commented
Is it me or did the laser loose 10 magazine shots mid firing.

2023-11-02 23:23 UTC, ps3moira commented
> Is it me or did the laser loose 10 magazine shots mid firing.

Pretty sure that's how it is in SS13, lethal shots cost 10 laser energy. Prevents people from spam swapping firing modes.

2023-11-03 00:04 UTC, FluffiestFloof commented
> Is it me or did the laser loose 10 magazine shots mid firing.

It's because when you change firemode and start shooting it updates the "total amount of shots you can have with this firemode"
If you stay with the disable mode it has 20 shots, if you stay with the lethal mode it has 10 shots.
So you could shoot 5 lethal then 10 disabler

2023-11-03 01:47 UTC, ps3moira commented
I think you could copy the code from Stun baton when swapping sprites for disable and lethal mode

2023-11-04 00:48 UTC, DebugOk commented
Funni big update

2023-11-06 01:49 UTC, Tryded commented
We should probably add energy guns with this PR since it adds the code to do it

2023-11-06 02:18 UTC, FluffiestFloof commented
> We should probably add energy guns with this PR since it adds the code to do it

The main question is what will we do with them? At best Captain could get it but they already have their laser pistol and we don't want them to be roundstart from what was discussed in discord.

2023-11-06 23:06 UTC, DEATHB4DEFEAT requested changes, later dismissed

2023-11-06 23:06 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/Weapons/Ranged/Components/EnergyGunComponent.cs
> +/// </summary>
```suggestion
/// <summary>
/// Allows for energy gun to switch between lethal and disable. This also changes sprites accordingly.
/// </summary>
/// <remarks>Yes this is a mashup of the StunbatonSystem and BatteryWeaponFireModesSystem</remarks>
```

2023-11-06 23:06 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/Weapons/Ranged/Systems/EnergyGunSystem.cs
This should be usable for more than just "guns that can either disable or kill at a moment's notice"

2023-11-06 23:06 UTC, DEATHB4DEFEAT commented on Resources/Audio/DeltaV/license.txt
> +dry_fire.ogg and laser.ogg both from tgstation at commit https://github.com/tgstation/tgstation/commit/2532911353d63661b735004f2895103d45858b50
Link to the files in the tree, commit unrelated.

2023-11-06 23:06 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/DeltaV/Objectives/traitor.yml
> +    difficulty: 3
```suggestion
    difficulty: 3 # HoS will mostly be using the gun to stop you from stealing it
```

2023-11-06 23:06 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +# For whatever magical reasons, I cannot put those in the DeltaV folders without having errors.
Weird

2023-11-06 23:06 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/meta.json
> +  "copyright": "taken from tg station at commit https://github.com/tgstation/tgstation/commit/8b7f8ba6a3327c7381967c550f185dffafd11a57",
Link to file(s) in tree, commit seems unrelated.

2023-11-06 23:06 UTC, DEATHB4DEFEAT commented on Resources/Textures/DeltaV/Objects/Weapons/Guns/Battery/multiphase_energygun.rsi/meta.json
> +            ]
```suggestion
            "delays": [[ 0.3, 0.3 ]]
```

2023-11-06 23:09 UTC, Tryded commented
> > We should probably add energy guns with this PR since it adds the code to do it
> 
> The main question is what will we do with them? At best Captain could get it but they already have their laser pistol and we don't want them to be roundstart nor give it to HoP from what was discussed in discord .

We could make it orderable from cargo and researchable

2023-11-07 09:11 UTC, FluffiestFloof commented on Content.Server/DeltaV/Weapons/Ranged/Systems/EnergyGunSystem.cs
Yeah that would be a good idea, sadly that would require way more code thing that I'm not smart enough to do.

2023-11-09 22:32 UTC, Carolyn3114 commented
vid 4 normal energy gun where

2023-11-09 22:43 UTC, Tryded commented
> > We should probably add energy guns with this PR since it adds the code to do it
> 
> The main question is what will we do with them? At best Captain could get it but they already have their laser pistol and we don't want them to be roundstart nor give it to HoP from what was discussed in discord .

Also, when you say roundstart, do you mean it spawns in their bag? The normal energy gun should take up as much space as an laser carbine and some should spawn in the armory if you meant what I said.

2023-11-09 22:44 UTC, Tryded commented
Also to compensate with lasers being worse than energy guns, lasers should get 19 rounds of fire instead of 16

2023-11-15 17:26 UTC, DebugOk approved these changes
I'm sure it'll be fine.

It should still be made into a more generic system imo, but this'll do

2023-11-15 18:40 UTC, DebugOk commented
Fuck it, we ball

2023-11-15 18:41 UTC, merged