Shitcode for vpn detection
DeltaV-Station/Delta-v pull request #392
Opened 2023-11-03 20:22 UTC by DebugOk

Something something bad code. I'm only making this a pr so I can hopefully get reviews as I finish it

2023-11-03 20:22 UTC, DebugOk commented
@DEATHB4DEFEAT if you have time, can you please take a quick look at this? I'm still working on it

2023-11-03 20:24 UTC, DebugOk commented
I'm going to rewrite the client thing at some point but for now I just used example code :clueless:

2023-11-05 12:27 UTC, OCOtheOmega commented
I'm very interested in this pr, so can I ask that you add the ability to whitelist players who don't need to be checked? Not IP addresses, but the players themselves.

2023-11-05 14:53 UTC, DebugOk commented
> I'm very interested in this pr, so can I ask that you add the ability to whitelist players who don't need to be checked? Not IP addresses, but the players themselves.

I modified part of the code so that the bans it applies are marked as datacenter bans. There is a command along the lines of ban_exempt_update that you can use to apply an exclusion to a player. I just need to make it double check during the initial connect so it doesn't deny

2023-11-06 22:36 UTC, DEATHB4DEFEAT commented
This would be great to have as a thing upstream ~~for them to maintain for us~~.
There are no downstream change markers anywhere, do you want them?

2023-11-06 22:52 UTC, DEATHB4DEFEAT requested changes

2023-11-06 22:52 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/ProxyDetection/NeutrinoApi/ApiErrorCode.cs
> +    public const int ApiGatewayError = 71;
I feel like there's a better way to store this

2023-11-06 22:52 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/ProxyDetection/NeutrinoApi/ApiResponse.cs
> +    }
This is indented a tab too much

2023-11-06 22:52 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/ProxyDetection/NeutrinoApi/ApiResponse.cs
> +        }
Blank xmldoc arg comments

2023-11-06 22:52 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/ProxyDetection/DetectionManager.cs
> +    private NeutrinoApiClient _neutrinoApiClient = default!;
```suggestion
    private ISawmill _sawmill = default!;
    private NeutrinoApiClient _neutrinoApiClient = default!;

    private bool _shouldProbe;
    private bool _apiValid;
```

2023-11-06 22:52 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/ProxyDetection/DetectionManager.cs
> +                return;
This exactly probably won't work, but these ifs can be compacted to one
```suggestion
        if (_cfg.GetCVar(DCCVars.BlockProxyConnections) &&
            !(_cfg.GetCVar(DCCVars.ProxyApiKey) == "" || _cfg.GetCVar(DCCVars.ProxyApiUser) == ""))
```

2023-11-06 22:52 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/ProxyDetection/NeutrinoApi/NeutrinoApiClient.cs
> +    {
Blank xmldoc arg comments

2023-11-06 22:52 UTC, DEATHB4DEFEAT commented on Content.Server/DeltaV/ProxyDetection/NeutrinoApi/NeutrinoApiClient.cs
> +            var contentType = response.Content.Headers.ContentType?.ToString();
```suggestion
            using var request = new HttpRequestMessage();
            request.Method = new HttpMethod(httpMethod.Equals("POST") ? "POST" : "GET");
            request.RequestUri = new Uri(url);
            request.Content = httpMethod.Equals("POST") ? encodedParams : null;

            using var cancellationToken = new CancellationTokenSource(TimeSpan.FromSeconds(timeoutInSeconds));
            using var response = await Client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead,
                cancellationToken.Token);

            var content = await response.Content.ReadAsStringAsync(cancellationToken.Token);
            var statusCode = (int) response.StatusCode;
            var contentType = response.Content.Headers.ContentType?.ToString();
```

2023-12-29 19:35 UTC, closed without merging