Implementing Height Sliders
DeltaV-Station/Delta-v pull request #471
Opened 2023-11-23 06:48 UTC by evilexecutive

## About the PR
This PR adds the new Height Slider feature from Cosmatic Drift, coded by @LankLTE from Wizden.

## Why / Balance
I've spent about 4 hours playing in the new Cosmatic Drift server, and this feature was too awesome not to port. As an side, Gunnar McDorf now finally gets to be short. 

## Technical details
Height references:
Humans, Vulpakin, Diona, Arachnid, Moth, Reptillian, Slimes: 4'6" to 7'
Felinids: 3' 10" to 4' 4"
Harpies: 4'8" to 5' 2"
Oni: 7'3 to 8'

## Media
![image](https://github.com/DeltaV-Station/Delta-v/assets/16548818/d00fb6a6-4231-4551-8fcb-e89c7cdcd20d)

## Breaking changes
**Changelog**
:cl: LankLTE & VMSolidus
- add: Height Sliders have now been ported to DeltaV
- tweak: Dwarfs are no longer required to receive leg extensions at Centcomm prior to entering the station.

2023-11-23 07:43 UTC, DebugOk requested changes
Sounds like sprite squishing with extra steps. Doing this so it can't be merged until I've had a look at it

2023-11-23 07:44 UTC, LankLTE commented
Scale width / height is true by default, so you don't need to worry about defining it for each species.

2023-11-23 07:48 UTC, DebugOk requested changes

2023-11-23 07:48 UTC, DebugOk commented on Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
> +  #- type: Hunger # DeltaV - Disable starvation damage
Why is this being removed

2023-11-23 07:48 UTC, DebugOk commented on Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
> -  components:
No comment

2023-11-23 07:48 UTC, DebugOk commented on Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
>    - type: Body
No comment

2023-11-23 07:48 UTC, DebugOk commented on error.txt
Why does this exist

2023-11-23 07:48 UTC, DebugOk commented on Content.Client/Humanoid/HumanoidAppearanceSystem.cs
> +        var speciesPrototype = _prototypeManager.Index<SpeciesPrototype>(component.Species);
Too many changes without any comments to add a review on all

2023-11-23 07:49 UTC, LankLTE commented
> Sounds like sprite squishing with extra steps. Doing this so it can't be merged until I've had a look at it

Not sure exactly what you mean by this, but it's modified the same way as species are currently (uniformly modifying the scale on the SpriteComponent) so I don't see why it'd be a huge deal

2023-11-23 07:52 UTC, DebugOk commented
> > Sounds like sprite squishing with extra steps. Doing this so it can't be merged until I've had a look at it
> 
> Not sure exactly what you mean by this, but it's modified the same way as species are currently (uniformly modifying the scale on the SpriteComponent) so I don't see why it'd be a huge deal

Scaling one axis but not the other. I personally think it looks horrible and don't want to see it on player characters

2023-11-23 07:54 UTC, LankLTE commented
> Scaling one axis but not the other. I personally think it looks horrible and don't want to see it on player characters 

I agree it looks terrible, and for that reason it's disabled by default. It's only supported for species like dwarves to be able to exist as they do currently. This PR doesn't apply it to any species- they're all scaled uniformly.

2023-11-23 08:11 UTC, deltanedas commented on Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
> +  #- type: Hunger # DeltaV - Disable starvation damage
branch troll probably

2023-11-23 09:05 UTC, Adrian16199 commented
Im gonna give my cookie on it, I like the idea if the minimum height would be human size on all species besides harpies and felinid only because they are smaller by default. I would love to see bigger humans even if it would cost them bigger hitbox just for a roleplay thing, I would not accept this if it could allow a human to be even smaller in any sort of way for powergaming needs.

2023-11-23 09:18 UTC, Adrian16199 commented
Which brings me a question..... due to size bein kinda of a factor regardin if you can easily shove someone or not, does this apply here? I would love to see a video regardin the highest human tryin to shove a normal size one.

2023-11-23 17:05 UTC, VMSolidus commented on error.txt
Small mistake I chalk up to coding at 2 AM in the morning. When building, I run dotnet build > error.txt because I actually like being able to read and/or search the errors when it finishes.

2023-11-23 17:08 UTC, evilexecutive commented
So MassContest doesn't actually care about what a Species scale is, which is a common misconception because all three of the species we have with different mass also have a different scale. MassContests actually check a species FixturesComponent, which lists a Density stat. This PR doesn't change anyone's Density stat, so no matter what you scale an Oni or a Felinid to, they still have the same mass for the purpose of their shoving/dragging. 

Per discussion I'm going to open up the Maximums a little for some of the species, and tighten up the minimums for all the basic humanoids except for Human(who we want to keep solely because it'll get the dwarf fans to stop complaining that we don't have dwarfs)

2023-11-23 17:12 UTC, evilexecutive commented
Damnit there are so many scuffed changes to the core files due to how I merged them(manually moving files from one repo to another) that I basically need to start over with them from scratch and merge them CORRECTLY. That way I can see our changes and make sure we keep what we need to keep, and comment what came from @LankLTE

2023-12-03 20:50 UTC, VMSolidus commented
Yea so I'm going to close this, because I straight up don't have the skill needed to maintain a feature like this, and it touches entirely too much Wizden code for my or Debug's comfort. I am miserly with touching Wizden code, and I feel bad if I have to change one or two lines. This changes nearly 3000 lines of Wizden code.

2023-12-03 20:50 UTC, closed without merging