Add Crusher Glaive to the Salvage Vendor
DeltaV-Station/Delta-v pull request #493
Opened 2023-11-30 23:08 UTC by AeraAuling

## About the PR
Added two Crusher Glaives to the salvage vendor

## Why / Balance
Added because Crusher Glaives are nice, basically. They are otherwise fairly identical to regular crushers. Readding them to the vendor should also allow for some visual variety and a bit of added flavor with salvage's choice of weaponry.

## Technical details
This touches the file at /Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml otherwise not much else is changed.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
![image](https://github.com/DeltaV-Station/Delta-v/assets/133451603/52c50ba4-bc44-464c-ad98-2b1ebca669a2)

## Breaking changes

N/A
**Changelog**

-Adds Crusher Glaives to the salvage vendor, finally bringing proper polearms to the delta sector.

2023-12-01 23:25 UTC, Colin-Tel requested changes

2023-12-01 23:25 UTC, Colin-Tel commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/salvage.yml
> +    WeaponCrusherGlaive: 2
```suggestion
    WeaponCrusherGlaive: 2 # DeltaV
```

2023-12-01 23:25 UTC, Colin-Tel commented
Why isn't this already in? Is it because of balance?

2023-12-01 23:44 UTC, Adrian16199 commented
> Why isn't this already in? Is it because of balance?

I believe the reason is the fact that it is basicly the crusher but diferent look.
No diferent stats.

2023-12-01 23:53 UTC, IamVelcroboy commented
Are these items supposed to be research locked?

2023-12-01 23:53 UTC, IamVelcroboy commented
Or...should they be?

2023-12-02 00:09 UTC, FluffiestFloof commented
> > Why isn't this already in? Is it because of balance?
> 
> I believe the reason is the fact that it is basicly the crusher but diferent look. No diferent stats.

They heal more damage when you hit a marked enemy
Crusher:
https://github.com/DeltaV-Station/Delta-v/blob/2fa1a61913e4e819edde09973e00a6d2936fcf88/Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml#L30-L33
Glaive:
https://github.com/DeltaV-Station/Delta-v/blob/2fa1a61913e4e819edde09973e00a6d2936fcf88/Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml#L105-L108

They have a faster melee attack speed
Crusher:
https://github.com/DeltaV-Station/Delta-v/blob/2fa1a61913e4e819edde09973e00a6d2936fcf88/Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml#L46-L51
Glaive:
https://github.com/DeltaV-Station/Delta-v/blob/2fa1a61913e4e819edde09973e00a6d2936fcf88/Resources/Prototypes/Entities/Objects/Weapons/Melee/mining.yml#L111-L113

2023-12-02 00:26 UTC, Colin-Tel commented
> Or...should they be?

I'd be more inclined to say that these should be research locked rather than have these available at the same time the objectively worse equipment is as well.

2023-12-02 02:05 UTC, AeraAuling commented
> > Or...should they be?
> 
> I'd be more inclined to say that these should be research locked rather than have these available at the same time the objectively worse equipment is as well.

I suppose they could be researched too yeah. I, did not know about the more health but I will say the slightly faster attack speed doesn't play out that much in practice. They attack at about the same rate when using the shot and strike.

2023-12-02 14:07 UTC, DebugOk commented
> Why isn't this already in? Is it because of balance?

I don't think these should be in until Wizden adds them, especially not as something available roundstart

2023-12-02 15:12 UTC, deltanedas commented
since its better in every way i think it should be in salvage tech, and probably upstreamed

2023-12-29 19:51 UTC, closed without merging