Straw hat
DeltaV-Station/Delta-v pull request #527
Opened 2023-12-07 11:46 UTC by Adrian16199

Farmer's best friend. (totally)

TO-DO: Make it craftable to be wheat, probably need a special tag.... eh= Done

We did it boys.

## About the PR

Hat
## Why / Balance

Botany deserves love.
## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/51888e9b-4e02-42d9-8770-b64f76e23a58)
![image](https://github.com/DeltaV-Station/Delta-v/assets/144424013/e5c5d1cf-1be2-436a-ba1d-cb633da31b87)

**Changelog**

Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Crew has learned how to make a straw hat out of wheat bushels!

2023-12-08 22:51 UTC, Colin-Tel commented
YAML linter is failing. Is it because you put hyphens before “tag” in the crafting graph?

Also your changelog won’t get added to the changelog because it’s formatted improperly. Was this intentional?

2023-12-09 09:06 UTC, Adrian16199 commented
Im pretty sure I fixed the changelog but I have no idea what is wrong with the yaml linter. I checked every single file and compared it to diferent files, only thing that I can imagine being wrong is either one too many spaces or one too little.

2023-12-09 09:55 UTC, deltanedas commented
learned not learnt :trollface:

add a space between `-tag` so its `- tag`

2023-12-09 10:09 UTC, Adrian16199 commented
I sure do love spacing. Ingame and in coding.

2023-12-10 13:48 UTC, Colin-Tel requested changes
Some grammar/capitalization to address

2023-12-10 13:48 UTC, Colin-Tel commented on Resources/Prototypes/DeltaV/Recipes/Crafting/improvised.yml
> +  name: Straw hat
```suggestion
  name: straw hat
```

2023-12-10 13:48 UTC, Colin-Tel commented on Resources/Prototypes/DeltaV/Entities/Clothing/Head/hats.yml
> +  name: Straw hat
```suggestion
  name: straw hat
```

2023-12-10 13:48 UTC, Colin-Tel commented on Resources/Prototypes/DeltaV/Entities/Clothing/Head/hats.yml
> +  description: A fancy hat for hot days, not recommended next to fires.
```suggestion
  description: A fancy hat for hot days! Not recommended to wear near fires.
```
I’m on phone so I can’t do a multi line review comment 😭

2023-12-10 13:48 UTC, Colin-Tel commented on Resources/Prototypes/DeltaV/Recipes/Crafting/improvised.yml
> +  description: A fancy hat for hot days, not recommended next to fires.
```suggestion
  description: A fancy hat for hot days! Not recommended to wear near fires.
```

2023-12-10 13:57 UTC, Adrian16199 commented
Still works after changes so definitely nice.

2023-12-13 20:13 UTC, Colin-Tel approved these changes

2023-12-13 20:13 UTC, merged