Laika changes
DeltaV-Station/Delta-v pull request #602
Opened 2023-12-26 11:24 UTC by BramvanZijp

## About the PR
This PR gives laika (Aswell as other security dogs) a few upgrades, namely an ID card & headset slot, both of which start filled for laika, buffed attacks and the ability to drag without needing hands. (Dogs do not have those)

## Why / Balance
Laika feels underpowered offensively, and being unable to so much as open maintenence doors can really get annoying.

## Technical details

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2023-12-26 12:05 UTC, leonardo-dabepis commented
I don't see the need for Laika to have a headset, but the rest is alright in my opinion. The attack buff may also be a bit much but idk.

2023-12-27 17:57 UTC, Colin-Tel requested changes
Changelog entries shouldn't exceed one or two in number.

2023-12-28 09:22 UTC, Colin-Tel submitted a review, later dismissed

2023-12-28 09:24 UTC, Colin-Tel commented on Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
> +- type: entity
```suggestion
- type: entity # DeltaV - Security dog Laika ID card
```

2023-12-28 09:32 UTC, merged