Salvage cloak
DeltaV-Station/Delta-v pull request #631
Opened 2024-01-01 17:57 UTC by lleftTheDragon

## About the PR
Gave the Salvage cloak back to salvage, it rarely spawns in the locker and also should spawn in the salvage crates on salvages.

## Why / Balance
Added this awhile back, same reason as then. Wanted to give salvage their own cloak outside of the mining cloak as salvage isn't just about mining
 

## Media
![Screenshot_798](https://github.com/DeltaV-Station/Delta-v/assets/125433431/8bb6fdca-5959-4f76-bd95-1c18b72fe5d1)
![Screenshot_799](https://github.com/DeltaV-Station/Delta-v/assets/125433431/b091a98a-ddd5-42cc-973b-d9407f77d650)
![Screenshot_800](https://github.com/DeltaV-Station/Delta-v/assets/125433431/000fa39d-c751-4133-8775-b120790e4f7d)
![Screenshot_801](https://github.com/DeltaV-Station/Delta-v/assets/125433431/adbb1e66-6178-4a42-978a-da59dcec0445)

- [ x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- Added Salvage cloak

2024-01-01 21:53 UTC, Colin-Tel requested changes
Move the `salvage.rsi` folder into the same directory under `Textures/DeltaV/...`, also fix the errors in regards to the incorrect filename `equipped-NECK3.png`

2024-01-01 21:53 UTC, Colin-Tel commented on Resources/Prototypes/Entities/Clothing/Neck/cloaks.yml
> +    sprite: Clothing/Neck/Cloaks/salvage.rsi
This should be under `DeltaV/Clothing/...`

2024-01-01 21:53 UTC, Colin-Tel commented on Resources/Textures/Clothing/Neck/Cloaks/salvage.rsi/equipped-NECK3.png
What's the purpose of the `3` in the filename? If it needs to be there, then it needs to be present when you reference this file, hence the errors.

2024-01-01 22:56 UTC, lleftTheDragon commented on Resources/Textures/Clothing/Neck/Cloaks/salvage.rsi/equipped-NECK3.png
Fixed it, it was a hold over my B

2024-01-02 22:12 UTC, Colin-Tel commented on Resources/Prototypes/Entities/Clothing/Neck/cloaks.yml
Reverting any changes to this file will resolve some of the errors, maybe all of them.

2024-01-03 07:13 UTC, lleftTheDragon commented on Resources/Prototypes/Entities/Clothing/Neck/cloaks.yml
I Directly remember removing this code, i guess it didnt stick or i removed the change before comitting it? Either way fixed it


> Reverting any changes to this file will resolve some of the errors, maybe all of them.

2024-01-07 18:30 UTC, Colin-Tel commented on Resources/Prototypes/Catalog/Fills/Crates/salvage.yml
> +      - id: ClothingNeckSalvager
```suggestion
      - id: ClothingNeckSalvager # DeltaV - salvage cloak
```

2024-01-07 18:30 UTC, Colin-Tel commented on Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
> +      - id: ClothingNeckSalvager
```suggestion
      - id: ClothingNeckSalvager # DeltaV - salvage cloak
```

2024-01-07 18:30 UTC, Colin-Tel commented on Resources/Prototypes/Catalog/Fills/Lockers/cargo.yml
> +      - id: ClothingNeckSalvager
```suggestion
      - id: ClothingNeckSalvager # DeltaV - salvage cloak
```

2024-01-19 21:06 UTC, merged