SlowOnDamage lessened + Moth buff
DeltaV-Station/Delta-v pull request #741
Opened 2024-01-31 03:17 UTC by OldDanceJacket

## The Changes Are:
SlowOnDamage values changed from
_60dmg 0.7 -> 0.8
80dmg 0.5 -> 0.6_

Moth Heat weakness lessened from
_4.5 -> 1.5_

## Why / Balance
SlowOnDamage values are changed to the much older Nyano balance changes, this was one of the most well received balance changes, it is a simple change in speed but helps assist in making death spiral moments feel considerably better. Players have a number of sources to be slowed down by already, and this allows melee combat to be a bit more engaging.

~

Moth heat weakness used to be 2, for some reason it's cranked up to 4.5 of all things. Players would complain about the old 2 modifier, and with how damage is dealt with Heat currently this means there's some comical ways to take out Moth players. A 1.5 weakness is still **plenty** but should allow the on fire moth a little bit more wiggle room in having someone douse them if they catch fire. _(Or when getting shot at by a laser gun...)_

~

These changes are bundled together due to being both simple yml changes in the same folder, as well as also balance changes of a similar vein (improving the play experience of the players)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl: ODJ
- tweak: Moth's now take 150% heat dmg instead of 450%
- tweak: You now move a little faster when hurt than previously

2024-01-31 04:22 UTC, OldDanceJacket commented
Wouldn't be a pr if there wasn't a test failure

2024-01-31 14:17 UTC, FluffiestFloof commented
I'm pretty sure that the default MobFlammable (aka anyone) is 3 while on fire so wouldn't giving Moth 1.5 make them less flammable?

2024-01-31 18:29 UTC, DebugOk requested changes
This is actually making moths take *less* damage, as by default you already take 3 heat damage per fire stack.

https://github.com/DeltaV-Station/Delta-v/blob/369109dcd0c975289b414629bd929e53ba67bd4b/Resources/Prototypes/Entities/Mobs/base.yml#L167-L181

Additionally, the damage slowdown changes are lacking change markers

2024-01-31 19:59 UTC, DebugOk requested changes
Also fix your changelog entries

2024-01-31 19:59 UTC, DebugOk commented on Resources/Prototypes/Entities/Mobs/Species/base.yml
> +      80: 0.6 # DV - Was 0.6
```suggestion
      80: 0.6 # DV - Was 0.5
```

2024-01-31 19:59 UTC, DebugOk commented on Resources/Prototypes/Entities/Mobs/Species/moth.yml
> +        Heat: 4 # moths burn more easily
```suggestion
        Heat: 4 # DV - Reduced by .5
```

2024-02-01 18:11 UTC, DebugOk approved these changes

2024-02-01 18:34 UTC, merged