Barrels & Kegs
DeltaV-Station/Delta-v pull request #829
Opened 2024-02-13 10:18 UTC by rosieposieeee

<img width="474" alt="Content Client_zLYlCAzqcC" src="https://github.com/DeltaV-Station/Delta-v/assets/52761126/e59c60f5-13c9-47f3-8aab-8380054967c6">

## About the PR

Added barrels and kegs. Fully constructible and deconstructible, though I couldn't figure out how to make kegs spill their contents when deconstructed, so I'd like some help with that. Base sprites from [tgstation](https://github.com/tgstation/tgstation/pull/38977) and I added the little keg though if someone wants to do that better, I'm all for it. (I'm terrible at pixel art.)

Regular barrel acts like a crate, keg acts like a tank. Keg was set to 500 volume; not sure if this is balanced, but I felt like it needed to be larger than jugs, but not as large as tanks (which are 1500). They can be constructed with 5 wood (a la crates), but that can be increased if necessary. I made the top of the collider have a little leeway so that you can look like you're on top just for fun.

## Why / Balance

For decoration, and for the bartender to have a keg to drag around that ISN'T identical to a nuke.

**Changelog**
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Added wooden barrels and kegs.

2024-02-13 15:31 UTC, IamVelcroboy requested changes

2024-02-13 15:31 UTC, IamVelcroboy commented on Resources/Prototypes/DeltaV/Recipes/Crafting/Graphs/barrel.yml
> +
Minor gripe, but keep line spacing consistent.

2024-02-13 15:31 UTC, IamVelcroboy commented on Resources/Prototypes/DeltaV/Recipes/Crafting/Graphs/barrel.yml
> +
And here

2024-02-13 21:39 UTC, VMSolidus approved these changes, later dismissed
I loooooooove these. I'm really excited to see what mappers will do with these.

2024-02-16 23:26 UTC, VMSolidus approved these changes, later dismissed

2024-02-27 13:05 UTC, closed without merging