Revert ambuzol recipe change
DeltaV-Station/Delta-v pull request #873
Opened 2024-02-20 15:26 UTC by stellar-novas

## About the PR

Reverts the change to make Ambuzol require ZombieBlood and AmbuzolPlus to require Omnizine.

## Why / Balance

The change was made upstream as a counter to powergaming by making Ambuzol early on, before any sign of zombies. This is not an issue on Delta-V, and most zombie rounds currently end with a crew loss, this change makes it even more difficult for the crew.

## Technical details

N/A

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

N/A

**Changelog**

:cl:
- tweak: Upstream Ambuzol recipe changes have been reverted.

2024-02-20 16:06 UTC, Adrian16199 commented on Resources/Prototypes/Recipes/Reactions/medicine.yml
> +    Blood:
```suggestion
    Blood:  # Delta V - Reverts "ambuzol beef 25119"
```

2024-02-20 16:06 UTC, Adrian16199 commented on Resources/Prototypes/Recipes/Reactions/medicine.yml
> +    ZombieBlood:
```suggestion
    ZombieBlood:  # Delta V - Reverts "ambuzol beef 25119"
```

2024-02-20 16:27 UTC, stellar-novas commented
Guh I forgot these were upstream files, I'll go back and add markers

2024-02-20 18:16 UTC, stellar-novas commented
Added a marker, though is it needed? This is equivalent to never merging the commit in the first place, and markers are not added for those.

2024-02-20 18:20 UTC, Adrian16199 commented
> Added a marker, though is it needed? This is equivalent to never merging the commit in the first place, and markers are not added for those.

I mean, adding a note helps a merger or anyone lookin there and see:
Oh wait, this is different compared to wizden!
Instead of:
What a weird thing, I dont recall this being in wizden but no note regardin it.

2024-02-23 18:31 UTC, DebugOk requested changes

2024-02-23 18:31 UTC, DebugOk commented on Resources/Prototypes/Recipes/Reactions/medicine.yml
> +# This code is licensed under AGPLv3. See LICENSE
No point in having this here

2024-02-23 18:31 UTC, DebugOk commented on Resources/Prototypes/Recipes/Reactions/medicine.yml
> +# This code is licensed under AGPLv3. See LICENSE
Referring to line 211

2024-02-23 21:38 UTC, stellar-novas commented on Resources/Prototypes/Recipes/Reactions/medicine.yml
> +# This code is licensed under AGPLv3. See LICENSE
Removed it

2024-03-07 20:52 UTC, closed without merging