Add Corspman Access & Airlocks
DeltaV-Station/Delta-v pull request #892
Opened 2024-02-23 18:21 UTC by rosieposieeee

## About the PR

<img width="524" alt="Content Client_AQ40yzRyFY" src="https://github.com/DeltaV-Station/Delta-v/assets/52761126/eb18fc39-4cba-4d4d-8ea5-25c5aedb1e34">

"""Corpsman""" access previously was just medical access on their locker (lol!) and NO access on their suit locker (LOL)
Also added the Mantis maints airlock while I'm at it from, so it "Fixes https://github.com/DeltaV-Station/Delta-v/issues/891".

Tested and works. HoS was given the access too. Warden left out.
I know this could easily be done upstream, but they denied my paramedic airlock PR so I don't think they'd care for this one.

**Changelog**
:cl:
- add: Added Corpsman-only access, and a Mantis-only maintenance airlock.

2024-02-23 18:22 UTC, DangerRevolution commented
PR should say "Fixes #891" so the issue is autoclosed on merge :)

2024-02-23 18:24 UTC, rosieposieeee commented
> PR should say "Fixes #891" so the issue is autoclosed on merge :)

ok lol i dont know how literal that is so i've just added that wholecloth

2024-02-23 18:27 UTC, DebugOk commented
2 unrelated things in the same pr, no attempt at upstreaming it and they don't need a seperate access type. Medical + security is enough.

2024-02-23 18:32 UTC, DangerRevolution commented
> they don't need a seperate access type. Medical + security is enough.

if a doctor gets into security they can just open Corpsman locker, as it's just a medical access locker? on the other way around, a security officer with medical access can just get into their locker. I've gotten Medical access a few times as Sec, doesn't mean I should be able to just go into the Corpsman's area and rob their shit

>2 unrelated things in the same pr, no attempt at upstreaming it

Wizden doesn't have Mantis, nor Corpsman

2024-02-23 18:49 UTC, IamVelcroboy commented
> they don't need a seperate access type. Medical + security is enough.

I kinda disagree. I'm always going to push for better granular access types. The current med+sec access makes for some weird mapping setups on some maps where sec has access to corpsman's stuff or med has access to corpsman's room. This would allow for better control/less wonky mapping setups. 

Also, as pointed out, WD does not have a brig medic/corpsman role any more. It was removed.

2024-02-24 01:07 UTC, rosieposieeee commented
![image](https://github.com/DeltaV-Station/Delta-v/assets/52761126/80ba75f4-cbd1-4a12-ae77-1702f1eb8307)

it took a beautiful and vindicating 3 minutes for upstream to close it. 

![image](https://github.com/DeltaV-Station/Delta-v/assets/52761126/96a78148-c6c0-4f3a-8295-241ccc370e1e)


> 2 unrelated things

its two airlocks.

2024-02-24 02:00 UTC, DebugOk commented
I would argue with Sloth's logic but there really isn't a point

2024-02-24 02:01 UTC, DebugOk requested changes

2024-02-24 02:01 UTC, DebugOk commented on Resources/Prototypes/DeltaV/Entities/Structures/Doors/Airlocks/access.yml
> +  parent: AirlockMaintRnDLocked
Unrelated to this pr

2024-03-19 11:43 UTC, DebugOk requested changes
You also have to add the access here https://github.com/DeltaV-Station/Delta-v/blob/master/Content.Shared/Access/Components/IdCardConsoleComponent.cs#L44-L89 or no one can assign it

2024-03-19 11:44 UTC, DebugOk commented
> You also have to add the access here https://github.com/DeltaV-Station/Delta-v/blob/master/Content.Shared/Access/Components/IdCardConsoleComponent.cs#L44-L89 or no one can assign it

and [here](https://github.com/DeltaV-Station/Delta-v/blob/master/Resources/Prototypes/Entities/Objects/Tools/access_configurator.yml#L20-L59)

2024-03-19 11:50 UTC, rosieposieeee commented
gah, i always forget somewhere

2024-03-19 12:13 UTC, DebugOk approved these changes

2024-03-19 12:13 UTC, merged