Replace RD mentions with Mystagogue
DeltaV-Station/Delta-v pull request #893
Opened 2024-02-23 18:46 UTC by FluffiestFloof

## About the PR

Fixes #890 
Also the potted plant.

2024-02-23 21:39 UTC, DEATHB4DEFEAT requested changes

2024-02-23 21:39 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Entities/Objects/Misc/bedsheets.yml
> +  # End of modified code
```suggestion
  name: Mystagogue's bedsheet # DeltaV - Epistemics Department - Replace Research Director with Mystagogue
```

2024-02-23 21:39 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Objectives/stealTargetGroups.yml
> +  # End of modified code
```suggestion
  name: Mystagogue's potted plant # DeltaV - Epistemics Department - Replace Research Director with Mystagogue
```

2024-02-23 21:41 UTC, FluffiestFloof commented
Do we just not use the new markers?

2024-02-23 21:46 UTC, DEATHB4DEFEAT approved these changes

2024-02-24 22:40 UTC, VMSolidus approved these changes

2024-03-05 23:50 UTC, merged