Smoke.mp4
DeltaV-Station/Delta-v pull request #931
Opened 2024-03-05 10:02 UTC by KittenColony

## About the PR
Adds several new cigarette brands in an attempt to shatter the monopoly Nomads and Interdyne have on the smokers market.

## Why / Balance
Nomads don't cut it anymore. The majority of people prefer Nomads for the fact that there isn't a better alternative.

## Technical details
adds a few .rsi files and some .yml files in the dV namespace

## Media
i'm trying 

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:

add: Added Several new cigarette brands.

2024-03-05 10:09 UTC, DangerRevolution reviewed
CandyCigCarton pls

2024-03-05 10:09 UTC, DangerRevolution commented on Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Smokeables/Cigarettes/cartons.yml
> +        amount: 5
```suggestion
        amount: 5

```

2024-03-05 10:09 UTC, DangerRevolution commented on Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +            Quantity: 10
```suggestion
            Quantity: 10

```

2024-03-05 10:09 UTC, DangerRevolution commented on Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
> +      amount: 5
```suggestion
      amount: 5
      
```

2024-03-05 10:09 UTC, DangerRevolution commented on Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
> +  id: CigPackCandy
Where's the carton of CandyCigPacks?

2024-03-05 10:09 UTC, DangerRevolution commented on Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
> +      amount: 5
It's good form apparently to leave a line at the end.

2024-03-05 10:09 UTC, DangerRevolution commented on Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +            Quantity: 10
It's good form apparently to leave a line at the end.

2024-03-05 10:15 UTC, KittenColony commented
its far from done, I still have to do beef cigarettes and [redacted], I'm just trying to get my dev-environment to work

2024-03-05 10:26 UTC, KittenColony commented on Resources/Prototypes/DeltaV/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
> +  id: CigPackCandy
:3

2024-03-08 07:26 UTC, KittenColony commented
fucking dev env wont work so im going to hope this currently works and try the other bits *later*

2024-03-08 08:15 UTC, KittenColony commented
why the fuck

2024-03-10 21:19 UTC, KittenColony commented
I give up

2024-03-11 05:35 UTC, KittenColony commented
I NO LONGER GIVE UP!

2024-03-11 05:57 UTC, KittenColony commented
I still need to add beef cigarettes and some other misc brands, as well as the vender contents but weh!

2024-03-22 04:43 UTC, KittenColony commented
why do I smell burning?

2024-03-28 19:10 UTC, DEATHB4DEFEAT requested changes

2024-03-28 19:10 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Catalog/Fills/Crates/service.yml
> +        prob: 0.33
```suggestion
        prob: 0.33 # DeltaV
```

2024-03-28 19:10 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Catalog/Fills/Crates/service.yml
> +        prob: 0.33
```suggestion
        prob: 0.33 # DeltaV
```

2024-03-28 19:10 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Catalog/Fills/Crates/service.yml
> +      - id: CigCartonCandy
```suggestion
      - id: CigCartonCandy # DeltaV
```

2024-03-28 19:10 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/cigs.yml
> +    CigPackCandy: 2 # Also DV
```suggestion
    CigPackCandy: 2 # DeltaV
```

2024-03-28 19:10 UTC, DEATHB4DEFEAT commented on Resources/Prototypes/Nyanotrasen/Entities/Markers/Spawners/Random/randomitems.yml
> +      - CigCartonCandy
```suggestion
      - CigCartonPurple # DeltaV
      - CigCartonCandy # DeltaV
```

2024-04-01 21:50 UTC, KittenColony commented
I should have put that in a long time ago

2024-04-02 05:54 UTC, DEATHB4DEFEAT approved these changes

2024-04-19 02:51 UTC, merged